Repository nuxt/nuxt, pull requests merged in 2019-02, with the labels that each got.

#4906 perf(ts): transpileOnly when using `nuxt-ts start`
  packages/typescript/src/index.js
  packages/typescript/test/setup.test.js
Labels: type: enhancement, typescript

#4907 chore(examples): zero-downtime pm2 typescript example
  examples/pm2-typescript/README.md
  examples/pm2-typescript/ecosystem.config.js
  examples/pm2-typescript/nuxt.config.ts
  examples/pm2-typescript/package.json
  examples/pm2-typescript/pages/index.vue
  examples/pm2-typescript/tsconfig.json
  examples/pm2-typescript/tslint.json
Labels: type: example

#4957 refactor(test): change cli.test to be more accurate
  test/unit/cli.test.js
  test/unit/utils.test.js
  test/utils/index.js
Labels: WIP

#5104 fix(types): reflect chainlable NuxtLoading methods
  packages/vue-app/types/index.d.ts
Labels: typescript

#5086 fix(nuxt-ts): error catch in nuxt-ts binary
  distributions/nuxt-ts/bin/nuxt-ts.js
  packages/cli/test/unit/__snapshots__/command.test.js.snap
Labels: typescript
