Repository nuxt/nuxt, pull requests merged in 2023-02, with the labels that each got.

#18594 docs: add `.env` to directory structure and improve config docs
  docs/2.guide/2.directory-structure/2.env.md
  docs/2.guide/3.going-further/10.runtime-config.md
Labels: documentation, 3.x

#18672 chore: bump test/dev dependencies
  jest.config.js
  package.json
  packages/generator/src/generator.js
  packages/types/package.json
  packages/types/test/vue.ts
  packages/utils/src/route.js
  packages/utils/test/serialize.test.input.js
  test/utils/index.js
  yarn.lock
Labels: 2.x, chore

#18670 chore: upgrade unjs dependencies
  packages/config/package.json
  packages/generator/package.json
  packages/server/package.json
  packages/utils/package.json
  packages/vue-app/package.json
  packages/vue-renderer/package.json
  packages/webpack/package.json
  test/dev/async-config.size-limit.test.js
  yarn.lock
Labels: 2.x, chore

#18650 docs: mention options api equivalent for `head()`
  docs/7.migration/4.meta.md
Labels: documentation, 3.x

#18679 chore: use named export from `defu`
  packages/cli/src/utils/config.js
  packages/config/src/load.js
  packages/config/src/options.js
  packages/generator/src/generator.js
  packages/vue-renderer/src/renderer.js
Labels: 2.x, chore

#18686 build: upgrade to rollup v3
  package.json
  scripts/rollup.config.js
  yarn.lock
Labels: 2.x, chore

#18706 fix(nuxt): make `onNuxtReady` safe to run on server-side
  docs/3.api/3.utils/on-nuxt-ready.md
  packages/nuxt/src/app/compat/idle-callback.ts
  packages/nuxt/src/app/composables/ready.ts
Labels: bug, 🔨 p3-minor-bug

#9671 feat(webpack)!: update postcss to v8
  .iyarc
  examples/tailwindcss-purgecss/nuxt.config.js
  examples/with-purgecss/nuxt.config.js
  packages/cli/test/unit/__snapshots__/webpack.test.js.snap
  packages/config/src/config/build.js
  packages/config/src/options.js
  packages/config/test/__snapshots__/options.test.js.snap
  packages/config/test/config/__snapshots__/index.test.js.snap
  packages/types/config/build.d.ts
  packages/webpack/package.json
  packages/webpack/src/utils/postcss-v8.js
  packages/webpack/src/utils/postcss.js
  packages/webpack/src/utils/style-loader.js
  renovate.json
  test/dev/basic.dev.test.js
  test/dev/basic.ssr.test.js
  test/dev/extract-css.test.js
  test/fixtures/basic/nuxt.config.js
  test/fixtures/basic/plugins/tailwind.js
  yarn.lock
Labels: enhancement, 2.x

#18733 fix(vite, webpack): omit magic keys when import of same name is detected
  docs/3.api/1.composables/use-async-data.md
  docs/3.api/1.composables/use-fetch.md
  docs/3.api/1.composables/use-lazy-async-data.md
  docs/3.api/1.composables/use-lazy-fetch.md
  docs/3.api/1.composables/use-state.md
  packages/vite/src/plugins/composable-keys.ts
Labels: bug, 🔨 p3-minor-bug

#18684 v2.16.0
  distributions/nuxt-start/package.json
  distributions/nuxt/package.json
  lerna.json
  packages/babel-preset-app/package.json
  packages/builder/package.json
  packages/cli/package.json
  packages/config/package.json
  packages/core/package.json
  packages/generator/package.json
  packages/server/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/vue-app/package.json
  packages/vue-renderer/package.json
  packages/webpack/package.json
Labels: 2.x, chore

#18734 perf(nuxt): cache result of importing styles module
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, performance

#18685 v3.1.2
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#18827 fix(deps): downgrade `@types` packages depending on webpack 5
  packages/types/package.json
  yarn.lock
Labels: types, 2.x

#18828 fix(webpack): client-side typechecking when `ssr: false`
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
Labels: bug, webpack

#18839 fix(config): let webpack merge postcss plugins
  packages/config/src/options.js
  packages/webpack/src/utils/postcss.js
  test/fixtures/basic/nuxt.config.js
Labels: 2.x, bug

#18752 fix(vite): exclude styles, not all assets
  packages/vite/src/plugins/paths.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#18553 feat(kit): add `addRouteMiddleware` method
  docs/3.api/4.advanced/2.kit.md
  packages/kit/src/pages.ts
Labels: 3.x, kit, 🍰 p2-nice-to-have

#18782 perf(vite): use stub entry in vite server build when `ssr: false `
  packages/nuxt/src/app/entry-spa.ts
  packages/vite/src/server.ts
Labels: enhancement, 3.x, bug, vite, performance

#18783 feat(nuxi): warn when prerendering routes with `ssr: false`
  docs/1.getting-started/10.deployment.md
  packages/nuxi/src/commands/build.ts
Labels: enhancement, documentation, 3.x, cli

#18652 feat(schema): add type hints for runtime config
  packages/schema/src/types/config.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/types.ts
Labels: enhancement, 3.x, schema

#18842 docs: add link to vue hydration mismatch docs
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation

#18526 feat(nuxt): infer `useFetch` return based on the method
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic/server/api/hey/index.get.ts
  test/fixtures/basic/types.ts
Labels: types, 3.x, bug, ❗ p4-important

#18864 feat(nuxi): add initial support for enabling/disabling devtools
  packages/nuxi/src/commands/devtools.ts
  packages/nuxi/src/commands/index.ts
Labels: enhancement, 3.x, cli

#18901 docs: add explanation with augmented meta for new routes
  docs/2.guide/2.directory-structure/1.pages.md
Labels: documentation, 3.x

#18902 refactor(nuxt): within nuxt app, import directly from source file
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/composables/head.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/app/plugins/debug.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/app/plugins/preload.server.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/head/runtime/composables.ts
  packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/plugins/prefetch.client.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/src/pages/runtime/router.options.ts
  packages/nuxt/src/pages/runtime/validate.ts
  test/bundle.test.ts
Labels: 3.x, chore

#18843 v3.2.0
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#18888 docs: add info for `nuxi devtools` command
  docs/3.api/5.commands/devtools.md
Labels: documentation, 3.x

#18931 fix(schema): allow type inference of arrays in runtime config
  packages/schema/src/types/config.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/types.ts
Labels: bug, ❗ p4-important, schema

#18948 fix(nuxt): avoid recursive import in nitro renderer
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 🔨 p3-minor-bug

#18884 v2.16.1
  distributions/nuxt-start/package.json
  distributions/nuxt/package.json
  lerna.json
  packages/builder/package.json
  packages/cli/package.json
  packages/config/package.json
  packages/core/package.json
  packages/types/package.json
  packages/webpack/package.json
Labels: 2.x, chore

#18905 ci: run webpack/vite and dev/prod as matrices
  .github/workflows/ci.yml
  .nuxtrc
  package.json
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/hmr.test.ts
  test/utils.ts
  vitest.config.ts
Labels: chore

#18922 fix(nuxt): expose `nuxt/schema` subpath for augmentation
  docs/2.guide/2.directory-structure/3.app-config.md
  docs/2.guide/3.going-further/10.runtime-config.md
  packages/nuxt/config.d.ts
  packages/nuxt/package.json
  packages/nuxt/schema.d.ts
  packages/nuxt/schema.mjs
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/config.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/runtime/composables.ts
  packages/nuxt/src/head/runtime/index.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/imports/transform.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/router.options.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/scan-components.test.ts
  packages/nuxt/types.d.ts
Labels: 3.x, bug, chore

#19001 fix(nitro): ensure ssr error `statusCode` is a number
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#18998 fix(vue-renderer): insert `charset` before `title`
  packages/vue-renderer/src/renderers/spa.js
  packages/vue-renderer/src/renderers/ssr.js
  test/dev/basic.ssr.test.js
Labels: 2.x, 🔨 p3-minor-bug

#19009 fix(schema): transpile `nuxt/app` by default
  packages/nuxt/src/core/nuxt.ts
Labels: bug, 🔨 p3-minor-bug, schema

#9772 feat(types): add basic types for Nuxt interface
  packages/types/config/module.d.ts
  packages/types/nuxt.d.ts
Labels: enhancement, 2.x

#18967 docs: flatten top-level project in layers example
  docs/2.guide/3.going-further/7.layers.md
Labels: documentation, 3.x

#19032 perf(nuxt): allow tree-shaking empty meta from build
  packages/nuxt/src/pages/page-meta.ts
  packages/nuxt/src/pages/utils.ts
Labels: enhancement, 3.x

#19061 docs: add note about nested directory order
  docs/2.guide/2.directory-structure/1.components.md
Labels: documentation, 3.x

#18464 docs: updated public directory explanation
  docs/7.migration/2.configuration.md
Labels: documentation, 3.x

#19083 docs: add information on when mw runs & how to skip
  docs/2.guide/2.directory-structure/1.middleware.md
Labels: documentation, 3.x

#19038 feat(nuxt): add experimental `app:chunkError` hook and reload strategy
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/chunk-error.ts
  packages/webpack/src/plugins/chunk.ts
  packages/webpack/src/webpack.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/chunk-error.vue
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/plugins/chunk-error.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19053 fix(vite): respect `isCustomElement` config for jsx transform
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/vite.ts
  packages/schema/src/types/config.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/components/Tsx.tsx
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/jsx.vue
Labels: 3.x, vite

#18951 fix(nuxt): use parser to treeshake client-only declarations
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/test/__snapshots__/treeshake-client.test.ts.snap
  packages/nuxt/test/fixture/components/client/ComponentWithProps.vue
  packages/nuxt/test/fixture/components/client/WithClientOnlySetup.vue
  packages/nuxt/test/scan-components.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/nuxt/test/utils.ts
  test/fixtures/basic/pages/client-only-components.vue
Labels: 3.x, bug

#18959 fix(nuxi): pass through exit code from test errors
  packages/nuxi/src/cli.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, test-utils

#19073 perf(nuxt): animate transform rather than width
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: 3.x, performance

#19055 fix(nuxi): read `devServer` options from nuxt config
  packages/nuxi/src/commands/dev.ts
  packages/schema/src/config/dev.ts
Labels: 3.x, cli, 🔨 p3-minor-bug

#19085 fix(nuxt): validate no `//` in path when constructing payload url
  packages/nuxt/src/app/composables/payload.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#18593 fix(nuxt): respect redirects which differ only by trailing slash
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/fixtures/basic/middleware/redirect.global.ts
  test/fixtures/basic/pages/navigate-to.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#19099 fix(nuxt): pass nuxt + workspace paths when importing builder
  packages/nuxt/src/core/builder.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19111 chore: increase node 14 minor version constraint
  package.json
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#19112 fix: add minimum node 14.18 version constraint
  packages/babel-preset-app/package.json
  packages/builder/package.json
  packages/cli/package.json
  packages/cli/src/utils/dependencies.js
  packages/config/package.json
  packages/core/package.json
  packages/generator/package.json
  packages/server/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/vue-app/package.json
  packages/vue-renderer/package.json
  packages/webpack/package.json
Labels: 2.x, bug, chore

#19082 v3.2.1
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#19131 fix(nuxi): restart nuxt when `distDir` is unlinked
  packages/nuxi/src/commands/dev.ts
Labels: 3.x, dx, cli, 🔨 p3-minor-bug

#19108 fix(config): upgrade md4 -> md5 on node > 16
  packages/config/src/options.js
Labels: 2.x, bug, webpack

#19166 fix(webpack): use default export from webpack
  packages/webpack/src/plugins/chunk.ts
Labels: bug, webpack, ❗ p4-important

#18585 fix(vue-app): handle promise rejection from `asyncData`
  packages/vue-app/template/server.js
Labels: 2.x, bug, 🔨 p3-minor-bug

#19192 fix(nuxt): preserve (re)named imports in meta
  packages/nuxt/src/pages/page-meta.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19187 fix(nuxt): log errors thrown when booting the nuxt app
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, dx, bug

#19309 fix(nuxt): preserve explicit `rel` attribute on internal link
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, 🔨 p3-minor-bug

#19261 fix(nuxt): compatible route object for custom external routes
  packages/nuxt/src/app/components/nuxt-link.ts
  test/bundle.test.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#19256 fix(vite): handle non-iterable `noExternal` option
  packages/vite/src/utils/external.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#19315 perf(nuxt): don't update manifest in dev mode
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, 🍰 p2-nice-to-have

#19317 v3.2.3
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x

#19335 perf(nuxt): increase static asset maxAge to 1yr
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, ❗ p4-important, performance
