Repository nuxt/nuxt, pull requests merged in 2023-03, with the labels that each got.

#19088 feat(nuxi): enforce consistent casing in filenames
  packages/nuxi/src/utils/prepare.ts
Labels: enhancement, cli

#18418 fix(nuxt): deprecate scanning directory index plugins
  docs/2.guide/2.directory-structure/1.plugins.md
  packages/kit/src/plugin.ts
  packages/nuxt/src/core/app.ts
Labels: 3.x, 🍰 p2-nice-to-have

#19084 feat(nuxi): reload nuxt when `restart` hook is called
  docs/3.api/4.advanced/1.hooks.md
  packages/nuxi/src/commands/dev.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x, cli, 🍰 p2-nice-to-have

#19249 feat(nuxt): scan composables with star export
  examples/auto-imports/composables/app.vue
  packages/kit/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/composables/export-star.ts
  test/fixtures/basic/composables/foo.ts
  test/fixtures/basic/composables/nested/bar.ts
  test/fixtures/basic/composables/template.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/utils/useBar.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19365 v2.16.2
  distributions/nuxt-start/package.json
  distributions/nuxt/package.json
  lerna.json
  packages/babel-preset-app/package.json
  packages/builder/package.json
  packages/cli/package.json
  packages/config/package.json
  packages/core/package.json
  packages/generator/package.json
  packages/server/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/vue-app/package.json
  packages/vue-renderer/package.json
  packages/webpack/package.json
Labels: 2.x, chore

#19379 fix(nuxt): prevent fallthrough attributes on custom `NuxtLink`
  packages/nuxt/src/app/components/nuxt-link.ts
  test/bundle.test.ts
Labels: 3.x, 🔨 p3-minor-bug

#19044 fix(types): add return type for `error()`
  packages/types/app/index.d.ts
Labels: types, 2.x, 🔨 p3-minor-bug

#19243 feat(vite): add `node_modules` and buildDir to `x_google_ignoreList`
  packages/vite/src/vite.ts
Labels: enhancement, 3.x, vite, 🍰 p2-nice-to-have

#19397 chore: bump edge version based on commits
  scripts/bump-edge.ts
Labels: chore

#19338 fix(schema): update vite `import.meta` types
  packages/nuxt/src/app/config.ts
  packages/schema/src/types/global/vite.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#18641 feat(nuxi): cli wrapper for self restart
  docs/3.api/4.advanced/1.hooks.md
  packages/nuxi/bin/nuxi.mjs
  packages/nuxi/build.config.ts
  packages/nuxi/src/cli-run.ts
  packages/nuxi/src/cli-wrapper.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/constants.ts
  packages/nuxi/src/index.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x

#19173 feat(schema): allow adding page routes without a matching file
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/treeshake-client.test.ts.snap
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x

#19422 feat(nuxt): add support for `nuxt/kit` subpath for local use
  packages/nuxt/kit.d.ts
  packages/nuxt/kit.mjs
  packages/nuxt/package.json
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19434 fix(nuxt): don't print layout warning if page is not ssr
  packages/nuxt/src/app/composables/router.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19394 feat(nuxt): auto-register modules in `~/modules`
  docs/2.guide/2.directory-structure/1.modules.md
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/common.ts
  test/basic.test.ts
  test/fixtures/basic/modules/auto-registered/index.ts
  test/fixtures/basic/modules/auto-registered/runtime/handler.ts
  test/fixtures/basic/modules/example.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19423 refactor(nuxi): hard restart with communication channel
  packages/nuxi/src/cli-run.ts
  packages/nuxi/src/cli-wrapper.ts
  packages/nuxi/src/cli.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/constants.ts
  packages/nuxi/src/index.ts
Labels: 3.x, cli

#19448 docs: add edge banners on `versions` and modules
  docs/2.guide/2.directory-structure/1.modules.md
  docs/2.guide/3.going-further/1.internals.md
Labels: documentation, 3.x

#19172 feat(nuxt): enable config schema by default
  packages/nuxt/src/core/schema.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/config.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/types.ts
Labels: 3.x, 🍰 p2-nice-to-have

#19450 fix(kit): match commit hashes of other lengths
  packages/kit/src/compatibility.ts
Labels: 3.x, bug, kit

#19252 feat(kit,nuxt): add component `priority` to allow overriding
  packages/kit/src/components.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/test/scan-components.test.ts
  packages/schema/src/types/components.ts
Labels: enhancement, 3.x, kit, 🍰 p2-nice-to-have

#19120 feat(nuxt): enable preloading object-syntax routes
  packages/nuxt/src/app/composables/preload.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19486 docs: update `devServer.https` example
  packages/schema/src/config/dev.ts
Labels: documentation, 3.x

#19458 feat(nuxt): support `trailingSlashBehavior` in `defineNuxtLink`
  docs/3.api/2.components/4.nuxt-link.md
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/nuxt-link/trailing-slash.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19383 feat(nuxt): allow configuring treeshakeable composables
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/schema/src/config/build.ts
  test/basic.test.ts
  test/fixtures/basic/composables/tree-shake.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/tree-shake.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19369 feat(nuxi,schema): add support for setting nuxt `logLevel`
  packages/nuxi/src/commands/analyze.ts
  packages/nuxi/src/commands/build.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/commands/prepare.ts
  packages/nuxi/src/commands/typecheck.ts
  packages/schema/src/config/build.ts
  packages/vite/src/vite.ts
  packages/webpack/src/presets/base.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19509 docs: add new release cycle info
  docs/5.community/6.roadmap.md
Labels: documentation

#19490 feat(nuxt): support custom keyed composables
  packages/schema/src/config/build.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/vite.ts
  packages/webpack/src/webpack.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/keyed-composables.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19508 perf(vite): mark more core functions as side-effect free
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  test/bundle.test.ts
Labels: enhancement, 3.x, vite, performance

#19371 feat(cli): programmatically pass nuxt config overrides (to dev)
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/commands/index.ts
  packages/nuxi/src/run.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19523 feat(vite): use custom logger to show vite logs
  packages/schema/src/config/vite.ts
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/utils/logger.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, vite

#19086 feat(nuxt): enable chunk error handling by default
  docs/1.getting-started/8.error-handling.md
  docs/3.api/3.utils/reload-nuxt-app.md
  packages/nuxt/src/app/composables/chunk.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/app/plugins/restore-state.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/chunk-error.vue
  test/fixtures/basic/pages/index.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19532 fix(nuxt): exclude nitro output dir from type checking
  packages/nuxt/src/core/nitro.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#19531 fix(vite): allow disabling clear screen behaviour
  packages/schema/src/config/vite.ts
  packages/vite/src/utils/logger.ts
Labels: 3.x, bug, vite

#19356 docs: update $fetch documentation
  docs/3.api/3.utils/$fetch.md
Labels: documentation, 3.x

#19556 ci: lint workflows
  .github/workflows/docs-e2e.yml
  .github/workflows/introspect.yml
  docs/1.getting-started/11.testing.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/3.going-further/4.kit.md
  docs/3.api/3.utils/preload-route-components.md
  docs/4.examples/6.advanced/testing.md
  scripts/crawl.mjs
Labels: 3.x, chore

#19530 feat(nuxt): add `watch` option and refactor dev server restarting
  packages/nuxi/src/commands/dev.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/common.ts
Labels: enhancement, 3.x

#19558 test: close pages after use
  test/basic.test.ts
  test/hmr.test.ts
  test/utils.ts
Labels: 3.x, chore, test

#19553 fix(nuxt): only log boot errors on client-side
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#19563 fix(nuxt): dedupe payload cache by payload url
  packages/nuxt/src/app/composables/payload.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19555 chore(nuxt): update to new `hasProtocol` options format
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/router.ts
Labels: 3.x, bug, chore, 🍰 p2-nice-to-have

#19548 feat(nuxt): add `useHeadSafe` and remove layer around head imports
  docs/3.api/1.composables/use-head-safe.md
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/composables/head.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/runtime/components.ts
  packages/nuxt/src/head/runtime/composables.ts
  packages/nuxt/src/head/runtime/index.ts
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  packages/nuxt/src/head/runtime/plugins/vueuse-head-polyfill.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
  packages/schema/src/config/app.ts
  packages/schema/src/index.ts
  packages/schema/src/types/config.ts
  packages/schema/src/types/head.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/head-script-setup.vue
  test/fixtures/basic/plugins/my-plugin.ts
  tsconfig.json
Labels: enhancement, 3.x, refactor, performance

#18648 feat(kit, schema): measure module setup timings
  packages/kit/src/module/define.ts
  packages/kit/src/module/install.ts
  packages/schema/src/types/module.ts
Labels: enhancement, 3.x

#19537 refactor(kit,nuxi): resolve module paths using node algorithm
  packages/kit/src/index.ts
  packages/kit/src/internal/cjs.ts
  packages/kit/src/internal/esm.ts
  packages/kit/src/loader/nuxt.ts
  packages/kit/src/module/install.ts
  packages/nuxi/src/commands/build-module.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/commands/typecheck.ts
  packages/nuxi/src/utils/cjs.ts
  packages/nuxi/src/utils/esm.ts
  packages/nuxi/src/utils/kit.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/head/module.ts
Labels: 3.x, bug, kit

#19599 chore: improve internal type safety
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: chore

#19607 fix(nuxt): avoid injecting adhoc modules in schema
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19487 fix(nuxt): improve types for data fetching with `transform`
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic/types.ts
Labels: types, 3.x, bug

#19601 fix(nuxi): resolve kit from nuxt modules dir
  packages/nuxi/src/utils/kit.ts
Labels: 3.x, bug, cli, 🔨 p3-minor-bug

#19602 fix(nuxt,schema): merge custom and resolved app configs
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/types/config.ts
  test/fixtures/basic/nuxt.schema.ts
  test/fixtures/basic/types.ts
Labels: 3.x, bug, schema

#19608 fix(nuxt): resolve builder using esm syntax
  packages/nuxt/src/core/builder.ts
Labels: 3.x, bug, ❗ p4-important

#19621 fix(nuxt): exclude `boolean` from inline module definitions
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#19635 refactor(nuxt): let mlly handle search paths
  packages/kit/src/internal/esm.ts
  packages/nuxt/src/core/builder.ts
Labels: 3.x, refactor

#18516 fix(schema): show `payloadExtraction` warning only when unset
  packages/nuxi/src/commands/build.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug

#19489 feat(nuxt): support app config for server routes
  docs/2.guide/2.directory-structure/3.app-config.md
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/config.ts
  test/basic.test.ts
  test/fixtures/basic/server/api/app-config.ts
Labels: enhancement, 3.x, nitro, 🍰 p2-nice-to-have

#19643 fix(nuxt): mark non-augmented NuxtApp properties as unknown
  .eslintrc
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/fixtures/basic/types.ts
Labels: enhancement, 3.x, bug

#19638 feat(nuxt): add `nitro:build:public-assets` hook
  docs/3.api/4.advanced/1.hooks.md
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x, nitro, 🍰 p2-nice-to-have

#19669 fix(nuxt): fix default injection type for plugins
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/fixtures/basic/types.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19524 v3.3.0
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/2.directory-structure/1.modules.md
  docs/2.guide/3.going-further/1.internals.md
  docs/3.api/2.components/1.nuxt-client-fallback.md
  docs/3.api/2.components/4.nuxt-link.md
  docs/3.api/4.advanced/1.hooks.md
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#19676 fix(nuxi): use file url to start nuxi
  packages/nuxi/src/cli-wrapper.ts
Labels: bug, cli, 🔥 p5-urgent

#19687 fix(kit): provide name to `performance.mark()`
  packages/kit/src/module/define.ts
Labels: 3.x, bug, kit, ❗ p4-important

#18551 docs: update module author guide
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#19730 test: remove sourcemaps from minimal test
  test/bundle.test.ts
  test/fixtures/minimal/nuxt.config.ts
Labels: 3.x, chore, test

#19518 fix(config): move `preset` to inner `postcssOptions`
  examples/with-purgecss/nuxt.config.js
  packages/config/src/config/build.js
  packages/config/test/__snapshots__/options.test.js.snap
  packages/config/test/config/__snapshots__/index.test.js.snap
  packages/webpack/src/utils/postcss.js
  test/fixtures/custom-dirs/nuxt.config.js
  test/fixtures/extract-css/nuxt.config.js
Labels: 2.x

#19745 chore: add internal types for nitro/app
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  tsconfig.json
Labels: 3.x, chore

#19755 fix(webpack): add `node-fetch-native` to externals list
  packages/webpack/src/config/server.js
Labels: 2.x, bug, ❗ p4-important

#19773 fix(webpack): transpile app directory
  packages/webpack/src/presets/base.ts
Labels: 3.x, bug, webpack, ❗ p4-important

#19753 fix(nuxt): unset context after app is created
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  test/bundle.test.ts
Labels: 3.x, bug, ❗ p4-important

#19736 fix(nuxi): watch dist and register restart hook after nuxt is ready
  packages/nuxi/src/commands/dev.ts
Labels: 3.x, bug, cli

#19684 fix(nuxt): ignore falsy modules
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/common.ts
  test/fixtures/basic/extends/bar/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, 🍰 p2-nice-to-have

#19713 fix(nuxt): use `h3` utilities to set response status/code
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  test/basic.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#18743 docs: improve swr documentation
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#19225 docs: add another example for `useAsyncData`
  docs/3.api/1.composables/use-async-data.md
Labels: documentation, 3.x

#19336 docs: add serialization section to data fetching
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#19829 fix(nuxt): handle external navigation to api routes
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/navigate-to-api.vue
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#19789 feat(types): support nuxt types for `defineComponent`
  packages/types/app/vue.d.ts
  packages/types/test/vue.ts
Labels: 2.x

#19802 fix(nuxt): observe slot element in custom nuxt-link
  packages/nuxt/src/app/components/nuxt-link.ts
  test/bundle.test.ts
Labels: 3.x

#19605 fix(nuxt): directly render server components
  docs/2.guide/2.directory-structure/1.components.md
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/components/AsyncServerComponent.server.vue
  test/fixtures/basic/components/islands/LongAsyncComponent.vue
  test/fixtures/basic/pages/islands.vue
  test/fixtures/basic/server/api/very-long-request.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19842 fix(vite): support multiple rollup entries
  packages/vite/src/client.ts
  packages/vite/src/server.ts
Labels: bug, vite, 🔨 p3-minor-bug

#19835 fix(nuxt): ignore schema types that eval to any
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19822 fix(nuxt): use prerender cache for islands
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#19830 fix(kit): check if nuxt is restarting before updating templates
  packages/kit/src/template.ts
Labels: bug, kit, 🔨 p3-minor-bug

#19825 perf(nuxt): experimentally disable vue server renderer nitro endpoint
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, nitro, 🍰 p2-nice-to-have

#19874 fix(kit): add legacy entrypoints for pre v3.3 usage
  packages/kit/package.json
Labels: 3.x, bug, kit

#19875 v3.3.2
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x

#19937 fix(schema): prefer src to rootDir aliases
  packages/schema/src/config/common.ts
Labels: dx, bug, 🍰 p2-nice-to-have, schema

#19934 fix(nuxt): don't override options signature with schema
  packages/nuxt/src/core/schema.ts
Labels: types, bug, 🔨 p3-minor-bug

#19962 chore: use pnpm workspace protocol internally
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
  scripts/_utils.ts
  scripts/bump-edge.ts
Labels: 3.x, chore

#19968 fix(vite): allow extending vue config per-environment
  packages/kit/src/build.ts
  packages/schema/src/types/config.ts
  packages/schema/src/types/hooks.ts
  packages/vite/src/client.ts
  packages/vite/src/css.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
Labels: enhancement, 3.x, vite, 🍰 p2-nice-to-have

#19936 fix(webpack): transpile rest of nuxt runtime directories
  packages/webpack/src/presets/base.ts
Labels: bug, webpack, ❗ p4-important

#20002 fix(nuxt): suppress handled errors
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20011 refactor(vite): use rollup types re-exported from vite
  packages/vite/src/client.ts
  packages/vite/src/plugins/virtual.ts
Labels: 3.x, vite, refactor

#20013 fix(vite): remove separate rollup dependency
  packages/vite/package.json
  pnpm-lock.yaml
Labels: 3.x, bug, vite, refactor, 🍰 p2-nice-to-have

#19987 fix(nuxt): sync `setResponseStatus` signature with h3
  docs/3.api/3.utils/set-response-status.md
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/composables/ssr.ts
Labels: dx, bug, 🍰 p2-nice-to-have
