Repository nuxt/nuxt, pull requests merged in 2023-07, with the labels that each got.

#21879 docs: describe environment override feature
  docs/1.getting-started/3.configuration.md
Labels: documentation

#21884 test: add `nuxt-vitest` and composable unit tests
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  test/nuxt/composables.test.ts
  tsconfig.json
  vitest.config.ts
  vitest.nuxt.config.ts
Labels: 3.x, chore, test

#21751 fix(nuxt): stop loading indicator on navigation failure
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/fixtures/basic/extends/node_modules/foo/layouts/default.vue
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/middleware-abort-non-fatal.vue
Labels: 3.x

#21912 fix(nuxi): respect nitro ssl cert/key variables
  packages/nuxi/src/commands/dev.ts
Labels: 3.x, bug, cli, 🔨 p3-minor-bug

#21916 perf(nuxt): allow hmr for server components in dev mode
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/module.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21659 fix(nuxt): support custom route names from meta with `typedPages`
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
  test/fixtures/basic-types/pages/custom-name.vue
  test/fixtures/basic-types/types.ts
Labels: enhancement, types, 3.x, pages, 🔨 p3-minor-bug

#21934 fix(nuxt): regenerate imports after template
  packages/nuxt/src/imports/module.ts
Labels: 3.x, bug

#21891 fix(vite): fix issue detecting shadowed keyed composables
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/test/composable-keys.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/other-composables-folder/custom-keyed-composable.ts
  test/fixtures/basic/pages/keyed-composables/index.vue
  test/fixtures/basic/pages/keyed-composables/local.vue
Labels: 3.x, bug

#21904 fix(nuxt): use `$fetch.raw` in dev client mode for islands
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x, bug

#21847 fix(schema): warn if user provides `vite.publicDir`
  packages/schema/src/config/vite.ts
  packages/schema/src/types/config.ts
Labels: 3.x, vite, 🍰 p2-nice-to-have, 🔨 p3-minor-bug, schema

#21823 fix(nuxt): preserve old vnode when leaving nested route
  packages/nuxt/src/app/components/injections.ts
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/components/route-provider.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/suspense.vue
  test/fixtures/basic/pages/suspense/async-[parent].vue
  test/fixtures/basic/pages/suspense/async-[parent]/async-[child].vue
  test/fixtures/basic/pages/suspense/async-[parent]/sync-[child].vue
  test/fixtures/basic/pages/suspense/sync-[parent].vue
  test/fixtures/basic/pages/suspense/sync-[parent]/async-[child].vue
  test/fixtures/basic/pages/suspense/sync-[parent]/sync-[child].vue
Labels: 3.x, bug, upstream, 🔨 p3-minor-bug, suspense

#21957 perf(nuxt): use getters when constructing reactive routes
  packages/nuxt/src/app/components/route-provider.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, 🔨 p3-minor-bug, performance

#21959 fix(kit): ignore telemetry startup time (as it has prompt)
  packages/kit/src/module/define.ts
Labels: 3.x, bug, kit

#21977 docs: fix accessing custom props from child pages
  docs/3.api/2.components/2.nuxt-page.md
Labels: documentation, 3.x

#21966 fix(vite): pass modulesDir to `isExternal`
  packages/vite/src/dev-bundler.ts
  packages/vite/src/utils/external.ts
  packages/vite/src/vite-node.ts
Labels: 3.x, bug, vite

#22049 perf(nuxt): prepopulate island payloads from rendered html
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/utils.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#22088 fix(nuxt): add pages in correct hook when generating
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, ❗ p4-important

#22118 docs: prefix internal links with `/`
  docs/1.getting-started/4.styling.md
Labels: documentation

#22142 refactor(cli,schema): add `bundler` module resolution flag
  packages/nuxi/src/utils/prepare.ts
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/typescript.ts
  test/fixtures/basic-types/nuxt.config.ts
Labels: 3.x, cli, schema

#22140 fix(nuxt): skip view transitions where there is no route change
  packages/nuxt/src/app/plugins/view-transitions.client.ts
Labels: 3.x, bug

#22074 fix(nuxt): skip scanning components that do not produce a name
  packages/nuxt/src/components/scan.ts
Labels: 3.x, bug

#21997 fix(cli): add aliases to monorepo paths to tsconfig includes
  packages/nuxi/src/utils/prepare.ts
Labels: 3.x, bug, cli

#22192 fix(nuxt): don't redirect if initial path has trailing slash
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug

#22189 docs: add runtime storage configuration examples
  docs/2.guide/2.directory-structure/1.server.md
Labels: documentation, 3.x

#22081 docs: add instruction on how to use other modules in a module
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#22157 docs: standardize indentation and tag positioning
  docs/1.getting-started/3.configuration.md
  docs/1.getting-started/4.styling.md
  docs/1.getting-started/5.routing.md
  docs/1.getting-started/5.seo-meta.md
  docs/1.getting-started/6.data-fetching.md
  docs/1.getting-started/7.state-management.md
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/2.guide/1.concepts/2.vuejs-development.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/2.directory-structure/1.composables.md
  docs/2.guide/2.directory-structure/1.layouts.md
  docs/2.guide/2.directory-structure/1.middleware.md
  docs/2.guide/2.directory-structure/1.pages.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/2.guide/3.going-further/10.runtime-config.md
  docs/2.guide/3.going-further/2.hooks.md
  docs/3.api/1.composables/use-cookie.md
  docs/3.api/1.composables/use-lazy-async-data.md
  docs/3.api/1.composables/use-lazy-fetch.md
  docs/3.api/1.composables/use-nuxt-app.md
  docs/3.api/1.composables/use-request-headers.md
  docs/3.api/1.composables/use-request-url.md
  docs/3.api/1.composables/use-route.md
  docs/3.api/2.components/2.nuxt-page.md
  docs/3.api/2.components/3.nuxt-layout.md
  docs/3.api/3.utils/$fetch.md
  docs/3.api/3.utils/create-error.md
  docs/3.api/3.utils/define-page-meta.md
  docs/3.api/3.utils/navigate-to.md
  docs/3.api/3.utils/refresh-nuxt-data.md
  docs/6.bridge/1.overview.md
  docs/7.migration/4.meta.md
  docs/7.migration/6.pages-and-layouts.md
  docs/7.migration/7.component-options.md
  docs/7.migration/8.runtime-config.md
Labels: documentation, 3.x

#22009 fix(nuxt): add `baseURL` to island fetch requests
  packages/nuxt/src/app/components/nuxt-island.ts
  test/basic.test.ts
Labels: 3.x, bug

#22200 fix(nuxt): ensure we only increment hydrating count once
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/hydration/spa-redirection/end.vue
  test/fixtures/basic/pages/hydration/spa-redirection/start.vue
Labels: 3.x, bug, ❗ p4-important

#22198 fix(nuxt): avoid premature hydration when using async layouts
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/core/templates.ts
  test/basic.test.ts
  test/fixtures/basic/pages/hydration/layout.vue
Labels: 3.x, bug, ❗ p4-important

#22216 fix(test-utils): pass along error if server can't start
  packages/test-utils/src/server.ts
Labels: 3.x, bug, test-utils

#22214 perf(nuxt,schema): do not watch `buildDir` and `node_modules`
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/transform.ts
  packages/nuxt/src/core/builder.ts
  packages/schema/src/config/common.ts
  test/setup.ts
Labels: 3.x, bug, schema

#22239 ci: add ecosystem-ci pr comment trigger
  .github/workflows/ecosystem-ci-trigger.yml
  .github/workflows/release-pr.yml
Labels: 3.x, chore

#22241 ci: add semantic pull request workflow
  .github/workflows/semantic-pull-requests.yml
Labels: 3.x, chore

#22264 fix(nuxt): access resolved `scrollBehaviorType`
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#22258 fix(nuxt): add overloads for `asyncData` generic + default
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, bug

#22305 fix(webpack): remove legacy support for `build.extend`
  packages/webpack/src/utils/config.ts
Labels: 3.x, webpack, ⚠️ breaking change

#22302 feat(schema,vite): allow `$client` and `$server` vite env overrides
  packages/schema/src/config/vite.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
Labels: enhancement, 3.x, vite, schema

#22304 feat(schema,webpack): allow `$client` and `$server` overrides
  packages/schema/src/types/config.ts
  packages/webpack/package.json
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/presets/assets.ts
  packages/webpack/src/presets/base.ts
  packages/webpack/src/presets/esbuild.ts
  packages/webpack/src/presets/node.ts
  packages/webpack/src/presets/pug.ts
  packages/webpack/src/presets/style.ts
  packages/webpack/src/presets/vue.ts
  packages/webpack/src/utils/config.ts
  packages/webpack/src/webpack.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, webpack, schema

#22324 ci: pin actionlint script
  .github/workflows/introspect.yml
Labels: 3.x, chore

#22323 fix(nuxt): allow `validate` return typing to be either error or boolean
  packages/nuxt/src/pages/runtime/composables.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#22322 chore: dedupe and bump semver
  pnpm-lock.yaml
Labels: 3.x, chore

#22333 fix(nuxt): pass (and handle) relative paths in `builder:watch`
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
Labels: 3.x, dx, bug, ❗ p4-important

#22336 refactor(nuxi,schema): move loading template into schema
  packages/nuxi/src/commands/dev.ts
  packages/nuxt/package.json
  packages/schema/package.json
  packages/schema/src/config/dev.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, cli, schema

#22340 chore(deps): bump typescript/untyped versions
  package.json
  packages/kit/package.json
  packages/kit/src/loader/config.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/templates.ts
  packages/schema/package.json
  pnpm-lock.yaml
  renovate.json
Labels: 3.x, chore

#18812 docs: add example for accessing vite config programmatically
  docs/3.api/4.advanced/2.kit.md
Labels: documentation, 3.x, kit

#21741 feat(nuxt): allow dynamic `scrollToTop` page meta
  docs/3.api/3.utils/define-page-meta.md
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#22366 fix(nuxt): disallow redirects to more script protocols
  package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/composables/router.ts
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x, bug, ❗ p4-important

#21935 feat(nuxt): expose filtered templates in `app:templatesGenerated` hook
  packages/nuxt/src/core/app.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#22384 perf(nuxt): write templates in single sync step + improve logs
  packages/kit/src/internal/template.ts
  packages/nuxt/src/core/app.ts
Labels: enhancement, 3.x, performance

#22179 feat(nuxt): render all head tags on server with `unhead`
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  test/bundle.test.ts
Labels: enhancement, 3.x

#22307 fix(nuxt): test `watch` paths against all layer `srcDir`s
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/common.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21747 feat(nuxt): auto-install `@nuxt/webpack-builder` when needed
  packages/nuxt/package.json
  packages/nuxt/src/core/features.ts
  packages/nuxt/src/core/nuxt.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, webpack, 🍰 p2-nice-to-have

#21592 feat(nuxt): allow remote sources for islands
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: enhancement, 3.x

#20726 feat(nuxt): environment-specific plugin execution for islands
  packages/nuxt/src/app/nuxt.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/components/islands/LongAsyncComponent.vue
  test/fixtures/basic/plugins/server-only.server.ts
Labels: enhancement, 3.x

#22385 feat(kit,nuxi): add `writeTypes` utility
  packages/kit/src/internal/cjs.ts
  packages/kit/src/template.ts
  packages/nuxi/src/commands/build.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/commands/prepare.ts
  packages/nuxi/src/commands/typecheck.ts
  packages/nuxi/src/utils/cjs.ts
  packages/nuxi/src/utils/prepare.ts
Labels: enhancement, 3.x, kit, cli

#22362 feat(nuxt): autocomplete layouts in `setPageLayout`/`<NuxtLayout>`
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/module.ts
Labels: enhancement, 3.x, dx

#20808 docs: add recommendation to install nuxtr
  docs/1.getting-started/2.installation.md
Labels: documentation, 3.x

#21793 perf(nuxt): render css/inline css higher than resource hints
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, performance

#22413 refactor(nuxt): use `nuxi-ng` for edge releases
  scripts/bump-edge.ts
Labels: 3.x, chore

#22418 fix(nuxt): support uppercase route methods in `useFetch`
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug
