Repository nuxt/nuxt, pull requests merged in 2023-12, with the labels that each got.

#24468 ci: label pull requests based on their target branch
  .github/workflows/label-pr.yml
Labels: 3.x, 2.x, chore

#24565 ci: update options for GitHub app token generation
  .github/workflows/ecosystem-ci-trigger.yml
Labels: 3.x

#24602 docs: update Nuxt 2 EOL date in roadmap
  docs/5.community/6.roadmap.md
Labels: 3.x

#24574 docs: prefer `~` to `@` alias in examples
  docs/1.getting-started/4.assets.md
  docs/1.getting-started/4.styling.md
  packages/schema/src/config/app.ts
Labels: 3.x

#24608 fix(vite,webpack): don't add type checker/analyzer when testing
  packages/nuxt/src/core/nitro.ts
  packages/vite/src/client.ts
  packages/vite/src/vite.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, test-utils

#24605 fix(nuxt): do not try auto-install outside of a Nuxt context
  packages/nuxt/src/components/loader.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, test-utils

#24612 docs: warn about using different env variables for `runtimeConfig`
  docs/2.guide/3.going-further/10.runtime-config.md
Labels: 3.x

#24639 fix(nuxt): merge and apply layer hooks
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#24675 docs: update props section in nuxt-page.md
  docs/3.api/1.components/2.nuxt-page.md
Labels: 3.x

#24659 chore: update vitest dependencies
  .github/workflows/autofix.yml
  .github/workflows/ci.yml
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/nuxt/test/__snapshots__/treeshake-client.test.ts.snap
  packages/nuxt/test/auto-imports.test.ts
  packages/nuxt/test/devonly.test.ts
  packages/nuxt/test/islandTransform.test.ts
  packages/vite/package.json
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic-types/package.json
  test/hmr.test.ts
  test/nuxt/composables.test.ts
  test/nuxt/nuxt-island.test.ts
  test/runtime-compiler.test.ts
  test/utils.ts
  vitest.config.ts
  vitest.nuxt.config.ts
Labels: 3.x, chore, test

#24674 feat(nuxt): add path to `error.data` when throwing 404 errors
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/src/pages/runtime/validate.ts
  test/basic.test.ts
  test/fixtures/basic/error.vue
Labels: 3.x

#23296 fix(nuxt): only add/remove trailing slash for http protocols
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#24680 docs: add more info about custom serialize/revive
  docs/1.getting-started/6.data-fetching.md
  docs/3.api/2.composables/use-nuxt-app.md
Labels: documentation, 3.x

#24707 feat(kit): load `/module` or `/nuxt` module subpath if it exists
  packages/kit/src/module/install.ts
  test/fixtures/basic/modules/subpath/index.ts
  test/fixtures/basic/modules/subpath/module.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#24709 feat(nuxt): layers support for spa loading template
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/app.ts
  test/basic.test.ts
Labels: 3.x

#24737 docs: fix grammar
  docs/2.guide/1.concepts/3.rendering.md
Labels: 3.x

#24736 perf(vite): avoid duplicate `resolve` operation
  packages/vite/src/manifest.ts
Labels: 3.x

#24730 perf(nuxt): avoid duplicate iterations over layers
  packages/nuxt/src/core/app.ts
Labels: 3.x

#24717 perf(kit): avoid duplicate `join` operation
  packages/kit/src/module/install.ts
Labels: 3.x

#24261 feat(nuxt): expose `refresh` on islands and server components
  docs/3.api/1.components/8.nuxt-island.md
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
  test/nuxt/nuxt-island.test.ts
Labels: enhancement, 3.x, server components

#24564 feat(nuxt): add `dedupe` option for data fetching composables
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#24697 docs: add documentation on `getCachedData` option
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: 3.x

#24715 perf(vite): simplify manifest property acccess
  packages/vite/src/manifest.ts
Labels: 3.x

#24396 fix(nuxt): ensure `error` in `useAsyncData` has correct type
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/error.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, chore

#24711 feat(vite): replace browser globals with `undefined` on server
  packages/vite/src/server.ts
Labels: enhancement, 3.x, vite, 🍰 p2-nice-to-have

#24749 refactor(nuxt): remove `process.*` usage in nuxt vue app
  packages/nuxt/index.d.ts
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/head/module.ts
  packages/vite/src/vite.ts
  packages/webpack/src/presets/base.ts
  vitest.config.ts
Labels: 3.x, vite, webpack, chore

#24718 perf(nuxt): don't dedupe fewer than two middleware/plugins
  packages/nuxt/src/core/utils/index.ts
Labels: 3.x

#24127 feat(nuxt): allow plugins to specify dependencies
  docs/2.guide/2.directory-structure/1.plugins.md
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/types.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/test/plugin-metadata.test.ts
  packages/schema/src/types/nuxt.ts
  test/bundle.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/plugins/async-plugin.ts
  test/fixtures/basic/plugins/dependsOnPlugin.ts
  test/nuxt/plugin.test.ts
Labels: enhancement, 3.x

#24001 feat(kit): add new `addServerScanDir` composable
  docs/3.api/5.kit/11.nitro.md
  packages/kit/src/nitro.ts
Labels: enhancement, 3.x, kit, 🍰 p2-nice-to-have

#24178 docs: add panda css to styling guide
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#24241 docs: highlight the possibility of middleware to return nothing
  docs/2.guide/2.directory-structure/1.middleware.md
Labels: documentation, 3.x

#24515 feat(nuxt): transform `setup` within `defineComponent` options
  packages/nuxt/src/app/composables/asyncContext.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
  packages/schema/src/config/build.ts
  test/basic.test.ts
  test/fixtures/basic/pages/async-transform-component.vue
Labels: enhancement, 3.x, workaround available, bug, 🍰 p2-nice-to-have

#23480 docs: setting middleware at build time
  docs/2.guide/2.directory-structure/1.middleware.md
Labels: documentation, 3.x

#24201 docs: remove deprecated `loadNuxt` options
  docs/3.api/5.kit/2.programmatic.md
Labels: documentation, 3.x

#24734 perf(schema): avoid duplicate `get` operations
  packages/schema/src/config/common.ts
  packages/schema/src/config/vite.ts
Labels: 3.x

#24752 ci: notify `nuxt/bridge` when composables change
  .github/workflows/notify-nuxt-bridge.yml
Labels: 3.x

#24771 perf(schema): use parallel promises
  packages/schema/src/config/build.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/vite.ts
Labels: 3.x

#24777 feat(nuxt): allow customising fallback layout
  packages/nuxt/src/app/components/nuxt-layout.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#24781 feat(nuxt): `useRequestHeader` utility
  docs/3.api/2.composables/use-request-header.md
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/imports/presets.ts
Labels: 3.x

#24786 fix(nuxt): allow modules to disable `appManifest` without crashing
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x

#24784 fix(nuxt): revert async transform of `setup` within `defineComponent`
  packages/nuxt/src/app/composables/asyncContext.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
  packages/schema/src/config/build.ts
  test/basic.test.ts
  test/fixtures/basic/pages/async-transform-component.vue
Labels: 3.x, bug, ❗ p4-important

#24790 docs: add documentation for `nuxi module`
  docs/3.api/4.commands/module.md
Labels: 3.x

#24814 chore: pin rollup to v4
  package.json
  packages/nuxt/src/core/nitro.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
Labels: 3.x

#24775 docs: update return for `useFetch` and `useAsyncData` #24407
  docs/1.getting-started/6.data-fetching.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: 3.x

#24584 fix(nuxt): eager load island components map
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/templates.ts
  test/fixtures/basic/components/islands/HmrComponent.vue
  test/fixtures/basic/pages/server-component-hmr.vue
  test/hmr.test.ts
Labels: 3.x, bug, test, server components

#24821 chore(nuxt): add return type for entry
  packages/nuxt/src/app/entry.ts
Labels: 3.x, chore

#24010 feat(nuxt): move loading api behind hooks
  docs/3.api/1.components/5.nuxt-loading-indicator.md
  docs/3.api/2.composables/use-loading-indicator.md
  docs/3.api/6.advanced/1.hooks.md
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
  packages/nuxt/src/app/composables/loading-indicator.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#22649 feat(nuxt): allow client components within `NuxtIsland`
  docs/2.guide/2.directory-structure/1.components.md
  docs/3.api/1.components/8.nuxt-island.md
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-teleport-ssr-client.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/test/islandTransform.test.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic/components/AsyncServerComponent.server.vue
  test/fixtures/basic/components/ServerWithClient.server.vue
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/islands.vue
  test/fixtures/basic/pages/server-components/lazy/end.vue
  test/nuxt/nuxt-island.test.ts
Labels: enhancement, 3.x, server components

#24658 docs: add initial docs for runtime tests
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#24833 fix(nuxt): register override hooks separately
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/load-nuxt.test.ts
Labels: 3.x, bug, ❗ p4-important

#24836 fix(nuxt): add `__VUE_PROD_HYDRATION_MISMATCH_DETAILS__`
  packages/nuxt/test/auto-imports.test.ts
  packages/schema/src/config/vite.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#24835 fix(kit): ensure `mode` from `filePath` for `addComponent`
  packages/kit/src/components.ts
Labels: 3.x

#24457 fix(kit): do not add local `~/modules` directories to `modulesDir`
  packages/kit/src/module/install.ts
Labels: 3.x, bug

#24843 perf(nuxt): avoid duplicate useRuntimeConfig call
  packages/nuxt/src/core/runtime/nitro/paths.ts
Labels: 3.x

#24846 test: add basic benchmark tests
  .github/workflows/ci.yml
  package.json
  packages/kit/test/load-nuxt-config.bench.ts
  packages/kit/test/write-types.bench.ts
  packages/nuxt/test/load-nuxt.bench.ts
  pnpm-lock.yaml
  vitest.config.ts
Labels: 3.x, test

#24848 perf(vite): avoid duplicate `JSON.stringify` operation
  packages/vite/src/manifest.ts
Labels: 3.x

#24876 docs: add `addComponentsDir` example to modules author guide
  docs/2.guide/3.going-further/3.modules.md
Labels: 3.x

#24857 feat(kit,nuxt,vite,webpack): add `toArray` util
  packages/kit/src/build.ts
  packages/kit/src/imports.ts
  packages/kit/src/internal/template.ts
  packages/kit/src/nitro.ts
  packages/kit/src/pages.ts
  packages/kit/src/resolve.ts
  packages/kit/src/utils.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/composables/state.ts
  packages/nuxt/src/app/utils.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/plugins/prefetch.client.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/src/pages/runtime/utils.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/src/utils.ts
  packages/vite/src/utils/external.ts
  packages/vite/src/utils/index.ts
  packages/webpack/src/utils/config.ts
  packages/webpack/src/utils/index.ts
Labels: enhancement, 3.x

#24880 refactor(schema): introduce `future` and `features` namespace
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/1.features.md
  packages/kit/src/template.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
  packages/vite/src/vite.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x, bug, vite, chore, kit

#24896 fix(nuxt): catch error in NuxtErrorBoundary if not server rendered
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
Labels: 3.x

#24899 test: add missing payload checks
  test/basic.test.ts
Labels: 3.x

#24853 perf(nuxt): avoid multiple transformations of headers
  packages/nuxt/src/app/composables/ssr.ts
Labels: 3.x

#24937 docs: corrected json syntax in 7.esm.md
  docs/2.guide/1.concepts/7.esm.md
Labels: 3.x

#24923 docs: specify yarn pnp opt-out for install
  docs/1.getting-started/2.installation.md
Labels: 3.x

#24948 docs: update useless parameters
  docs/2.guide/2.directory-structure/1.pages.md
Labels: 3.x

#24744 perf(kit, schema, nuxt): rework startsWith to direct index
  packages/kit/src/compatibility.ts
  packages/kit/src/ignore.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/config/webpack.ts
Labels: 3.x

#24946 perf(nuxt): use single iteration when normalising routes
  packages/nuxt/src/pages/utils.ts
Labels: 3.x
