Repository nuxt/nuxt, pull requests merged in 2023-10, with the labels that each got.

#23476 fix(nuxt): decrement hydration count when rendering no route
  packages/nuxt/src/pages/runtime/page.ts
Labels: 3.x, bug, kit, 🔨 p3-minor-bug

#23462 fix(nuxt): compute fetch cache key with headers
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, workaround available, bug, 🔨 p3-minor-bug

#23447 perf(nuxt): verbatim module syntax + restrict type discovery
  packages/kit/src/template.ts
Labels: types, 3.x, performance

#23502 fix(nuxt): mock hookable methods on nuxt 2
  packages/kit/src/loader/nuxt.ts
Labels: 2.x, bug, kit, 🔨 p3-minor-bug

#23509 fix(kit): revert accidental change to `addPrerenderRoutes` name
  docs/3.api/4.advanced/2.kit.md
  packages/kit/src/nitro.ts
Labels: 3.x, bug, kit

#23512 fix(nuxt): use `test`/`dev` as manifest buildId when appropriate
  packages/nuxt/src/core/nitro.ts
  vitest.nuxt.config.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23520 test(nuxt): add test suite for app resolution behaviour
  packages/nuxt/src/core/app.ts
  packages/nuxt/test/app.test.ts
Labels: 3.x, chore, test

#23372 docs: add server concept
  docs/1.getting-started/8.server.md
Labels: documentation, 3.x

#23607 feat(nuxt): auto-install optional features on StackBlitz
  packages/nuxt/src/core/features.ts
  packages/nuxt/src/core/nuxt.ts
Labels: enhancement

#23604 fix(nuxt): don't print warnings for unresolved ids
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
Labels: 3.x, bug

#22375 docs: improve `nuxt kit` section
  docs/3.api/4.advanced/2.kit.md
  docs/3.api/4.kit/1.modules.md
  docs/3.api/4.kit/10.templates.md
  docs/3.api/4.kit/11.nitro.md
  docs/3.api/4.kit/12.resolving.md
  docs/3.api/4.kit/13.logging.md
  docs/3.api/4.kit/14.builder.md
  docs/3.api/4.kit/15.examples.md
  docs/3.api/4.kit/2.programmatic.md
  docs/3.api/4.kit/3.compatibility.md
  docs/3.api/4.kit/4.autoimports.md
  docs/3.api/4.kit/5.components.md
  docs/3.api/4.kit/6.context.md
  docs/3.api/4.kit/7.pages.md
  docs/3.api/4.kit/8.layout.md
  docs/3.api/4.kit/9.plugins.md
  docs/3.api/4.kit/_dir.yml
  docs/3.api/5.advanced/1.hooks.md
  docs/3.api/5.advanced/_dir.yml
  docs/3.api/6.commands/_dir.yml
  docs/3.api/6.commands/add.md
  docs/3.api/6.commands/analyze.md
  docs/3.api/6.commands/build-module.md
  docs/3.api/6.commands/build.md
  docs/3.api/6.commands/cleanup.md
  docs/3.api/6.commands/dev.md
  docs/3.api/6.commands/devtools.md
  docs/3.api/6.commands/generate.md
  docs/3.api/6.commands/info.md
  docs/3.api/6.commands/init.md
  docs/3.api/6.commands/prepare.md
  docs/3.api/6.commands/preview.md
  docs/3.api/6.commands/typecheck.md
  docs/3.api/6.commands/upgrade.md
  docs/3.api/7.configuration/_dir.yml
  docs/3.api/7.configuration/nuxt-config.md
Labels: documentation, 3.x

#23508 feat(kit,nuxt,vite,webpack): support `-nightly` extension
  .github/workflows/release-pr.yml
  docs/2.guide/3.going-further/11.edge-channel.md
  packages/kit/src/loader/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/test/import-protection.test.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
  packages/webpack/src/configs/server.ts
  scripts/bump-edge.ts
Labels: 3.x, chore

#23466 fix(nuxt): tree shake all occurrences of `<DevOnly>`
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/utils/plugins.ts
  packages/nuxt/test/devonly.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#23605 docs: add section about computed url for data fetching
  docs/1.getting-started/6.data-fetching.md
Labels: documentation

#23552 fix(nuxt): give priority to later middleware when deduping
  packages/nuxt/src/core/app.ts
  packages/nuxt/test/app.test.ts
  test/basic.test.ts
  test/fixtures/basic/extends/bar/middleware/override.ts
  test/fixtures/basic/extends/node_modules/foo/middleware/override.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#23667 fix(nuxt): provide global scope for nuxt plugin context
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23693 fix(nuxt): resolve type error in options of `useFetch`
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#23692 fix(webpack): remove `lodash-es` + simplify postcss resolution
  packages/webpack/package.json
  packages/webpack/src/plugins/vue/client.ts
  packages/webpack/src/utils/config.ts
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
Labels: 3.x, webpack, performance

#23600 feat(nuxt): support `deep: false` for data composables
  docs/3.api/1.composables/use-async-data.md
  docs/3.api/1.composables/use-fetch.md
  docs/3.api/1.composables/use-state.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
Labels: enhancement, 3.x

#23697 fix(nuxt): write cookie values before navigating away
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23703 fix: remove md4 patch now that `webpack` has it in core
  packages/config/src/options.js
  packages/config/test/config/index.test.js
  packages/config/test/options.test.js
Labels: 2.x, bug, chore

#23351 fix(nuxt): refetch both undefined/null values in `useAsyncData`
  packages/nuxt/src/app/composables/asyncData.ts
  test/basic.test.ts
  test/fixtures/basic/pages/useAsyncData/nuxt-data.vue
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23706 ci: remove node version from matrix
  .github/workflows/changelogensets.yml
  .github/workflows/test.yml
  .github/workflows/windows.yml
Labels: 2.x, chore

#20747 feat(nuxt): custom cache support for data fetching composables
  docs/3.api/1.composables/use-async-data.md
  docs/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#23701 ci: use node 18 for ci jobs
  .github/workflows/test.yml
  .github/workflows/windows.yml
  packages/server/test/middleware/nuxt.test.js
  test/dev/basic.dev.test.js
  test/dev/basic.dynamic.test.js
  test/dev/basic.generate.test.js
  test/dev/basic.plugins.test.js
  test/dev/basic.relative.test.js
  test/dev/basic.ssr.csp.test.js
  test/dev/basic.ssr.test.js
  test/dev/children.test.js
  test/dev/cli.test.js
  test/dev/custom-dirs.test.js
  test/dev/dist-options.test.js
  test/dev/encoding.test.js
  test/dev/error.test.js
  test/dev/express.test.js
  test/dev/fallback.test.js
  test/dev/filenames-query-part.test.js
  test/dev/full-static-with-preview.test.js
  test/dev/full-static.test.js
  test/dev/modern.client.test.js
  test/dev/modern.server.test.js
  test/dev/modern.spa.test.js
  test/dev/module.test.js
  test/dev/nuxt.test.js
  test/dev/postcss-function.test.js
  test/dev/runtime-config.test.js
  test/dev/server.listen.test.js
  test/dev/spa.test.js
  test/dev/ssr.test.js
  test/dev/trailing-slash-payload.test.js
  test/dev/trailing-slash.test.js
  test/dev/with-config.test.js
  test/e2e/basic.browser.test.js
  test/e2e/basic.navigation.test.js
  test/e2e/basic.vue-config.test.js
  test/e2e/children.patch.browser.test.js
  test/e2e/error.test.js
  test/e2e/fetch.browser.test.js
  test/e2e/page-transitions.browser.test.js
  test/e2e/spa-base.browser.test.js
  test/e2e/split-layouts-error.test.js
  test/fixtures/basic/pages/fetch.vue
Labels: 2.x, chore

#20190 feat(nuxt): scan and register layouts in nested folders
  docs/2.guide/2.directory-structure/1.layouts.md
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/test/app.test.ts
  packages/nuxt/test/scan-components.test.ts
Labels: enhancement, 3.x

#23707 fix(nuxt): don't mark redirected routes as prerendered
  packages/nuxt/src/app/composables/payload.ts
  test/bundle.test.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23715 fix(nuxt): respect custom export in component transform
  packages/nuxt/src/components/transform.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23741 docs: add info about `<NuxtImg>` and `<NuxtPicture>`
  docs/3.api/2.components/10.nuxt-picture.md
  docs/3.api/2.components/11.teleports.md
  docs/3.api/2.components/9.nuxt-img.md
Labels: documentation

#23744 docs: remove redundant trailing slashes from links
  docs/1.getting-started/11.testing.md
  docs/1.getting-started/2.installation.md
  docs/1.getting-started/3.configuration.md
  docs/1.getting-started/4.assets.md
  docs/1.getting-started/4.styling.md
  docs/1.getting-started/5.routing.md
  docs/1.getting-started/5.seo-meta.md
  docs/1.getting-started/5.transitions.md
  docs/1.getting-started/8.server.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/2.guide/1.concepts/2.vuejs-development.md
  docs/2.guide/1.concepts/3.rendering.md
  docs/2.guide/1.concepts/4.server-engine.md
  docs/2.guide/1.concepts/7.esm.md
  docs/2.guide/2.directory-structure/1.node_modules.md
  docs/2.guide/2.directory-structure/3.app.md
  docs/2.guide/3.going-further/8.custom-routing.md
  docs/3.api/2.composables/use-head.md
  docs/3.api/5.kit/14.builder.md
  docs/5.community/2.getting-help.md
  docs/5.community/3.reporting-bugs.md
  docs/5.community/4.contribution.md
  docs/5.community/5.framework-contribution.md
  docs/5.community/6.roadmap.md
  docs/7.migration/10.bundling.md
  docs/7.migration/2.configuration.md
Labels: documentation, 3.x

#23724 feat(nuxt): allow configuring default `<NuxtLink>` options
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/build.config.ts
  packages/schema/src/config/experimental.ts
  test/mocks/nuxt-config.ts
  vitest.config.ts
Labels: enhancement, 3.x, 🔨 p3-minor-bug

#23754 chore: remove huntr + encourage GitHub vulnerability reporting
  SECURITY.md
Labels: documentation, chore

#23755 chore: refresh lockfile
  pnpm-lock.yaml
Labels: 3.x, chore

#23781 fix(nuxt): don't use `prerenderedAt` to override app manifest
  packages/nuxt/src/app/composables/payload.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23799 fix(nuxt): ensure we add prerender hints to correct event
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/schema/src/config/common.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23828 ci: add doc deploy webhook trigger
  .github/workflows/docs-deploy.yml
Labels: chore

#23795 fix(schema): accept single string for `extends`
  packages/schema/src/config/common.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#23751 fix(nuxt): resolve internal `target: blank` links with base
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23802 fix(nuxt): use `.json` extension for server components
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: 3.x, bug, performance

#23841 fix(nuxt): handle relative baseURL in nitro runtime config
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
  packages/nuxt/src/core/nitro.ts
  test/bundle.test.ts
Labels: 3.x, bug, nitro, 🔨 p3-minor-bug

#23857 fix(nuxt): improve watcher logs slightly
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/schema.ts
Labels: 3.x, bug, chore

#23858 fix(nuxt): resolve `@unhead/vue` in template code
  packages/nuxt/src/head/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23860 fix(kit): resolve module tsconfig paths relative to dirs
  packages/kit/src/module/install.ts
  packages/kit/src/template.ts
Labels: 3.x, bug, kit, 🔨 p3-minor-bug

#23856 fix(nuxt,schema,vite,webpack): analyze w/o overriding config
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/webpack.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/analyze.ts
  packages/webpack/src/configs/client.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#23884 fix(nuxt): don't use local fetch with an external `baseURL`
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23889 fix(nuxt): only skip refetching errors when hydrating
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug, ❗ p4-important

#23861 fix(vite): remove `postcss-url` and duplicate `postcss-import`
  packages/schema/package.json
  packages/schema/src/config/postcss.ts
  packages/vite/package.json
  packages/webpack/package.json
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#23935 docs: skip View Transitions API route middleware on server
  docs/1.getting-started/5.transitions.md
Labels: documentation, 3.x

#23549 fix(nuxt): unset `useCookie` value when it expires
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23995 fix(vite): use `h3` cors handler for vite routes only
  packages/vite/src/client.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#23980 fix(schema): correctly set default cssnano config
  packages/schema/src/config/postcss.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, schema

#24032 perf(nuxt): set `pages` on nuxt app and deduplicate calls
  packages/nuxt/src/pages/module.ts
  packages/schema/src/types/nuxt.ts
Labels: enhancement, 3.x, bug, schema

#24031 fix(nuxt): use payload url for isPrerendered, not current route
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, schema

#23975 fix(vite): don't warm up css deps and normalise urls correctly
  packages/vite/src/utils/warmup.ts
  packages/vite/src/vite.ts
Labels: 3.x, vite, 🔨 p3-minor-bug, performance

#24033 perf(nuxt): remove pure annotations plugin
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/pure-annotations.ts
  packages/vite/src/server.ts
Labels: enhancement, 3.x, bug, schema

#23951 perf(nuxt): use granular imports for auto-importing composables
  .eslintrc
  docs/3.api/5.kit/10.templates.md
  docs/3.api/5.kit/9.plugins.md
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/components/route-provider.ts
  packages/nuxt/src/app/composables/chunk.ts
  packages/nuxt/src/app/composables/hydrate.ts
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/composables/url.ts
  packages/nuxt/src/app/entry.async.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/middleware/manifest-route-rule.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/app/plugins/debug.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/app/plugins/preload.server.ts
  packages/nuxt/src/app/plugins/restore-state.client.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  packages/nuxt/src/app/plugins/view-transitions.client.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: enhancement, 3.x, vite

#24000 fix(kit): fix `addServerImportsDir` implementation
  docs/3.api/5.kit/11.nitro.md
  packages/kit/src/nitro.ts
  test/fixtures/basic/modules/auto-registered/index.ts
Labels: 3.x, bug, kit, 🔨 p3-minor-bug

#23902 fix(nuxt): preserve hyphens in component/layout kebab names
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/test/naming.test.ts
  packages/nuxt/test/scan-components.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24052 fix(nuxt): do not register loading indicator hooks on server
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: 3.x, bug, ❗ p4-important, performance

#24036 fix(nuxt): reload nitro when spa loading template updates
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug
