Repository nuxt/nuxt, pull requests merged in 2023-05, with the labels that each got.

#20607 fix(nuxt): remove internal `<FragmentWrapper>`
  packages/nuxt/src/app/components/utils.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#20603 docs: fix fetch composable examples
  docs/3.api/1.composables/use-fetch.md
  examples/other/use-custom-fetch-composable/composables/useCustomFetch.ts
Labels: documentation, 3.x

#20606 refactor(schema): move `runtimeCompiler` option out of experimental
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/experimental.ts
  test/fixtures/runtime-compiler/nuxt.config.ts
Labels: 3.x, 🍰 p2-nice-to-have, schema

#20585 fix(nuxt): ensure `useError` is called with nuxt app context
  docs/1.getting-started/6.data-fetching.md
  docs/1.getting-started/8.error-handling.md
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/plugins/cookie.ts
Labels: 3.x, bug, ❗ p4-important

#20525 feat(kit): support passing getter to `addVitePlugin` and `addWebpackPlugin`
  packages/kit/src/build.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x, kit, 🍰 p2-nice-to-have, performance

#20644 ci: run tests in node 16
  .github/workflows/test.yml
  .github/workflows/windows.yml
Labels: 2.x, chore

#20608 feat(nuxt): add `nuxtApp.runWithContext`
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/src/pages/runtime/validate.ts
  test/bundle.test.ts
  test/fixtures/basic/types.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20689 chore: do not install example dependencies
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 3.x, chore

#20711 chore: type-check `.mjs` files
  package.json
  packages/vite/src/runtime/client.manifest.mjs
  packages/vite/src/runtime/vite-node-shared.mjs
  packages/vite/src/runtime/vite-node.mjs
  pnpm-lock.yaml
  scripts/crawl.mjs
Labels: 3.x, chore

#20605 fix(webpack): warn when using deprecated `build.extend` hook
  packages/webpack/src/utils/config.ts
Labels: 3.x, webpack, 🍰 p2-nice-to-have

#20639 fix(nuxt): allow resolving client nuxt app to singleton
  packages/nuxt/src/app/entry.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20745 fix(nuxt): prevent treeshaking hooks with composable names
  packages/nuxt/src/core/plugins/tree-shake.ts
  test/fixtures/basic/plugins/style.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#20367 feat(nuxt): add experimental `typedPages` option
  .eslintrc
  packages/nuxt/package.json
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/src/pages/runtime/router.options.ts
  packages/nuxt/src/pages/runtime/utils.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/[...slug].vue
  test/fixtures/basic/pages/nested/[foo]/[bar].vue
  test/fixtures/basic/pages/nested/[foo]/index.vue
  test/fixtures/basic/pages/nested/[foo]/user-[group].vue
  test/fixtures/basic/pages/nuxt-link/trailing-slash.vue
  test/fixtures/basic/pages/random/[id].vue
  test/fixtures/basic/types.ts
  tsconfig.json
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20637 feat(nuxt): add apps to nuxt build-time instance
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/types/nuxt.ts
Labels: 3.x

#20755 fix(vite): expand `fs.allow` dirs to include app files
  packages/vite/src/vite.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#20743 fix(nuxt): deduplicate global components before registration
  packages/nuxt/src/components/templates.ts
  test/fixtures/basic/components/global/ClientGlobal.client.vue
Labels: 3.x, bug, components, 🔨 p3-minor-bug

#20760 feat(nuxi): allow passing overrides to other nuxi commands
  packages/nuxi/src/commands/analyze.ts
  packages/nuxi/src/commands/build-module.ts
  packages/nuxi/src/commands/build.ts
  packages/nuxi/src/commands/generate.ts
  packages/nuxi/src/commands/prepare.ts
  packages/nuxi/src/commands/preview.ts
  packages/nuxi/src/commands/test.ts
  packages/nuxi/src/commands/typecheck.ts
Labels: enhancement, 3.x, cli

#20770 feat(schema): enable rich json payloads by default
  packages/schema/src/config/experimental.ts
  test/bundle.test.ts
Labels: enhancement, 3.x, schema

#20478 feat(deps): update vue to v3.3
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/__snapshots__/treeshake-client.test.ts.snap
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/basic/components/SugarCounter.vue
Labels: 3.x, chore

#20775 feat(nuxt): use `runWithContext` within `callWithNuxt`
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
  test/bundle.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20777 fix(nuxt): enable suspensible behaviour for nested pages
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/pages/suspense.vue
  test/fixtures/basic/pages/suspense/async-[parent].vue
  test/fixtures/basic/pages/suspense/async-[parent]/async-[child].vue
  test/fixtures/basic/pages/suspense/async-[parent]/sync-[child].vue
  test/fixtures/basic/pages/suspense/sync-[parent].vue
  test/fixtures/basic/pages/suspense/sync-[parent]/async-[child].vue
  test/fixtures/basic/pages/suspense/sync-[parent]/sync-[child].vue
Labels: 3.x, bug, ❗ p4-important

#20501 fix(nuxi): hard-reload nuxt when `.env` changes
  packages/nuxi/src/commands/dev.ts
Labels: 3.x, bug, cli, 🔨 p3-minor-bug

#20599 fix(nuxt): always inline styles for server/island components
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/server.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20828 fix(nuxt): allow serialising undefined refs
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  test/basic.test.ts
  test/fixtures/basic/pages/json-payload.vue
Labels: 3.x, bug, ❗ p4-important

#20765 feat(nuxt): add `useRequestURL` helper
  docs/3.api/1.composables/use-request-url.md
  docs/5.community/5.framework-contribution.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/url.ts
  packages/nuxt/src/imports/presets.ts
  test/basic.test.ts
  test/fixtures/basic/pages/url.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20835 fix(nuxt): transform client fallbacks directly on SFCs
  packages/nuxt/src/components/client-fallback-auto-id.ts
  test/basic.test.ts
Labels: 3.x, bug

#20817 feat(nuxt): allow fallback production content in `<DevOnly>`
  docs/2.guide/2.directory-structure/1.components.md
  packages/nuxt/src/app/components/dev-only.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  test/basic.test.ts
  test/fixtures/basic/pages/index.vue
Labels: enhancement, 3.x

#20587 feat(kit): `addBuildPlugin` for builder-agnostic implementation
  packages/kit/src/build.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x, kit

#20829 fix(vite): dedupe/optimize more vue core deps
  packages/vite/src/client.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug, vite

#20336 feat(nuxt): allow keeping fallback for `NuxtClientFallback`
  docs/3.api/2.components/1.nuxt-client-fallback.md
  packages/nuxt/src/app/components/client-fallback.client.ts
  packages/nuxt/src/app/components/client-fallback.server.ts
  test/basic.test.ts
  test/fixtures/basic/pages/client-fallback.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20779 fix(nuxt): ensure all dir parts are present in component name
  packages/nuxt/src/components/scan.ts
  packages/nuxt/test/fixture/components/same-name/same/Same.vue
  packages/nuxt/test/scan-components.test.ts
Labels: 3.x, bug

#20806 fix(nuxt): allow `pages:extend` to enable pages module
  docs/2.guide/3.going-further/3.modules.md
  packages/nuxt/src/pages/module.ts
Labels: enhancement, 3.x

#20738 fix(nuxt): stop loading indicator on vue errors
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20559 feat(nuxt): support separate server tsconfig
  packages/nuxt/src/core/nitro.ts
  test/fixtures/basic/server/api/useAsyncData/count.ts
  test/fixtures/basic/server/tsconfig.json
Labels: enhancement, 3.x, dx, nitro, 🍰 p2-nice-to-have

#20749 fix(nuxt): add types for webpack/vite environments
  packages/nuxt/src/core/nuxt.ts
  packages/schema/build.config.ts
  packages/schema/builder-env.d.ts
  packages/schema/package.json
  packages/schema/src/builder-env.ts
  packages/schema/src/config/typescript.ts
  packages/schema/src/index.ts
  packages/schema/src/types/builder-env/index.ts
  packages/schema/src/types/builder-env/vite.ts
  packages/schema/src/types/builder-env/webpack.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#20284 feat(nuxt): full scoped slots support for server components
  docs/2.guide/2.directory-structure/1.components.md
  packages/nuxt/package.json
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/components/AsyncServerComponent.server.vue
  test/fixtures/basic/components/islands/LongAsyncComponent.vue
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/islands.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20460 feat(nuxt): support parallel plugins
  packages/nuxt/src/app/nuxt.ts
  test/bundle.test.ts
Labels: enhancement, 3.x

#20859 fix(nuxt): pass from + savedPosition to first `scrollBehavior`
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#20894 fix(nuxt): allow island renders without `/` route
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20797 fix(nuxt): infer `useFetch` method when generic is passed
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic/server/api/hey/index.post.ts
  test/fixtures/basic/types.ts
Labels: 3.x, bug

#20910 fix(nuxt): prioritise vue app context when available
  packages/nuxt/src/app/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/pages/instance/error.vue
  test/fixtures/basic/pages/instance/next-request.vue
  test/fixtures/basic/plugins/context-error.ts
Labels: 3.x, bug, ❗ p4-important

#20916 fix(nuxt): don't `refresh` when hydrating when data is present
  packages/nuxt/src/app/composables/asyncData.ts
  test/fixtures/basic/pages/useAsyncData/override.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#20836 perf(nuxt): use granular watcher to avoid crawling ignored dirs
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/schema.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance, 🧷 edge release

#20932 fix(nuxt): resolve layer assets in relation to layer directory
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  test/fixtures/basic/extends/bar/components/ExtendsOverride.vue
  test/fixtures/basic/extends/bar/public/nuxt.svg
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#20939 fix(nuxt): don't match partial component names with prefix
  packages/nuxt/src/components/scan.ts
  packages/nuxt/test/scan-components.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20896 fix(kit): resolve relative module paths when installing
  packages/kit/src/module/install.ts
  test/fixtures/basic/modules/test/index.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, kit, 🔨 p3-minor-bug

#20974 fix(nuxt): exclude plugin declaration from non-existent files
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#20924 fix(nuxt): skip middleware for islands components
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/bundle.test.ts
Labels: bug

#20975 fix(nuxt): use `resolvePath` to handle edge cases for modules
  packages/kit/src/module/install.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20249 docs: add advanced usage example of `useState`
  docs/1.getting-started/7.state-management.md
Labels: documentation, 3.x

#20995 fix(nuxt): scan component dirs case-sensitively
  packages/nuxt/src/components/scan.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20669 fix(utils): respect patterns within paths when sorting routes
  packages/utils/src/route.js
  packages/utils/test/__snapshots__/route.test.js.snap
  packages/utils/test/route.test.js
  test/dev/dynamic-routes.test.js
Labels: 2.x, bug

#20992 fix(nuxt): use simple incrementing id on client
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21011 perf(nuxt): use `.test` and hoist regexps where possible
  packages/nuxi/src/commands/dev.ts
  packages/nuxt/src/components/client-fallback-auto-id.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/transform.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/nuxt/src/imports/transform.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/page-meta.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/webpack/src/plugins/vue/server.ts
Labels: 3.x, performance

#21008 fix(nuxt): await nuxt ready state before `refreshNuxtData`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20719 fix(vue-app): skip page render early on error or navigation
  packages/vue-app/template/client.js
  packages/vue-app/template/utils.js
  test/e2e/basic.navigation.test.js
  test/fixtures/basic/middleware/slow.js
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/navigation.vue
  test/fixtures/basic/pages/navigation/asyncData-error.vue
  test/fixtures/basic/pages/navigation/asyncData-throw.vue
  test/fixtures/basic/pages/navigation/middleware-asyncData-error.vue
  test/fixtures/basic/pages/navigation/middleware-asyncData-throw.vue
Labels: 2.x, bug, 🔨 p3-minor-bug

#21047 fix(nuxt): show error page after fatal `abortNavigation`
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/fixtures/basic/pages/middleware-abort.vue
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#21066 fix(nuxt): normalize windows paths in granular watcher
  packages/nuxt/src/core/builder.ts
Labels: 3.x, bug, windows, ❗ p4-important, performance

#21031 docs: rewrite data fetching section
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#21072 fix(nuxt): omit `Set-Cookie` header if value is null
  packages/nuxt/src/app/composables/cookie.ts
  test/basic.test.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#21082 fix(nuxt): resolve modules relative to modulesDir
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/head/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21224 fix(vite): narrow vite-node inline pattern
  packages/vite/src/vite-node.ts
Labels: bug, vite, 🔨 p3-minor-bug, performance

#21257 fix(nuxt): handle serialising empty bigint
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/json-payload.vue
Labels: 3.x, bug, 🔨 p3-minor-bug
