Repository nuxt/nuxt, pull requests merged in 2023-04, with the labels that each got.

#19902 fix(nuxt): end route param tokens manually
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#20050 feat(nuxt): warn in dev when `useRoute` is used in middleware
  packages/nuxt/src/app/composables/router.ts
Labels: enhancement, 3.x, dx, pages, 🍰 p2-nice-to-have

#20024 fix(nuxt): disable `x-nuxt-no-ssr` header by default
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/no-ssr.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/experimental.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, nitro, 🍰 p2-nice-to-have

#20023 fix(kit): support calling Nuxt 2 modules with module container
  packages/kit/src/module/install.ts
Labels: 3.x, bug, kit, schema

#19823 feat(nuxt): support disabling `watch` with `useFetch`
  docs/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#19986 feat(nuxt): support `~`/`~~`/`@`/`@@` aliases within layers
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic/extends/node_modules/foo/alias/test.ts
  test/fixtures/basic/extends/node_modules/foo/pages/foo.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20083 test: use kb size snapshot
  test/bundle.test.ts
Labels: 3.x, chore, test

#20079 feat(nuxt): respect custom `dir.pages` in page placeholder
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/runtime/page-placeholder.ts
Labels: enhancement, 3.x, dx, 🍰 p2-nice-to-have

#20084 docs: re-enable docs linting and update docs
  .markdownlint.yml
  .markdownlintignore
  docs/1.getting-started/10.deployment.md
  docs/1.getting-started/2.installation.md
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/2.guide/2.directory-structure/1.modules.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/2.guide/2.directory-structure/3.app-config.md
  docs/2.guide/3.going-further/3.modules.md
  docs/3.api/1.composables/use-head-safe.md
  docs/3.api/4.advanced/1.hooks.md
  docs/3.api/5.commands/devtools.md
  docs/5.community/5.framework-contribution.md
  docs/7.migration/2.configuration.md
  package.json
Labels: documentation, 3.x, chore

#20081 fix(nuxt): add types for globally injected `$config` object
  packages/nuxt/src/core/templates.ts
  test/fixtures/basic/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#20088 ci: use autofix to update bundle size
  .github/workflows/autofix-docs.yml
  .github/workflows/autofix.yml
Labels: 3.x, chore

#20052 fix(nuxt): throw error on protocol relative path in `useFetch`
  packages/nuxt/src/app/composables/fetch.ts
Labels: enhancement, 3.x, dx, 🍰 p2-nice-to-have

#20025 fix(nuxt): add `@types/node` as a peerDependency
  docs/2.guide/1.concepts/8.typescript.md
  docs/3.api/5.commands/typecheck.md
  packages/nuxt/package.json
  pnpm-lock.yaml
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#20105 fix(nuxt): test all custom app config keys for `any`
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#20093 fix(nuxt): add key to `.client` component placeholders
  packages/nuxt/src/app/components/client-only.mjs
  test/basic.test.ts
  test/fixtures/basic/components/client/SetupScript.client.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#19415 fix(nuxt): add `undefined` type for `useCookie` return value
  packages/nuxt/src/app/composables/cookie.ts
Labels: types, 3.x

#20112 refactor(schema): clean up `experimental` options
  packages/schema/src/config/experimental.ts
Labels: 3.x, chore, schema

#19205 feat(nuxt): experimental option for rich json payloads
  docs/3.api/1.composables/use-nuxt-app.md
  packages/nuxt/package.json
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/json-payload.vue
  test/fixtures/basic/plugins/custom-type-assertion.client.ts
  test/fixtures/basic/plugins/custom-type-registration.ts
  test/utils.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20111 refactor(nuxt): remove `#head` alias
  packages/nuxt/package.json
  packages/nuxt/src/head/module.ts
  test/fixtures/basic/plugins/my-plugin.ts
Labels: 3.x, refactor

#20082 fix(nuxt): deprecate old (pre-rc) runtimeConfig
  packages/nuxt/src/app/nuxt.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/plugins/async-plugin.ts
Labels: 3.x, bug, performance

#18882 fix(nuxi): preview nitro build with custom dir config
  packages/nuxi/src/commands/preview.ts
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, cli

#20092 feat(nuxt): add experimental View Transitions API support
  docs/1.getting-started/5.transitions.md
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/view-transitions.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20172 chore: remove `JITI_ESM_RESOLVE`
  package.json
Labels: chore

#20182 feat(nuxt): support async transform of object properties
  docs/1.getting-started/6.data-fetching.md
  docs/2.guide/1.concepts/1.auto-imports.md
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/build.ts
  pnpm-lock.yaml
  test/fixtures/basic/pages/chunk-error.vue
  test/fixtures/basic/pages/legacy/async-data.vue
  test/fixtures/basic/pages/navigate-to-redirect.vue
Labels: enhancement, 3.x

#20194 chore: upgrade to consola v3
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxi/src/cli.ts
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: 3.x, chore

#20003 feat(nuxt): support object-syntax plugins
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/3.api/1.composables/use-nuxt-app.md
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/app/plugins/debug.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/app/plugins/preload.server.ts
  packages/nuxt/src/app/plugins/restore-state.client.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  packages/nuxt/src/head/runtime/plugins/vueuse-head-polyfill.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/pages/runtime/plugins/prefetch.client.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/schema/src/config/build.ts
  test/bundle.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/plugins/custom-type-registration.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20198 fix(nuxi, vite): suppress sourcemap + native fetch warnings
  packages/nuxi/src/cli.ts
  packages/vite/src/utils/logger.ts
Labels: 3.x, bug, vite

#19805 feat(nuxt): add `experimentalNoScripts` route rule
  docs/2.guide/1.concepts/3.rendering.md
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/types.d.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/no-scripts.vue
Labels: 3.x

#20170 v3.4.0
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#20216 fix(nuxt): set config on `ssrContext` in spa renderer
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/plugins/custom-type-assertion.client.ts
Labels: 3.x, bug, ❗ p4-important

#20218 fix(nuxt): mark entire payload as reactive
  packages/nuxt/src/app/nuxt.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/index.vue
Labels: 3.x, bug, ❗ p4-important

#20237 fix(nuxt): add missing imports to `<NuxtClientFallback>`
  packages/nuxt/src/app/components/client-fallback.client.ts
  packages/nuxt/src/app/components/client-fallback.server.ts
  packages/nuxt/src/app/components/dev-only.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20244 fix(nuxt): improve handling of redirects within middleware
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/middleware/redirect.global.ts
  test/fixtures/basic/pages/[...slug].vue
  test/fixtures/basic/server/plugins/headers.ts
  test/fixtures/basic/types.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#20247 fix(nuxt): do not redirect when `vue-router` normalises url
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/fixtures/basic/middleware/redirect.global.ts
Labels: 3.x, bug, pages, ❗ p4-important

#20246 v3.4.1
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/vite/package.json
  packages/webpack/package.json
Labels: 3.x, chore

#20259 perf(nuxt): share lazy component definitions
  packages/nuxt/src/components/templates.ts
  test/bundle.test.ts
Labels: enhancement, 3.x, performance

#20276 fix(vite): set different cache dirs for client/server
  packages/vite/src/client.ts
  packages/vite/src/plugins/cache-dir.ts
  packages/vite/src/server.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#20280 fix(nuxt): generate hi-res sourcemaps
  packages/nuxt/src/components/client-fallback-auto-id.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/imports/transform.ts
  packages/nuxt/src/pages/page-meta.ts
  packages/vite/src/plugins/chunk-error.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/paths.ts
  packages/vite/src/plugins/pure-annotations.ts
  packages/webpack/src/plugins/dynamic-base.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#20288 fix(nuxt): return type directly if not picking asyncData
  packages/nuxt/src/app/composables/asyncData.ts
  test/fixtures/basic/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#20289 fix(nuxt): provide more helpful error when instance unavailable
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, dx

#20286 fix(nuxt): mark `useRequestHeaders` keys as optional
  packages/nuxt/src/app/composables/ssr.ts
  test/fixtures/basic/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#20282 docs: add brief information on debugging a nuxt app
  docs/2.guide/3.going-further/9.debugging.md
Labels: documentation, 3.x

#20375 fix(nuxt): swap preloads for json/js payloads
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20356 perf: remove unused deps and add implicit deps
  package.json
  packages/kit/package.json
  packages/nuxi/package.json
  packages/nuxt/build.config.ts
  packages/nuxt/package.json
  packages/schema/package.json
  packages/test-utils/package.json
  packages/test-utils/src/setup/jest.ts
  packages/vite/package.json
  packages/vite/src/utils/logger.ts
  packages/webpack/build.config.ts
  packages/webpack/package.json
  pnpm-lock.yaml
  test/fixtures/basic/extends/bar/app/router.options.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/package.json
  test/fixtures/basic/types.ts
Labels: 3.x, bug, performance

#20373 fix(nuxt): log error with debug information for invalid page
  packages/nuxt/src/pages/page-meta.ts
  test/fixtures/basic/pages/empty.ts
Labels: 3.x, bug

#20360 fix(test-utils): import jest.fn from `@jest/globals`
  packages/test-utils/build.config.ts
  packages/test-utils/package.json
  packages/test-utils/src/setup/jest.ts
  pnpm-lock.yaml
Labels: 3.x, bug, test-utils

#20396 fix(core,kit): ensure module transpilation paths are dirs
  packages/kit/src/module/install.ts
  packages/nuxt/src/core/modules.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20344 refactor(nuxt): rework and use `isJS` and `isVue` utilities consistently
  packages/nuxt/src/components/client-fallback-auto-id.ts
  packages/nuxt/src/components/helpers.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/core/utils/index.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/src/core/utils/plugins.ts
  packages/nuxt/src/imports/transform.ts
  packages/vite/src/plugins/pure-annotations.ts
  test/fixtures/basic/pages/index.vue
Labels: 3.x, bug, vite

#19640 fix(schema): rely on installed telemetry types
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/adhoc.ts
  pnpm-lock.yaml
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, 🍰 p2-nice-to-have, schema

#20179 perf: allow using `@parcel/watcher` for dev watcher
  packages/nuxt/package.json
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/schema.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
Labels: 3.x, performance

#20401 fix(nuxi): load kit from `rootDir` when preparing project
  packages/nuxi/src/commands/prepare.ts
Labels: 3.x, bug, cli

#20278 fix(nuxt): clone app config on server
  packages/nuxt/package.json
  packages/nuxt/src/app/config.ts
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x, bug, vite

#20414 refactor(vite): use native `isFileServingAllowed` util
  packages/vite/src/vite-node.ts
Labels: 3.x, vite, refactor

#20424 fix(nuxt): don't call `timeEnd` unless we're debugging
  packages/nuxt/src/core/builder.ts
Labels: 3.x, bug, 🍰 p2-nice-to-have

#19911 fix(nuxt): use key to force server component re-rendering
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
  test/basic.test.ts
  test/fixtures/basic/pages/islands.vue
Labels: 3.x, bug

#20498 fix(nuxi,schema): support `devServer.https: true`
  packages/nuxi/src/commands/dev.ts
  packages/schema/src/config/dev.ts
Labels: 3.x, bug, cli, 🍰 p2-nice-to-have

#20506 chore: bump jest dependencies
  package.json
  packages/builder/test/context/__snapshots__/template.test.js.snap
  packages/config/test/__snapshots__/options.test.js.snap
  packages/config/test/config/__snapshots__/index.test.js.snap
  packages/config/test/config/index.test.js
  packages/config/test/options.test.js
  packages/utils/test/__snapshots__/route.test.js.snap
  renovate.json
  yarn.lock
Labels: 2.x, chore, test

#20510 fix(nuxt): use `callAsync` for executing hooks with context
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, bug, ❗ p4-important

#20115 docs: add custom fetch composable example
  docs/3.api/1.composables/use-fetch.md
  docs/4.examples/8.other/use-custom-fetch-composable.md
  examples/other/use-custom-fetch-composable/app.vue
  examples/other/use-custom-fetch-composable/composables/useCustomFetch.ts
  examples/other/use-custom-fetch-composable/nuxt.config.ts
  examples/other/use-custom-fetch-composable/package.json
  examples/other/use-custom-fetch-composable/tsconfig.json
  pnpm-lock.yaml
Labels: documentation, 3.x

#20511 fix(nuxt): call `app:error` in SSR before rendering error page
  docs/1.getting-started/8.error-handling.md
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/error.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#20547 fix(nuxt): transform `#components` imports into direct component imports
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/components/transform.ts
  test/bundle.test.ts
Labels: 3.x, bug, ❗ p4-important, performance

#20496 fix(nuxt): return `RenderResponse` for redirects
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/navigate-to-external.vue
  test/fixtures/basic/pages/navigate-to-redirect.vue
  test/fixtures/basic/types.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#20508 feat(nuxt): add scoped helper for clearing error within boundary
  docs/1.getting-started/8.error-handling.md
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#20279 feat(nuxt): auto import 'watchPostEffect' and 'watchSyncEffect' from vue
  packages/nuxt/src/imports/presets.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20411 feat(vite): introduce `vite:configResolved` hook
  docs/3.api/4.advanced/1.hooks.md
  packages/schema/src/types/hooks.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20412 feat(webpack): introduce `webpack:configResolved` hook
  docs/3.api/4.advanced/1.hooks.md
  packages/schema/src/types/hooks.ts
  packages/webpack/src/webpack.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20340 fix(nuxt): remove backwards-compatible runtimeConfig proxy
  packages/nuxt/src/app/nuxt.ts
  test/bundle.test.ts
Labels: bug, ❗ p4-important, performance

#20403 feat(kit): allow vite and webpack plugins to be prepended
  packages/kit/src/build.ts
Labels: enhancement, kit, 🍰 p2-nice-to-have

#20329 feat(nuxt): add layer meta and env overrides to config types
  packages/nuxt/config.d.ts
  packages/nuxt/package.json
  pnpm-lock.yaml
Labels: enhancement, 3.x, dx

#20443 feat(test-utils): add option to configure test server port
  docs/1.getting-started/11.testing.md
  packages/test-utils/src/server.ts
  packages/test-utils/src/types.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have, test-utils

#20590 fix(nuxt): skip payload extraction for island context
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: ❗ p4-important
