Repository nuxt/nuxt, pull requests merged in 2023-06, with the labels that each got.

#21316 chore: avoid inlining deps in vitest
  packages/nuxt/test/treeshake-client.test.ts
  vitest.config.ts
Labels: 3.x, chore

#21372 fix(nuxt): support usage of `std-env` in runtime code
  packages/nuxt/src/core/nuxt.ts
  packages/vite/src/client.ts
Labels: 3.x, bug

#21356 ci: pin actions by hash and use corepack
  .github/workflows/test.yml
  .github/workflows/windows.yml
  package.json
Labels: 2.x

#21326 chore: rewrite crawler to remove old dependencies
  package.json
  pnpm-lock.yaml
  scripts/crawl.mjs
Labels: 3.x, chore

#20955 fix(vite): skip generating keys for locally scoped functions
  packages/schema/src/config/build.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/utils/index.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/keyed-composables/index.vue
  test/fixtures/basic/pages/keyed-composables/local.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#20892 fix(kit): temporarily inline `lodash.template` from `lodash-es`
  packages/kit/build.config.ts
  packages/kit/package.json
  packages/kit/src/internal/template.ts
  packages/schema/src/config/build.ts
  pnpm-lock.yaml
Labels: 3.x, chore

#21303 docs: add info about vue configuration
  docs/1.getting-started/3.configuration.md
Labels: documentation, 3.x

#21408 fix(nuxt): handle page rendering on different path
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/server/routes/proxy.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#20970 feat(nuxt): sync `useCookie` state between tabs
  docs/3.api/1.composables/use-cookie.md
  packages/nuxt/src/app/composables/cookie.ts
Labels: enhancement, 3.x, bug, 🔨 p3-minor-bug

#21246 feat(kit): module compatibility utils
  packages/kit/src/compatibility.ts
  packages/kit/src/index.ts
  packages/kit/src/module/compatibility.test.ts
  packages/kit/src/module/compatibility.ts
  packages/kit/src/module/install.ts
Labels: enhancement, 3.x, kit, 🍰 p2-nice-to-have

#18610 feat(nuxt): add `renderResult` to `app:rendered`
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: enhancement, 3.x

#21337 docs: include example for server utilities
  docs/2.guide/2.directory-structure/1.server.md
Labels: documentation, 3.x

#21407 fix(schema): remove obsolete terser option from webpack config
  packages/schema/build.config.ts
  packages/schema/src/config/webpack.ts
Labels: 3.x, 🔨 p3-minor-bug, schema

#21412 fix(nuxt): skip vue render when redirecting
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/navigate-to-error.vue
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#21436 feat(webpack): allow configuring `esbuild-loader` options
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/webpack.ts
  packages/webpack/src/presets/esbuild.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, webpack, 🍰 p2-nice-to-have

#9621 feat(csp): support generating nonce for scripts and links in ssr
  packages/config/src/options.js
  packages/config/test/options.test.js
  packages/types/config/render.d.ts
  packages/vue-renderer/src/renderers/ssr.js
  test/dev/basic.ssr.csp.test.js
Labels: enhancement, 2.x

#21333 feat(nuxt): add `open` option in `navigateTo` helper
  docs/3.api/3.utils/navigate-to.md
  packages/nuxt/src/app/composables/router.ts
  test/bundle.test.ts
Labels: enhancement, discussion, 3.x, 🍰 p2-nice-to-have

#21448 ci: move bundle skipping logic to workflow
  .github/workflows/ci.yml
  test/bundle.test.ts
Labels: 3.x, chore

#21462 docs: add info about merging strategy in app config
  docs/2.guide/2.directory-structure/3.app-config.md
Labels: documentation, 3.x

#21488 fix(babel-preset-app): add explicit dep on used babel plugin
  packages/babel-preset-app/package.json
  yarn.lock
Labels: 2.x, bug, 🔨 p3-minor-bug

#19495 feat(webpack): support passing function as `postcssOptions`
  packages/webpack/src/utils/postcss.js
  packages/webpack/test/postcss.test.js
  test/dev/postcss-function.test.js
  test/fixtures/postcss-function/nuxt.config.js
  test/fixtures/postcss-function/pages/css.vue
  test/fixtures/postcss-function/pages/postcss.vue
  test/fixtures/postcss-function/postcss-function.test.js
Labels: enhancement, 2.x, 🍰 p2-nice-to-have

#21355 v2.17.0
  distributions/nuxt-start/package.json
  distributions/nuxt/package.json
  lerna.json
  packages/babel-preset-app/package.json
  packages/builder/package.json
  packages/cli/package.json
  packages/config/package.json
  packages/core/package.json
  packages/generator/package.json
  packages/server/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/vue-app/package.json
  packages/vue-renderer/package.json
  packages/webpack/package.json
Labels: 2.x

#21409 feat(nuxt): provide `clearNuxtState` composable
  docs/1.getting-started/7.state-management.md
  docs/3.api/3.utils/clear-nuxt-data.md
  docs/3.api/3.utils/clear-nuxt-state.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/state.ts
  packages/nuxt/src/imports/presets.ts
  test/bundle.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21331 feat(kit): `addTypeTemplate` helper with auto-registration
  docs/2.guide/3.going-further/3.modules.md
  docs/3.api/4.advanced/2.kit.md
  packages/kit/src/template.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/types.ts
Labels: enhancement, documentation, 3.x, kit, 🍰 p2-nice-to-have

#21396 docs: remove example of deprecated reactivity transform
  docs/4.examples/7.experimental/reactivity-transform.md
  examples/experimental/reactivity-transform/app.vue
  examples/experimental/reactivity-transform/components/label.vue
  examples/experimental/reactivity-transform/nuxt.config.ts
  examples/experimental/reactivity-transform/package.json
  examples/experimental/reactivity-transform/tsconfig.json
  packages/schema/src/config/experimental.ts
Labels: documentation, 3.x

#21045 feat(nuxt): return `status` from `useAsyncData`
  docs/3.api/1.composables/use-async-data.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/pages/useAsyncData/status.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21081 fix(nuxi,nuxt): remove baseUrl + use relative paths in tsconfig
  packages/nuxi/src/utils/prepare.ts
  packages/nuxt/src/components/module.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#21501 fix(vite): invalidate templates by `dst` not `src`
  packages/vite/src/vite-node.ts
Labels: 3.x, bug, vite

#19403 feat(nuxt): allow accessing `NuxtPage` ref via `pageRef`
  docs/3.api/2.components/2.nuxt-page.md
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/wrapper-expose/page.vue
  test/fixtures/basic/pages/wrapper-expose/page/another.vue
  test/fixtures/basic/pages/wrapper-expose/page/index.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21524 fix(nuxt): don't disable vue endpoint in dev mode
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, nitro

#21500 fix(nuxt): respect query/hash for external routes in `navigateTo`
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/navigate-to-external.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#20680 docs: add warning about redirect check
  docs/2.guide/2.directory-structure/1.middleware.md
  docs/3.api/3.utils/abort-navigation.md
Labels: documentation, 3.x

#21461 perf(nuxt): use prerendered islands to serialise/revive payload
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/core/templates.ts
  test/basic.test.ts
  test/fixtures/basic/pages/prefetch/index.vue
  test/fixtures/basic/pages/prefetch/server-components.vue
  test/utils.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21521 fix(nuxt): abort navigation when updating `window.location`
  packages/nuxt/src/app/composables/router.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21547 feat(nuxt): emit error in `ssr-error` event
  packages/nuxt/src/app/components/client-fallback.server.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21588 fix(vite): ignore and warn if vite config file exists
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
Labels: 3.x

#21525 docs: add styling section
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#20763 feat(kit): allow direct function in `defineNuxtModule`
  docs/2.guide/3.going-further/3.modules.md
  packages/kit/src/module/define.ts
  test/fixtures/basic/modules/functional.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21583 fix(nuxt): ensure prerendered components are treated as islands
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21636 feat(nuxt): expose `useNuxtApp` to window for convenience
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/types/augments.d.ts
  test/bundle.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21645 fix(nuxt): replace `:` in rendered server components (for win)
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, windows, 🔨 p3-minor-bug

#21632 fix(nuxi): add back default `baseUrl` in `tsconfig.json`
  .github/workflows/ci.yml
  package.json
  packages/nuxi/src/utils/prepare.ts
  packages/nuxt/src/components/module.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/package.json
  test/fixtures/minimal-types/package.json
Labels: types, 3.x, bug, cli

#21611 perf(nuxt): extract and apply plugin order at build time
  packages/nuxt/package.json
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/test/plugin-metadata.test.ts
  packages/schema/src/types/nuxt.ts
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/basic/plugins/invalid-plugin-1.ts
  test/fixtures/basic/plugins/invalid-plugin-2.ts
Labels: enhancement, 3.x, performance

#21656 fix(nuxt): stop indicator when not changing page component
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21657 fix(nuxt): scroll to top in nested routes
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#21617 docs: add experimental features page
  docs/2.guide/3.going-further/1.experimental-features.md
Labels: documentation, 3.x

#21573 fix(nuxt): inline css directly in root component
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/src/plugins/paths.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/components/ServerOnlyComponent.server.vue
  test/fixtures/basic/pages/styles.vue
Labels: enhancement, 3.x, bug, 🔨 p3-minor-bug

#21640 feat(nuxt): allow configuring spa loading indicator
  docs/2.guide/1.concepts/3.rendering.md
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/app.ts
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#21666 feat(nuxt): add types for nuxt-defined nitro runtime hooks
  packages/nuxt/types.d.ts
Labels: enhancement, 3.x, bug, nitro

#21665 fix(nuxt): guard `res.end()` calls with check if event is handled
  package.json
  packages/nuxi/package.json
  packages/nuxt/package.json
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/schema/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21671 fix(nuxt): do not embed error path in payload
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21696 feat(nuxt): update devdependency nitropack to v2.5.1
  packages/kit/package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/components/nuxt-error-page.vue
  packages/nuxt/src/core/runtime/nitro/paths.ts
  packages/nuxt/types.d.ts
  packages/schema/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x, nitro

#21655 fix(nuxt): use static nitro build if possible
  packages/nuxt/src/core/nitro.ts
Labels: enhancement, 3.x, bug, nitro, 🍰 p2-nice-to-have

#21680 fix(nuxt): add aliases and augmentations for nitro context
  packages/nuxi/src/utils/prepare.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  playground/server/tsconfig.json
Labels: 3.x, bug, nitro, 🔨 p3-minor-bug

#21699 docs: update specified Nuxt 2 version in migration guide
  docs/6.bridge/1.overview.md
Labels: documentation, 3.x

#21450 fix(nuxt): fix error on layout switching
  packages/nuxt/src/app/components/layout.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/components/ComponentWithRef.vue
  test/fixtures/basic/layouts/custom-async.vue
  test/fixtures/basic/pages/layout-switch/end.vue
  test/fixtures/basic/pages/layout-switch/start.vue
Labels: 3.x, bug, ❗ p4-important

#21729 fix(nuxt): use esbuild/acorn instead of `typescript` dep
  packages/nuxt/package.json
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/test/plugin-metadata.test.ts
  pnpm-lock.yaml
Labels: 3.x, bug, ❗ p4-important

#21742 docs: add a link to Docus layer nuxt config file
  docs/2.guide/3.going-further/7.layers.md
Labels: documentation, 3.x

#21740 fix(nuxt): proxy headers to islands + returned prerender hints
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/components/ServerOnlyComponent.server.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#21739 fix(nuxt): respect `false` to disable spa loading template
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21732 fix(nuxt): remove `path` from SPA payload
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21730 fix(nuxt): only remove one item from middleware
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: 3.x, bug, ❗ p4-important

#21731 fix(nuxt): escape colons in page paths
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21724 fix(nuxt): augment nitro config within server context as well
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/types.d.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#21763 fix(nuxt): inline global css with `ssr: false` route rule
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21770 fix(vite): resolve css files without importer id first
  packages/vite/src/plugins/ssr-styles.ts
  test/basic.test.ts
Labels: bug, vite

#21790 fix(vite): emit assets referenced in inline css
  packages/vite/src/plugins/ssr-styles.ts
  test/basic.test.ts
  test/fixtures/basic/assets/css-only-asset.svg
  test/fixtures/basic/assets/global.css
Labels: bug, vite, ❗ p4-important

#21804 fix(webpack): pin `webpack-dev-middleware` to 5.0.0
  packages/webpack/package.json
  yarn.lock
Labels: 2.x, bug, 🔨 p3-minor-bug

#21809 chore: prune internal unused code and exports
  knip.json
  package.json
  packages/kit/src/internal/cjs.ts
  packages/nuxi/src/utils/cjs.ts
  packages/nuxi/src/utils/esm.ts
  packages/nuxi/src/utils/fs.ts
  packages/nuxi/src/utils/nuxt.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/modules.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/src/dirs.ts
  packages/schema/package.json
  packages/test-utils/src/dirs.ts
  packages/vite/src/dev-bundler.ts
  packages/vite/src/dirs.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/dev-ssr-css.ts
  packages/vite/src/plugins/paths.ts
  packages/vite/src/plugins/pure-annotations.ts
  packages/vite/src/utils/index.ts
  packages/vite/src/utils/logger.ts
  packages/webpack/src/plugins/vue/server.ts
  packages/webpack/src/presets/base.ts
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
  test/fixtures/basic-types/package.json
  test/fixtures/basic/package.json
  vitest.config.ts
Labels: 3.x, chore

#21815 fix(nuxt): only redirect if path is not the same as initial url
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/fixtures/basic/plugins/add-route.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#21805 docs: add warning about dynamic import of css
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#21811 docs: update example links
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  README.md
  docs/0.index.md
  docs/1.getting-started/5.seo-meta.md
  docs/1.getting-started/6.data-fetching.md
  docs/1.getting-started/7.state-management.md
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/2.directory-structure/1.composables.md
  docs/2.guide/2.directory-structure/1.layouts.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/3.api/1.composables/use-cookie.md
  docs/3.api/1.composables/use-fetch.md
  docs/3.api/2.components/4.nuxt-link.md
  docs/3.api/2.components/8.teleports.md
  package.json
Labels: documentation

#21836 fix(nuxi): resolve `@nuxt/ui-templates` from `modulesDir`
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/utils/esm.ts
Labels: 3.x, bug, cli, 🔨 p3-minor-bug

#21837 fix(nuxt, vite): do not use cjs utils to resolve/alias vue
  .gitignore
  packages/nuxt/src/core/nitro.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  test/bundle.test.ts
  test/fixtures/minimal/nuxt.config.ts
Labels: 3.x, bug, nitro, vite, 🔨 p3-minor-bug

#21849 fix(vite): greater type-safety within runtime vite-node
  packages/vite/src/runtime/vite-node-shared.d.ts
  packages/vite/src/runtime/vite-node-shared.mjs
  packages/vite/src/vite-node.ts
Labels: 3.x, chore, 🍰 p2-nice-to-have

#21860 fix(nuxt): ensure static presets equivalent to `nuxi generate`
  packages/nuxi/src/commands/build.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21864 fix(nuxt): handle injecting multiple entry ids for styles
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug, 🔨 p3-minor-bug
