Repository nuxt/nuxt, pull requests merged in 2023-09, with the labels that each got.

#22991 fix(vite): don't set explicit conditions in `shouldExternalize`
  packages/vite/src/vite-node.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#22986 fix(nuxt): render inlined ssr styles before stylesheets
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#22998 fix(nuxt): improve types within plugin templates
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
Labels: types, 3.x, chore

#22999 perf(nuxt): decrease default bundle size
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/bundle.test.ts
Labels: 3.x, 🍰 p2-nice-to-have, performance

#22889 fix(nuxt): load layer plugins before project plugins
  packages/nuxt/src/core/app.ts
  test/basic.test.ts
  test/fixtures/basic/extends/bar/plugins/09.layer-plugin-pre.ts
  test/fixtures/basic/extends/bar/plugins/11.layer-plugin-post.ts
  test/fixtures/basic/plugins/10.layer-ordering.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#22997 fix(nuxt): use `destr` in more places over `JSON.parse`
  packages/nuxt/src/app/components/test-component-wrapper.ts
  packages/nuxt/src/app/composables/chunk.ts
  packages/nuxt/src/app/plugins/restore-state.client.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
Labels: 3.x, 🍰 p2-nice-to-have, performance

#22973 fix(nuxt): resolve head instance from Nuxt app
  docs/1.getting-started/4.styling.md
  docs/1.getting-started/5.seo-meta.md
  docs/3.api/1.composables/use-head-safe.md
  docs/3.api/1.composables/use-head.md
  packages/nuxt/package.json
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  packages/schema/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x, bug

#22975 fix(nuxt): always use increment for id with client side islands
  packages/nuxt/src/app/components/nuxt-island.ts
  test/basic.test.ts
Labels: 3.x, bug

#23031 ci: add script to update changelog for 2.x releases
  .github/workflows/changelogensets.yml
  package.json
  scripts/_utils.ts
  scripts/update-changelog.ts
  yarn.lock
Labels: 2.x, chore

#22403 fix(nuxt): scroll to top by default on dynamic routes
  packages/nuxt/src/pages/runtime/router.options.ts
  test/basic.test.ts
  test/fixtures/basic/modules/page-extend/index.ts
  test/fixtures/basic/modules/page-extend/pages/big-page.vue
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/nested/[foo].vue
  test/fixtures/basic/pages/nested/[foo]/[bar].vue
  test/fixtures/basic/pages/nested/[foo]/user-[group].vue
Labels: 3.x, bug

#23049 fix(vite): add css to manifest without `cssCodeSplit`
  packages/vite/src/manifest.ts
Labels: bug, vite, 🔨 p3-minor-bug

#23040 fix(nuxt): find parent routes by exact path match
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#23120 fix(nuxt): handle unset spa-loading fallback
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/app.ts
Labels: 3.x, bug

#23122 ci: update fixtures to node 18
  .github/workflows/ci.yml
  test/basic.test.ts
Labels: 3.x, chore

#23126 fix(vite): remove dev styles injected via absolute path
  packages/vite/src/plugins/dev-ssr-css.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#23127 fix(nuxt): default scanned layer components to priority `0`
  packages/nuxt/src/components/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23135 ci: unpin node 20 actions runners
  .github/workflows/autofix-docs.yml
  .github/workflows/autofix.yml
  .github/workflows/changelogensets.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release-pr.yml
Labels: 3.x, chore

#23134 fix(nuxt): allow granularly overriding pages in layers
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
  test/basic.test.ts
  test/fixtures/basic/extends/bar/pages/override.vue
  test/fixtures/basic/extends/node_modules/foo/pages/override/index.vue
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#23145 chore(nuxt): update nuxi
  package.json
  packages/nuxt/package.json
  packages/test-utils/src/server.ts
  pnpm-lock.yaml
Labels: 3.x, chore

#23133 fix(nuxt): allow changing dirs within modules
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#23156 fix(nuxt): allow overriding components + only warn if clash
  packages/nuxt/src/components/scan.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#21980 refactor(nuxt): don't wrap server placeholders/client fallbacks
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/types/components.ts
Labels: 3.x, bug, refactor

#23188 fix(nuxt): allow importing server components from `#components`
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/transform.ts
  test/fixtures/basic/components/global/ServerComponentGlobal.server.vue
Labels: 3.x, bug, 🔨 p3-minor-bug, server components

#23191 fix(nuxt): use original escapes/quotes in page re-exports
  packages/nuxt/src/pages/plugins/page-meta.ts
  test/fixtures/basic/pages/non-ascii/ç.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#23205 refactor(nuxt): use built-in consola prompts
  packages/nuxt/package.json
  packages/nuxt/src/core/features.ts
  pnpm-lock.yaml
Labels: 3.x, performance

#23206 fix(schema): default devServer host to undefined
  packages/schema/src/config/dev.ts
Labels: 3.x, bug, schema

#22925 fix(nuxt): load layer middlewares before project middlewares
  packages/nuxt/src/core/app.ts
  test/basic.test.ts
  test/fixtures/basic/extends/bar/middleware/a.global.ts
  test/fixtures/basic/extends/bar/middleware/override.ts
  test/fixtures/basic/extends/node_modules/foo/middleware/override.ts
  test/fixtures/basic/middleware/b.global.ts
Labels: 3.x, bug

#23238 fix(nuxt): don't incl overridden layer pages as nested children
  packages/nuxt/src/pages/utils.ts
  test/fixtures/basic/extends/node_modules/foo/pages/override.vue
Labels: 3.x, bug, pages, ❗ p4-important

#23276 fix(vite): explicitly set vite manifest path
  packages/vite/src/client.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#21893 docs: add support details and update roadmap (#21867)
  docs/5.community/6.roadmap.md
Labels: documentation, 3.x

#21641 fix(nuxt): experimental build manifest + client route rules
  .github/workflows/ci.yml
  package.json
  packages/nuxt/index.d.ts
  packages/nuxt/package.json
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/middleware/manifest-route-rule.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/minimal-types/nuxt.config.ts
  test/fixtures/minimal-types/types.ts
  test/nuxt/composables.test.ts
  vitest.nuxt.config.ts
Labels: enhancement, 3.x, bug, 🔨 p3-minor-bug

#23333 fix(nuxt): generate empty file when shim is disabled
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#23357 fix(nuxt): add import protection for `nuxt/*` exports
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/test/import-protection.test.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#23373 docs: add `tryUseNuxt` to kit context utils list
  docs/3.api/4.advanced/2.kit.md
Labels: documentation, 3.x

#23404 fix(nuxt): detect nested pages with `/index` segments
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug, ❗ p4-important

#23415 docs: mention `listhen` options on nuxi dev page
  docs/3.api/5.commands/dev.md
Labels: documentation, 3.x

#23428 fix(nuxt): initialise `asyncData` errors with `null`
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#23420 docs: improve data fetching section
  docs/1.getting-started/6.data-fetching.md
Labels: documentation

#23436 docs: remove duplicated arrows
  docs/2.guide/2.directory-structure/1.server.md
Labels: documentation, 3.x

#23389 docs: extend description of `handler` param for useAsyncData composable
  docs/3.api/1.composables/use-async-data.md
Labels: documentation, 3.x

#23440 fix(nuxt): rename dts to avoid shadowing w/ baseUrl
  packages/nuxt/src/pages/module.ts
Labels: types, 3.x, bug

#23288 feat(kit): add `addServerImports` and `addServerImportsDir`
  packages/kit/src/nitro.ts
  test/basic.test.ts
  test/fixtures/basic/modules/auto-registered/index.ts
  test/fixtures/basic/modules/auto-registered/runtime/server/utils/some-utils.ts
  test/fixtures/basic/modules/auto-registered/runtime/some-server-import.ts
  test/fixtures/basic/server/api/auto-imports.ts
Labels: enhancement, 3.x, kit

#23286 feat(nuxt): warn when nesting nuxt links when SSR on dev
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: enhancement, 3.x, dx, 🍰 p2-nice-to-have

#22863 feat(nuxt): add `prerenderRoutes` ssr composable
  docs/3.api/3.utils/prerender-routes.md
  docs/3.api/4.advanced/2.kit.md
  packages/kit/src/nitro.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/imports/presets.ts
  test/fixtures/basic/components/ServerOnlyComponent.server.vue
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x, nitro, 🍰 p2-nice-to-have

#23359 perf(vite): don't print server compressed size after vite build
  packages/vite/src/server.ts
Labels: 3.x, dx, vite, performance

#23449 fix(nuxt): stringify cookie values before broadcasting them
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#23448 feat(nuxt): enable `appManifest` by default
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have
