Repository nuxt/nuxt, pull requests merged in 2023-11, with the labels that each got.

#24022 fix(nuxt): resolve imports from virtual files
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24072 fix(vite): include more of warmup within try/catch
  packages/vite/src/utils/warmup.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#24091 fix(nuxt): use shared `isChangingPage` util in scrollBehavior
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x, 🔨 p3-minor-bug

#24043 fix(nuxt): account for delay ≤ 0 in `useCookie`
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24146 chore: extract `@nuxt/test-utils` to separate repo
  .eslintrc
  .stackblitz/codeflow.json
  knip.json
  package.json
  packages/test-utils/README.md
  packages/test-utils/build.config.ts
  packages/test-utils/experimental.d.ts
  packages/test-utils/package.json
  packages/test-utils/src/browser.ts
  packages/test-utils/src/context.ts
  packages/test-utils/src/dirs.ts
  packages/test-utils/src/experimental.ts
  packages/test-utils/src/index.ts
  packages/test-utils/src/mock.ts
  packages/test-utils/src/nuxt.ts
  packages/test-utils/src/run.ts
  packages/test-utils/src/runtime/global-setup.ts
  packages/test-utils/src/server.ts
  packages/test-utils/src/setup/index.ts
  packages/test-utils/src/setup/jest.ts
  packages/test-utils/src/setup/vitest.ts
  packages/test-utils/src/types.ts
  pnpm-lock.yaml
  scripts/release-edge.sh
  scripts/release-rc.sh
  scripts/release.sh
  test/basic.test.ts
  vitest.config.ts
Labels: 3.x, chore

#24162 fix(vite): skip warming up node builtins
  packages/vite/src/utils/warmup.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#24093 fix(nuxt): wrap caught asyncData error in `createError`
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#24195 test: add route-provider e2e test
  test/basic.test.ts
  test/fixtures/basic/pages/route-provider/index.vue
  test/fixtures/basic/pages/route-provider/index/bar.vue
  test/fixtures/basic/pages/route-provider/index/foo.vue
Labels: 3.x, test, 🧹 p1-chore

#23943 fix(nuxt): include plugin templates in `plugins.d.ts` if they will be written
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#24212 fix(nuxt): handle multi-line slots in islands
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x, bug, server components

#24255 fix(nuxt): fix replace regex used for slots in islands SSR
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, server components

#24248 docs: correct spelling from "opiniated" to "opinionated"
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#23036 docs: unfined defineNuxtPlugin migration guide for nuxt bridge #22433
  docs/6.bridge/3.bridge-composition-api.md
Labels: documentation, 3.x

#24260 docs: add mention about `nuxt3-vuex-module`
  docs/7.migration/2.configuration.md
Labels: documentation, 3.x

#24269 docs: fix links in 1.auto-imports.md
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#23903 fix(vite): use rollup replace plugin for `typeof` optimisations
  packages/vite/src/server.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#24024 fix(nuxt): provide route component names to `KeepAlive` cache
  packages/nuxt/src/app/components/route-provider.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/composables/keep-alive.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/keepalive.vue
  test/fixtures/basic/pages/keepalive/keepalive-in-config.vue
  test/fixtures/basic/pages/keepalive/keepalive-in-nuxtpage-2.vue
  test/fixtures/basic/pages/keepalive/keepalive-in-nuxtpage.vue
  test/fixtures/basic/pages/keepalive/not-keepalive-in-nuxtpage.vue
  test/fixtures/basic/pages/keepalive/not-keepalive.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#24295 docs: remove only
  docs/2.guide/2.directory-structure/1.server.md
Labels: documentation, 3.x

#23696 fix(schema): use scule types for `runtimeConfig` type hints
  packages/schema/package.json
  packages/schema/src/types/config.ts
  pnpm-lock.yaml
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#24307 fix(nuxt): deeply unwrap headers/query for useFetch key
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24318 fix(nuxt): split component name case in each segment
  packages/kit/package.json
  packages/nuxt/package.json
  packages/nuxt/src/core/utils/names.ts
  pnpm-lock.yaml
Labels: 3.x, bug, 🔨 p3-minor-bug

#24333 fix(nuxt): do not compute `useFetch` key from headers (reverting #23462)
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24252 docs: add hint about app.config placement with custom srcDir
  docs/2.guide/2.directory-structure/3.app-config.md
Labels: documentation, 3.x

#24323 docs: typos and wording tweaks for guide section
  docs/2.guide/1.concepts/2.vuejs-development.md
  docs/2.guide/1.concepts/7.esm.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/2.directory-structure/1.middleware.md
  docs/2.guide/2.directory-structure/1.pages.md
  docs/2.guide/2.directory-structure/1.public.md
  docs/2.guide/2.directory-structure/1.server.md
Labels: documentation, 3.x

#24244 docs: update route parameters in example
  docs/2.guide/2.directory-structure/1.content.md
Labels: documentation, 3.x

#23680 chore: added cd in docs
  docs/1.getting-started/2.installation.md
Labels: documentation, 3.x

#24337 fix(schema): add type for `ignoreOptions`
  packages/schema/src/config/common.ts
Labels: types, 3.x, chore, schema

#24349 docs: minor wording & formatting tweaks
  docs/2.guide/3.going-further/3.modules.md
  docs/3.api/1.components/1.nuxt-client-fallback.md
  docs/3.api/1.components/3.nuxt-layout.md
  docs/3.api/1.components/7.nuxt-welcome.md
  docs/3.api/1.components/8.nuxt-island.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#24364 fix(nuxt): respect custom timeout in `useFetch`
  docs/3.api/2.composables/use-fetch.md
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24375 docs: fix typo
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#24253 fix(nuxt): use max length + iterations for `useCookie` timeout
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug

#24399 fix(nuxt): avoid recursive ssr errors
  packages/nuxt/src/core/runtime/nitro/error.ts
  test/basic.test.ts
  test/fixtures/basic/plugins/error.server.ts
  test/fixtures/basic/server/api/error.ts
Labels: 3.x, bug, ❗ p4-important

#24116 feat(nuxt): warn when page uses a layout without `<NuxtLayout>`
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/app/plugins/check-if-layout-used.ts
  packages/nuxt/src/core/nuxt.ts
Labels: enhancement, 3.x, dx, 🍰 p2-nice-to-have

#24309 feat(kit): support prepend option for `addComponentsDir`
  packages/kit/src/components.ts
Labels: enhancement, 3.x, kit, 🍰 p2-nice-to-have

#24243 feat(kit): allow customising logger options
  docs/3.api/5.kit/13.logging.md
  packages/kit/src/logger.test.ts
  packages/kit/src/logger.ts
Labels: enhancement, 3.x, kit

#24426 feat: migrate to `hookable` package
  packages/cli/package.json
  packages/cli/src/command.js
  packages/core/package.json
  packages/core/src/nuxt.js
  packages/core/test/nuxt.test.js
  yarn.lock
Labels: 2.x

#24504 fix(nuxt): ignore manifest when prerendering
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24503 feat(nuxt): allow readonly option for `useCookie`
  docs/3.api/2.composables/use-cookie.md
  packages/nuxt/src/app/composables/cookie.ts
  test/fixtures/basic-types/types.ts
Labels: enhancement, 3.x, bug, 🍰 p2-nice-to-have, 🔨 p3-minor-bug

#24512 fix(vite): use `isBuiltin` polyfill for greater node support
  packages/vite/src/utils/warmup.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#24469 fix(nuxt): island components with number prefix
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
  test/fixtures/basic/components/1thing.island.vue
Labels: 3.x, bug

#24514 fix(nuxt): use consistent annotations for tree-shaking
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/runtime/composables.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#24517 fix(nuxt): skip prerendering all pages in hash mode
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#24421 fix(nuxt): skip router middleware/redirections for islands
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x

#24516 fix(nuxt): remove trailing slash before checking if prerendered
  packages/nuxt/src/app/composables/payload.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#24526 refactor(nuxt): opt-in to future `jiti.import` for schema
  packages/nuxt/src/core/schema.ts
Labels: enhancement, 3.x, 🧹 p1-chore
