Repository nuxt/nuxt, pull requests merged in 2023-08, with the labels that each got.

#22410 fix(kit): remove `baseUrl` and use relative paths in tsconfig
  packages/kit/package.json
  packages/kit/src/template.ts
  pnpm-lock.yaml
Labels: 3.x, bug, kit, 🔨 p3-minor-bug

#22389 docs: escape `]` in code-block filenames
  docs/1.getting-started/5.routing.md
  docs/1.getting-started/5.transitions.md
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/2.directory-structure/1.content.md
  docs/2.guide/2.directory-structure/1.pages.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/3.api/1.composables/use-route.md
  docs/3.api/3.utils/create-error.md
  docs/7.migration/7.component-options.md
Labels: documentation, 3.x

#22468 fix(kit): apply preferred options for esbuild transpilation
  packages/kit/src/template.ts
Labels: types, 3.x, bug, kit

#22465 perf(nuxt): use LRU prerender cache and limit cached items
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: enhancement, 3.x, 🔨 p3-minor-bug, performance

#22500 fix(nuxi): display log when restarting nuxt
  packages/nuxi/src/commands/dev.ts
Labels: 3.x, bug, cli

#22518 chore: refresh lockfile
  packages/nuxt/src/app/components/client-fallback.client.ts
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/vite/src/plugins/chunk-error.ts
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/basic/components/clientFallback/StatefulSetup.vue
  test/fixtures/basic/pages/client-only-explicit-import.vue
  test/fixtures/basic/pages/with-layout2.vue
  test/fixtures/basic/server/plugins/headers.ts
Labels: 3.x, chore

#21585 feat(nuxt): use build plugin to access nuxt route injection
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/route-injection.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x

#22478 feat(nuxt): resolve unresolved paths within `node_modules`
  packages/kit/src/module/install.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
Labels: enhancement, 3.x, 🔨 p3-minor-bug

#22524 fix(schema): `webpack` options should be optional
  packages/schema/src/types/config.ts
Labels: 3.x, bug, webpack, schema

#22494 fix(nuxt): enable hmr of `app.config.ts` files
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#20918 feat(nuxt): experimental native async context support
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/async-context.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/experimental.ts
  packages/vite/src/vite.ts
  packages/webpack/src/presets/base.ts
  test/basic.test.ts
  test/fixtures/basic/composables/async-context.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/async-context.vue
  vitest.config.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#22530 test: remove JS payload test + add non-async context test
  .github/workflows/ci.yml
  package.json
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/utils.ts
Labels: 3.x, test

#22538 chore: increase stale bot limit to 300
  .github/workflows/reproduire-close.yml
Labels: chore

#22558 feat(nuxt): allow experimental `global: 'sync'` components
  packages/nuxt/src/components/templates.ts
  packages/schema/src/types/components.ts
  test/basic.test.ts
  test/fixtures/basic/components/GlobalSync.vue
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/index.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#22576 fix(vite): include `import.meta` build vars in `define` as well
  packages/schema/src/config/vite.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  vitest.nuxt.config.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#22580 fix(nuxt): provide fallback route
  packages/nuxt/src/pages/route-injection.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#22592 fix(nuxt): unsub from hooks when unmounting indicator
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#22593 chore: depend on `h3-nightly` on edge releases
  scripts/bump-edge.ts
Labels: 3.x, chore

#22596 test: refactor test suite and reduce `networkidle` dependency
  test/basic.test.ts
  test/hmr.test.ts
  test/runtime-compiler.test.ts
  test/utils.ts
Labels: 3.x, chore, test

#22633 fix(nuxt): use relative paths when augmenting types
  packages/nuxt/src/pages/module.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#22636 fix(nuxt): don't prompt to install packages in CI
  packages/nuxt/package.json
  packages/nuxt/src/core/features.ts
  pnpm-lock.yaml
Labels: 3.x, bug, 🔨 p3-minor-bug

#22627 docs: warn directives must be registered on both server/client
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: documentation, 3.x

#22642 fix(nuxi): ignore error if nitro is not enabled on bridge
  packages/nuxi/package.json
  packages/nuxi/src/commands/build.ts
  pnpm-lock.yaml
Labels: 3.x, bug, cli

#22774 test: add regression test for escaping payload
  test/fixtures/basic/pages/json-payload.vue
Labels: 3.x, chore, test

#20391 feat(nuxt): add support for `routeRules` defined within pages
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/src/pages/plugins/route-injection.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
  packages/schema/src/config/experimental.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/route-rules/inline.vue
  test/hmr.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#20980 fix(nuxt): recreate `asyncData` when `immediate` is disabled
  docs/3.api/1.composables/use-async-data.md
  docs/3.api/1.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  test/basic.test.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/useAsyncData/immediate-remove-unmounted.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#22787 feat(schema): support setting `hidden` sourcemaps
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/build.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/webpack.ts
Labels: enhancement, 3.x, schema

#22782 fix(nuxt): respect ignorelist when scanning auto-imports
  packages/nuxt/src/imports/module.ts
  test/basic.test.ts
  test/fixtures/basic/.nuxtignore
  test/fixtures/basic/composables/ignored.ts
  test/fixtures/basic/pages/ignore/composables.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#22785 refactor(nuxt): import `useNitroApp` from subpath
  packages/nuxt/src/core/runtime/nitro/error.ts
Labels: 3.x, bug, nitro, 🔨 p3-minor-bug

#22808 feat(kit,nuxt): respect nuxt ignore patterns in nitro
  packages/kit/src/ignore.ts
  packages/kit/src/index.ts
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/types/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/.nuxtignore
  test/fixtures/basic/public/ignore/public-asset
  test/fixtures/basic/server/routes/ignore/scanned.ts
Labels: enhancement, 3.x, nitro, kit

#22798 fix(nuxt): default `spaLoadingTemplate` to `false`
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/app.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#22812 fix(vite): only mark nitro deps as externals when building
  packages/vite/src/server.ts
Labels: 3.x, bug, vite

#22799 feat(nuxt): migrate to new `nuxt/cli`
  .gitignore
  .stackblitz/codeflow.json
  package.json
  packages/nuxi/README.md
  packages/nuxi/bin/nuxi.mjs
  packages/nuxi/build.config.ts
  packages/nuxi/package.json
  packages/nuxi/src/cli-run.ts
  packages/nuxi/src/cli-wrapper.ts
  packages/nuxi/src/cli.ts
  packages/nuxi/src/commands/add.ts
  packages/nuxi/src/commands/analyze.ts
  packages/nuxi/src/commands/build-module.ts
  packages/nuxi/src/commands/build.ts
  packages/nuxi/src/commands/cleanup.ts
  packages/nuxi/src/commands/dev.ts
  packages/nuxi/src/commands/devtools.ts
  packages/nuxi/src/commands/generate.ts
  packages/nuxi/src/commands/index.ts
  packages/nuxi/src/commands/info.ts
  packages/nuxi/src/commands/init.ts
  packages/nuxi/src/commands/prepare.ts
  packages/nuxi/src/commands/preview.ts
  packages/nuxi/src/commands/test.ts
  packages/nuxi/src/commands/typecheck.ts
  packages/nuxi/src/commands/upgrade.ts
  packages/nuxi/src/commands/usage.ts
  packages/nuxi/src/index.ts
  packages/nuxi/src/run.ts
  packages/nuxi/src/utils/banner.ts
  packages/nuxi/src/utils/cjs.ts
  packages/nuxi/src/utils/diff.ts
  packages/nuxi/src/utils/engines.ts
  packages/nuxi/src/utils/env.ts
  packages/nuxi/src/utils/esm.ts
  packages/nuxi/src/utils/fs.ts
  packages/nuxi/src/utils/help.ts
  packages/nuxi/src/utils/kit.ts
  packages/nuxi/src/utils/nuxt.ts
  packages/nuxi/src/utils/packageManagers.ts
  packages/nuxi/src/utils/templates.ts
  packages/nuxt/package.json
  packages/test-utils/src/server.ts
  pnpm-lock.yaml
Labels: 3.x, chore

#22882 fix(kit): respect `priority` when registering components dirs
  packages/kit/src/components.ts
  packages/nuxt/src/components/scan.ts
  packages/schema/src/types/components.ts
Labels: 3.x, bug, kit

#22920 docs: update examples of dynamic `pageKey`
  docs/2.guide/2.directory-structure/1.pages.md
  docs/3.api/2.components/2.nuxt-page.md
Labels: documentation, 3.x
