Repository nuxt/nuxt, pull requests merged in 2024-08, with the labels that each got.

#28377 chore(schema): fix typo
  packages/schema/src/config/experimental.ts
Labels: 3.x, chore

#28331 docs: setup host property and usage example
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#28356 chore: fix router code reference permalink
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, chore

#28403 docs: fix TypeScript errors for examples
  docs/2.guide/4.recipes/1.custom-routing.md
Labels: documentation, 3.x

#28327 docs: improve readability
  docs/3.api/6.advanced/2.import-meta.md
Labels: documentation, 3.x

#28411 docs: use ts for create-error example
  docs/3.api/3.utils/create-error.md
Labels: documentation, 3.x

#28407 chore(nuxt): remove unecessary await
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, chore

#28391 fix(nuxt)!: remove unused `globalName` property
  packages/nuxt/src/app/nuxt.ts
Labels: enhancement, 3.x

#28414 chore: upgrade vue in a separate pr
  renovate.json
Labels: 3.x, chore

#28349 fix(nuxt): use static import for hmr `updateAppConfig`
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#28307 fix(schema): update for vue option change in `vite-plugin-vue`
  packages/schema/src/config/vite.ts
Labels: 3.x, bug

#28270 docs: alias links in jsdoc `@see` blocks
  packages/schema/src/config/adhoc.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/nitro.ts
  packages/schema/src/config/postcss.ts
  packages/schema/src/config/router.ts
  packages/schema/src/config/typescript.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/config/webpack.ts
Labels: documentation, 3.x

#28392 feat: allow to specify app id when creating a nuxt app
  packages/nuxt/src/app/composables/id.ts
  packages/nuxt/src/app/nuxt.ts
  packages/schema/src/config/common.ts
Labels: enhancement, 3.x

#28433 chore: update docs typecheck command
  package.json
Labels: 3.x, chore

#28320 fix(nuxt): handle `scroll-padding-top: auto` in scrollBehavior
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x, bug

#28443 fix(nuxt): ensure `runtimeConfig.public` is reactive on client
  packages/nuxt/src/app/composables/payload.ts
Labels: 3.x, bug, 🔨 p3-minor

#28449 fix(nuxt): updated renamed stub composables from `nuxt/scripts`
  packages/nuxt/src/app/composables/script-stubs.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: 3.x, bug

#28446 fix(nuxt): augment `@vue/runtime-core` and `@vue/runtime-dom`
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor

#28215 perf(nuxt): call cookie `decode` function only for named cookie
  package.json
  packages/nuxt/src/app/composables/cookie.ts
  pnpm-lock.yaml
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#28463 docs: link to vue test utils docs for `mountSuspended`
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#28371 feat: use-preview-mode custom callbacks
  docs/3.api/2.composables/use-preview-mode.md
  packages/nuxt/src/app/composables/preview.ts
Labels: enhancement, 3.x

#28479 fix(nuxt): scan jsx pages for page metadata
  packages/nuxt/src/core/utils/index.ts
  packages/nuxt/src/core/utils/plugins.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug, 🔨 p3-minor, possible regression

#28480 fix(nuxt): handle plugin type extensions more correctly
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, ❗ p4-important

#28481 fix(vite,webpack): handle local postcss plugins
  packages/vite/src/css.ts
  packages/webpack/src/utils/postcss.ts
Labels: 3.x, bug, 🔨 p3-minor

#28482 fix(vite): respect `baseURL` for public assets in dev
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug, vite, 🔨 p3-minor, possible regression

#28484 docs: fix vue-tsc version in TypeScript page
  docs/2.guide/1.concepts/8.typescript.md
Labels: documentation, 3.x

#28488 fix(vite): write dev manifest when `ssr: false`
  packages/vite/src/manifest.ts
  packages/vite/src/server.ts
Labels: 3.x, bug, vite, 🔨 p3-minor

#28489 docs: recommend '#teleports' target instead of 'body'
  docs/3.api/1.components/11.teleports.md
Labels: documentation, 3.x

#28497 docs: correct custom routing link
  docs/2.guide/2.directory-structure/1.pages.md
  docs/2.guide/4.recipes/1.custom-routing.md
  docs/3.api/3.utils/define-page-meta.md
  docs/7.migration/7.component-options.md
Labels: documentation, 3.x

#28334 perf(nuxt): prevent converting client only component setup to Promise
  packages/nuxt/src/app/components/client-only.ts
  test/basic.test.ts
  test/fixtures/basic/components/WrapClientComponent.vue
  test/fixtures/basic/pages/client-only-components.vue
Labels: 3.x, performance

#28501 chore: fix some comments
  test/basic.test.ts
  test/fixtures/basic/components/ServerWithClient.server.vue
  test/fixtures/basic/pages/client.vue
Labels: 3.x, chore

#28496 feat(kit): add `prepend` option to `addRouteMiddleware`
  docs/3.api/5.kit/7.pages.md
  packages/kit/src/pages.ts
Labels: enhancement, 3.x

#28508 fix(vite): log transformation result when a PARSE_ERROR happens
  packages/vite/src/vite-node.ts
Labels: 3.x, bug

#28509 fix(vite): include module symbols in generated code
  packages/vite/src/server.ts
Labels: 3.x, bug, upstream, 🔨 p3-minor

#28276 feat(nuxt): route group
  docs/2.guide/2.directory-structure/1.pages.md
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
  test/basic.test.ts
  test/fixtures/basic/pages/(new-group)/group-page.vue
  test/fixtures/basic/pages/nested-group/(deep-group)/group-page.vue
  test/fixtures/basic/pages/nested-group/(index-group)/index.vue
  test/fixtures/basic/pages/nested-group/more-nested/(more-deep)/group-page.vue
Labels: enhancement, 3.x

#27689 feat(nuxt): generate basic jsdoc for module config entry
  packages/nuxt/src/core/templates.ts
Labels: enhancement, 3.x

#28517 fix(nuxt): add reason when aborting request in `useFetch`
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x

#28389 docs: fix `options` type in custom useFetch recipe
  docs/2.guide/4.recipes/3.custom-usefetch.md
Labels: documentation, 3.x

#28521 feat(vite): preserve vite sourcemaps for nitro build
  packages/vite/src/plugins/nitro-sourcemap.ts
  packages/vite/src/server.ts
Labels: enhancement, 3.x

#28531 ci: add reproduire-sur-stackblitz workflow
  .github/workflows/reproduire-sur-stackblitz.yml
Labels: 3.x, chore

#28553 docs: update useRuntimeConfig source path
  docs/3.api/2.composables/use-runtime-config.md
Labels: documentation, 3.x

#28542 fix(nuxt): only augment `vue`, not sub-packages
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/typescript.ts
Labels: types, 3.x, bug, 🔨 p3-minor

#28514 docs: persist package manager choice in code blocks
  docs/1.getting-started/11.testing.md
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/2.installation.md
  docs/1.getting-started/4.styling.md
  docs/1.getting-started/9.prerendering.md
  docs/2.guide/1.concepts/8.typescript.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/2.guide/3.going-further/3.modules.md
  docs/2.guide/4.recipes/2.vite-plugin.md
  docs/6.bridge/1.overview.md
  docs/6.bridge/8.nitro.md
Labels: enhancement, 3.x

#28563 perf(nuxt): directly return ServerPlaceholder in createClientOnly in server bundle
  packages/nuxt/src/app/components/client-only.ts
Labels: 3.x, performance

#28593 fix(nuxt): avoid stripping js extensions in plugin injections
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug, 🔨 p3-minor

#28587 docs: add proper line-breaks to tips in Module Author Guide
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#28441 fix(nuxt): preserve route-specific metadata on `route.meta`
  docs/1.getting-started/12.upgrade.md
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug

#27846 feat(nuxt): allow defining triggers for prefetching links
  docs/3.api/1.components/4.nuxt-link.md
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/schema/src/config/experimental.ts
  test/nuxt/components.test.ts
Labels: 3.x

#28594 feat(schema): split dev/prod build directories
  packages/schema/src/config/common.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
  test/hmr.test.ts
  test/suspense.test.ts
Labels: enhancement, dx, 🍰 p2-nice-to-have

#28604 fix(nuxt): don't warn when fetch/asyncData is called in middleware
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#28625 fix(nuxt): handle multiple `<script>` blocks for route rules + page meta
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug

#28612 fix: allow customising status code in validate method
  packages/nuxt/src/pages/runtime/validate.ts
  test/basic.test.ts
  test/fixtures/basic/pages/navigate-to-validate-custom-error.vue
  test/fixtures/basic/pages/validate-custom-error.vue
Labels: 3.x

#28629 docs: update nuxt scripts status
  docs/5.community/6.roadmap.md
  docs/5.community/7.changelog.md
Labels: 3.x

#28630 fix(nuxt): do not provide default `prefetchOn` prop
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug

#27987 feat(nuxt): head manipulation with islands
  package.json
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/server-page.server.vue
  test/utils.ts
Labels: enhancement, 3.x

#28656 fix(nuxt): revert back to object syntax for island head
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/utils.ts
Labels: 3.x, bug, 🔨 p3-minor

#28684 chore: use `tinyexec` internally
  package.json
  packages/ui-templates/package.json
  packages/ui-templates/test/templates.spec.ts
  pnpm-lock.yaml
  scripts/_utils.ts
  test/bundle.test.ts
  test/prepare.ts
Labels: 3.x, chore

#28686 chore: use `tinyglobby` internally
  package.json
  packages/ui-templates/lib/prerender.ts
  packages/ui-templates/lib/render.ts
  packages/ui-templates/package.json
  pnpm-lock.yaml
  scripts/_utils.ts
  test/bundle.test.ts
  test/prepare.ts
Labels: 3.x, chore

#28687 chore: trim tag
  scripts/_utils.ts
Labels: 3.x, chore

#28700 fix(schema): make serverDir only relative to root
  packages/schema/src/config/common.ts
Labels: 3.x, bug

#28706 chore: improve accuracy of 4.x changelog
  scripts/_utils.ts
  scripts/update-changelog.ts
Labels: 3.x, chore

#28709 fix(nuxt): handle mismatching declaration/plugin extensions
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug

#28676 fix(nuxt): do not accept arbitrary strings for `MiddlewareKey`
  nuxt.config.ts
  packages/nuxt/src/pages/module.ts
Labels: enhancement, 3.x

#28724 docs: fix typo
  docs/2.guide/1.concepts/4.server-engine.md
Labels: documentation, 3.x

#28738 fix(nuxt): do not pass listeners to custom `NuxtLink`
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug, 🔨 p3-minor

#28739 docs: update broken/redirected links
  docs/3.api/1.components/10.nuxt-picture.md
  docs/3.api/1.components/9.nuxt-img.md
  packages/schema/src/config/nitro.ts
  packages/vite/src/server.ts
Labels: documentation, 3.x

#28734 docs: capitalize text
  docs/1.getting-started/8.error-handling.md
Labels: documentation, 3.x

#28726 feat(nuxt): cache vue/nitro build outputs
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/kit/src/loader/config.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/cache.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, 🍰 p2-nice-to-have, performance, 4.x

#28743 docs: add missing `query` returned value from `useRoute()`
  docs/3.api/2.composables/use-route.md
Labels: 3.x

#28747 fix(nuxt): augment `NuxtOptions` as well as config
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor

#28753 fix(nuxt): improve error logging in import protections
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/test/import-protection.test.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#28760 fix(nuxt): cookie composable does not propogate null to all refs
  packages/nuxt/src/app/composables/cookie.ts
  test/basic.test.ts
  test/fixtures/basic/components/ComponentUsingCookie.vue
  test/fixtures/basic/composables/cookie-manager.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x, bug
