Repository nuxt/nuxt, pull requests merged in 2024-03, with the labels that each got.

#25985 docs: update VS Code settings
  docs/5.community/4.contribution.md
Labels: documentation, 3.x

#26013 docs: mention island features SFC only
  docs/2.guide/2.directory-structure/1.components.md
Labels: documentation, 3.x

#26043 docs(nuxt): improve pick and transform doc
  packages/nuxt/src/app/composables/asyncData.ts
Labels: documentation, 3.x

#26059 fix(nuxt): skip vue style blocks in unctx transform
  packages/nuxt/src/core/plugins/unctx.ts
  test/fixtures/basic/pages/styles.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#26058 fix(nuxt): pass event to `useRuntimeConfig` in Nuxt renderer
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/nuxt/src/core/runtime/nitro/paths.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, nitro, 🔨 p3-minor-bug

#26052 fix(schema): disable `typescript.shim` by default in favour of volar features
  docs/1.getting-started/2.installation.md
  nuxt.config.ts
  packages/schema/src/config/typescript.ts
Labels: 3.x, 🍰 p2-nice-to-have, schema

#26077 docs: add Nuxt Fonts to changelog
  docs/5.community/7.changelog.md
Labels: documentation, 3.x

#26081 fix(nuxt): only check if server page is prerendered on client
  packages/nuxt/src/components/runtime/server-component.ts
Labels: 3.x, bug

#26072 docs: update roadmap
  docs/5.community/6.roadmap.md
Labels: documentation, 3.x

#26089 fix(nuxt): don't refetch server components in initial html
  packages/nuxt/src/app/components/nuxt-island.ts
  test/basic.test.ts
  test/fixtures/basic/pages/random/[id].vue
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#26085 fix(nuxt): resolve `defu`/`h3` paths in type templates
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#26086 fix(nuxt): use exported `toExports` from `unimport`
  packages/nuxt/src/imports/module.ts
Labels: 3.x, bug, upstream, 🍰 p2-nice-to-have

#26068 fix(nuxt): cache-bust payloads with build id
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#26094 docs: add documentation for using layers with private repos
  docs/1.getting-started/9.layers.md
Labels: documentation, 3.x

#25548 fix(kit): correctly exclude local modules in `tsconfig.json`
  packages/kit/src/index.ts
  packages/kit/src/module/install.ts
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
Labels: types, 3.x, bug

#25037 feat(nuxt): client only page
  docs/2.guide/2.directory-structure/1.pages.md
  packages/nuxt/src/components/runtime/client-component.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/types/hooks.ts
  test/basic.test.ts
  test/fixtures/basic/pages/client-only-page/index.client.vue
  test/fixtures/basic/pages/client-only-page/normal.vue
Labels: enhancement, 3.x

#26045 feat(nuxt): add `page:view-transition:start` hook
  docs/3.api/6.advanced/1.hooks.md
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/view-transitions.client.ts
Labels: enhancement, 3.x

#25932 feat(nuxt): custom loading reset/hide delay + force `finish()`
  packages/nuxt/src/app/composables/loading-indicator.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#25798 feat(nuxt): add error event in NuxtIsland
  docs/3.api/1.components/8.nuxt-island.md
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
  test/nuxt/nuxt-island.test.ts
Labels: enhancement, 3.x

#21705 feat(nuxt): `usePreviewMode` composable
  docs/3.api/2.composables/use-preview-mode.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/preview.ts
  packages/nuxt/src/imports/presets.ts
  test/basic.test.ts
  test/fixtures/basic/pages/preview/index.vue
  test/fixtures/basic/pages/preview/with-custom-enable.vue
  test/fixtures/basic/pages/preview/with-custom-state.vue
  test/fixtures/basic/pages/preview/with-use-fetch.vue
  test/fixtures/basic/server/api/preview.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#26083 docs: add note about vue-tsc
  docs/2.guide/1.concepts/8.typescript.md
Labels: documentation, 3.x

#26118 docs: improve readme readability
  README.md
Labels: documentation, 3.x

#26120 fix(nuxt): handle external redirects from `routeRules`
  packages/nuxt/src/app/middleware/manifest-route-rule.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#26135 chore: update .npmrc
  .npmrc
Labels: 3.x, chore

#26136 docs: added `macros.pageMeta` and `typescript.esbuild` option
  docs/6.bridge/10.configuration.md
  docs/6.bridge/4.plugins-and-middleware.md
Labels: documentation, 3.x

#26139 docs: fix bracket escape on `definePageMeta` page
  docs/3.api/3.utils/define-page-meta.md
Labels: documentation, 3.x

#26151 fix(nuxt): watch custom `cookieRef` values deeply
  packages/nuxt/src/app/composables/cookie.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#26146 fix(nuxt): access prerender cache synchronously
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#26154 feat(nuxt): support async transforms for data composables
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  test/fixtures/basic-types/types.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#26158 fix(nuxt): provide typescript aliases for core packages
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/types.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  test/basic.test.ts
Labels: 3.x, bug

#26162 fix(nuxt): add more names for render function to isComponentNotCalledInSetup
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/test/treeshake-client.test.ts
Labels: 3.x, bug

#26176 perf(nuxt): treeshake server side code for island client components
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x, performance

#26172 perf(nuxt): use faster approach to check cache exists
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, performance

#26192 docs: add `app:manifest:update` hook
  docs/3.api/6.advanced/1.hooks.md
Labels: documentation, 3.x

#25043 feat(nuxt): add dedicated `#teleports` element for ssr teleports
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/app.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/nuxt-teleport.vue
  test/fixtures/basic/pages/teleport.vue
Labels: enhancement, 3.x

#26193 fix(nuxt): improved plugin annotating warnings
  packages/nuxt/src/core/app.ts
Labels: 3.x, bug

#26197 docs(nuxt): add cache.varies docs for multi-tenant use case
  docs/3.api/2.composables/use-request-url.md
Labels: documentation, 3.x

#26191 refactor(nuxt): simplify `request` computation inside `useFetch`
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, refactor

#26206 fix(nuxt): generate typed routes after pages are scanned
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#26223 feat(nuxt): enable component islands when server pages/components are present
  docs/2.guide/2.directory-structure/1.pages.md
  docs/3.api/1.components/8.nuxt-island.md
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, refactor, server components

#26230 feat(nuxt): allow auto-registration of plugins with .jsx or .tsx extensions
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/test/plugin-metadata.test.ts
Labels: enhancement, 3.x

#26204 feat(nuxt): allow generating metadata for nuxt components
  docs/3.api/5.kit/5.components.md
  packages/kit/src/components.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
  packages/schema/src/types/components.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#26163 feat(vite): handle multiple/custom public dirs
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/schema/src/config/vite.ts
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/vite.ts
  test/basic.test.ts
  test/fixtures/basic/custom-public/file.svg
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/assets-custom.vue
Labels: enhancement, 3.x, bug, vite, 🔨 p3-minor-bug, performance

#26240 docs: added modular architecture use case for Layers
  docs/1.getting-started/9.layers.md
Labels: documentation, 3.x

#26250 perf(nuxt): only update changed templates
  packages/nuxt/src/core/app.ts
  packages/schema/src/types/nuxt.ts
Labels: 3.x, performance

#26249 fix(nuxt): auto imports regeneration timing
  packages/nuxt/src/imports/module.ts
Labels: 3.x, bug

#26268 chore: update issue template config to fix nuxt 3 docs link
  .github/ISSUE_TEMPLATE/config.yml
Labels: 3.x, chore

#26276 docs: fixed typo in 5.seo-meta.md
  docs/1.getting-started/5.seo-meta.md
Labels: 3.x

#25727 fix(nuxt): respect baseUrl for client components within server components
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x, bug

#22277 fix(nuxt): update `useNuxtData` to access shared asyncData state
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#26279 docs: update 5.seo-meta.md
  docs/1.getting-started/5.seo-meta.md
Labels: documentation, 3.x

#26283 docs: removed additional variable at 7.state-management.md
  docs/1.getting-started/7.state-management.md
Labels: documentation, 3.x

#26203 fix(vite): drop name prefix for client chunk file names
  packages/vite/src/client.ts
  test/fixtures/minimal/nuxt.config.ts
Labels: 3.x, bug, vite

#26284 docs: linking to ofetch libary at 6.data-fetching.md
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#26287 feat(nuxt): pass nuxt instance to `getCachedData`
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
Labels: enhancement, 3.x, dx

#25936 feat(nuxt): pass server logs to client
  docs/3.api/6.advanced/1.hooks.md
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/dev-server-logs.client.ts
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/dev-server-logs.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/typescript.ts
Labels: enhancement, 3.x, dx, 🍰 p2-nice-to-have

#26291 fix(nuxt): don't generate separate chunk for stubs
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/types/hooks.ts
Labels: 3.x, bug, performance

#26282 fix(nuxt): use `joinRelativeURL` for build assets
  packages/nuxt/src/core/templates.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#26288 docs: section title update at 8.error-handling.md
  docs/1.getting-started/8.error-handling.md
Labels: documentation, 3.x

#26296 ci: do not cache Playwright browsers
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
Labels: 3.x, chore

#26298 test: use retryable assertion for scrollY
  test/basic.test.ts
Labels: 3.x, chore, test

#25841 feat(nuxt): add `nuxtMiddleware` route rule
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/middleware/routeRulesMiddleware.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/route-rules/middleware.vue
  test/nuxt/composables.test.ts
  test/setup-runtime.ts
  vitest.nuxt.config.ts
Labels: enhancement, 3.x

#26259 feat(nuxt): add `clear` function to async data
  docs/1.getting-started/6.data-fetching.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#26303 docs: fix code block formatting for `usePreviewMode`
  docs/3.api/2.composables/use-preview-mode.md
Labels: documentation, 3.x

#26301 docs: readability improvements at 1.auto-imports.md
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#26316 chore: include `ofetch` in `typescript.hoist` defaults
  packages/schema/src/config/typescript.ts
Labels: 3.x, chore

#26314 fix(nuxt): conditionally use `tsx` parser
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/test/plugin-metadata.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#26319 chore(nuxt): remove unused code
  packages/nuxt/src/app/components/utils.ts
Labels: 3.x, chore

#26340 fix(nuxt): handle failure creating BroadcastChannel
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#26341 fix(nuxt): don't warn when injecting client-only components
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/templates.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#26029 docs: mention `<DevOnly>` component in api section
  docs/2.guide/2.directory-structure/1.components.md
  docs/3.api/1.components/1.client-only.md
  docs/3.api/1.components/1.dev-only.md
  docs/3.api/1.components/1.nuxt-client-fallback.md
Labels: documentation, 3.x

#26190 docs: note that `@nuxt/schema` should be used by module authors
  docs/2.guide/3.going-further/10.runtime-config.md
Labels: documentation, 3.x

#25838 docs: add missing routeNameSplitter alternative example
  docs/7.migration/2.configuration.md
Labels: documentation, 3.x

#26354 fix(nuxt): prevent losing pages routes on prerender
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug

#26358 fix(nuxt): pass `undefined` name when resolving trailing slash
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#26356 fix(vite): don't fall back to `importedModules` if ssr result exists
  packages/vite/src/utils/warmup.ts
Labels: 3.x, bug, vite

#26366 fix(kit): typo in test names
  packages/kit/test/generate-types.spec.ts
Labels: 3.x, bug

#26370 fix(nuxt): handle underscores in island names
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, server components

#26389 docs: migration page typo
  docs/7.migration/2.configuration.md
Labels: documentation, 3.x

#26368 fix(nuxt): don't append new route for redirect if one exists
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/pages/param.vue
Labels: types, 3.x, bug, pages, 🔨 p3-minor-bug

#26392 fix(nuxt): ignore `navigateTo` `open` option on server side
  packages/nuxt/src/app/composables/router.ts
Labels: 3.x, bug

#26410 fix(nuxt): print errors on template error
  packages/nuxt/src/core/app.ts
Labels: 3.x, bug

#26422 fix(nuxt): don't warn about `definePageMeta` in server pages
  packages/nuxt/src/pages/runtime/composables.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#26407 fix(nuxt): pass `joinRelativeURL` to bundle renderer and share paths with nitro
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/paths.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/paths.ts
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/server.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/plugins/dynamic-base.ts
  packages/webpack/src/presets/base.ts
  test/bundle.test.ts
  vitest.config.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#26421 perf(nuxt): don't tree-shake `useServerHead` in dev
  packages/nuxt/src/head/module.ts
Labels: 3.x, performance

#26430 fix(nuxt): exclude `<srcDir>/index.html` from protection, not `rootDir`
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug, layers

#26447 docs: add shamefully hoist mention for pnpm users on example launch.json
  docs/2.guide/3.going-further/9.debugging.md
Labels: documentation, 3.x

#26386 fix(nuxt): correctly move v-if from slot to wrapper component
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, server components

#26387 fix(nuxt): move some directive to client component wrapper
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, server components

#26486 fix(nuxt): ignore fetch errors in `getLatestManifest`
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
Labels: 3.x

#26480 fix(nuxt): check vnode element instead of hydration state for islands
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, server components

#26482 docs: adjust grammar
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#26504 fix(nuxt): add build id to rendered payload url
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug

#26503 fix(nuxt): support serialising rich server logs
  packages/nuxt/src/app/plugins/dev-server-logs.ts
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/dev-server-logs.ts
Labels: 3.x, bug

#26532 docs: add contents of the layout in examples
  docs/3.api/1.components/3.nuxt-layout.md
Labels: documentation, 3.x

#26541 fix(nuxt): augment `GlobalComponents` in multiple vue modules
  packages/nuxt/src/components/templates.ts
  packages/schema/src/config/typescript.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#26546 refactor(nuxt): ensure `navigateTo` is more concise on server side
  packages/nuxt/src/app/composables/router.ts
Labels: 3.x, refactor

#26547 docs: add a note for prerenderRoutes when used in dynamic routes
  docs/3.api/3.utils/prerender-routes.md
Labels: documentation, 3.x

#26562 chore: improve pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3.x, chore

#26569 perf(nuxt): reduce nuxt island payload
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: 3.x, performance

#26564 docs: fix app-config merging strategy note
  docs/2.guide/2.directory-structure/3.app-config.md
Labels: documentation, 3.x

#26558 refactor(nuxt): simplify `runtimeConfig` initialization of client side
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, refactor
