Repository nuxt/nuxt, pull requests merged in 2024-11, with the labels that each got.

#29713 fix(nuxt): remove Vue compiler hint from auto import
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: 3.x, bug

#29708 docs: add props to special metadata
  docs/2.guide/2.directory-structure/1.pages.md
Labels: documentation, 3.x

#29756 docs: add type casting of api plugin to custom-usefetch documentation
  docs/2.guide/4.recipes/3.custom-usefetch.md
Labels: 3.x

#29755 docs: remove tip comparing `useFetch` to `useAsyncData(url, () => $fetch(url))`
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#28682 feat(schema,nuxt): add `shared` folder to alias and auto-imports
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/test/import-protection.test.ts
  packages/schema/src/config/common.ts
  packages/vite/src/server.ts
  packages/vite/src/utils/external.ts
  packages/vite/src/vite-node.ts
  packages/webpack/src/configs/server.ts
Labels: enhancement, 4.x

#28160 feat(nuxt): add a plugin that triggers an immediate reload on chunkError & manifest update
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/app/plugins/chunk-reload-immediate.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x

#28909 docs(configuration): add --envName flag
  docs/1.getting-started/3.configuration.md
Labels: documentation, 3.x

#29741 feat(nuxt): add `useRuntimeHook` composable
  docs/3.api/2.composables/use-runtime-hook.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/runtime-hook.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/imports/presets.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#29683 fix(nuxt): definePageMeta props set true
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
Labels: 3.x, bug

#29768 docs(auto-imports): capitalize title
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#29775 docs: fix rou3 link in nitro.js
  packages/schema/src/config/nitro.ts
Labels: documentation, 3.x

#29780 fix(nuxt): update nitropack preset directory
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: 3.x, bug

#29792 docs: fix tip formatting
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#29794 docs: add link to h3 blogpost
  docs/2.guide/2.directory-structure/1.server.md
Labels: 3.x, bug

#29793 fix(nuxt,kit): getNuxtModuleVersion not returning version
  packages/kit/src/module/compatibility.ts
Labels: 3.x, bug

#29799 fix(kit): use `mlly` to resolve module paths to avoid cjs fallback
  packages/kit/src/module/install.ts
Labels: 3.x, bug

#29806 fix(webpack,rspack): add adapter for webpack-dev-middleware
  packages/webpack/src/webpack.ts
Labels: 3.x, bug

#29809 fix(nuxt): remove null-byte prefix for virtual files
  packages/nuxt/src/core/plugins/virtual.ts
Labels: 3.x, bug

#29812 docs: remove outdated cloudflare tip (auto minify deprecated)
  docs/1.getting-started/10.deployment.md
Labels: 3.x

#29810 refactor(nuxt): delete redundant type
  packages/nuxt/src/pages/module.ts
Labels: 3.x, refactor

#29823 fix(rspack): rspack builder usage without installing webpack
  packages/rspack/builder.mjs
  packages/rspack/package.json
  packages/webpack/builder.d.ts
  packages/webpack/builder.mjs
  packages/webpack/package.json
  packages/webpack/src/presets/base.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#29869 fix(nuxt): assign default name to component without setup
  packages/nuxt/src/components/plugins/component-names.ts
Labels: 3.x, bug

#29876 chore: remove unused imports and update eslint config
  eslint.config.mjs
  packages/nuxt/src/core/cache.ts
  packages/nuxt/src/core/external-config-files.ts
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x

#29913 docs: add information about islands directory
  docs/3.api/1.components/8.nuxt-island.md
Labels: documentation, 3.x

#29910 docs: fix typo in composable name
  docs/3.api/2.composables/use-nuxt-data.md
Labels: 3.x

#29906 docs(roadmap): rename @nuxt/auth to @nuxt/auth-utils
  docs/5.community/6.roadmap.md
Labels: documentation, 3.x

#29938 docs: capitalize text
  docs/1.getting-started/3.views.md
Labels: documentation, 3.x

#29930 docs: typo in use-seo-meta.md
  docs/3.api/2.composables/use-seo-meta.md
Labels: 3.x, bug

#29895 fix: #29894 addTemplate should consider the entire path
  packages/kit/src/template.ts
Labels: 3.x, bug

#29955 fix(kit): resolve module paths before appending subpaths
  packages/kit/src/module/install.ts
Labels: 3.x, bug

#29954 fix(nuxt): recompile templates on `change` events
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/imports/module.ts
Labels: 3.x, bug, 🔨 p3-minor

#29956 fix(nuxt): do not include `<NuxtWelcome>` when building
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug, server components

#29957 refactor(nuxt): define layouts as async vue components
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/core/templates.ts
Labels: 3.x, refactor, 🍰 p2-nice-to-have, performance

#29969 fix(nuxt): allow scanning metadata from multiple files with same route
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, bug, 🔨 p3-minor

#29975 fix(nuxt): do not disallow importing nitro dependencies
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: 3.x, bug, ❗ p4-important

#29845 docs: update getting started to include WebStorm
  docs/1.getting-started/2.installation.md
Labels: documentation, 3.x

#30029 chore: move composable-keys into core
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/composable-keys.ts
  packages/nuxt/src/core/utils/plugins.ts
  packages/nuxt/test/composable-keys.test.ts
  packages/vite/src/utils/index.ts
  packages/vite/src/vite.ts
  packages/webpack/src/webpack.ts
Labels: 3.x, chore

#30031 docs: remove extra new line in frontmatter
  docs/3.api/2.composables/on-prehydrate.md
Labels: documentation, 3.x

#30043 fix: remove unused dependencies and tidy project
  knip.json
  nuxt.config.ts
  package.json
  packages/kit/package.json
  packages/kit/src/template.ts
  packages/nuxt/package.json
  packages/rspack/package.json
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/ui-templates/package.json
  packages/vite/package.json
  packages/vite/src/vite-node.ts
  packages/webpack/package.json
  pnpm-lock.yaml
  test/fixtures/basic/package.json
Labels: 3.x, bug

#29980 feat(kit): allow module defaults to be async
  packages/kit/src/module/define.ts
  packages/schema/src/types/module.ts
Labels: enhancement, 3.x

#29819 feat(nuxt): add new types to vue preset
  packages/nuxt/src/imports/presets.ts
Labels: enhancement, 3.x

#30012 docs: update 8.typescript.md
  docs/2.guide/1.concepts/8.typescript.md
Labels: 3.x

#30006 docs: update use-fetch.md
  docs/3.api/2.composables/use-fetch.md
Labels: 3.x

#30002 docs: remove duplicate part in 4.assets.md
  docs/1.getting-started/4.assets.md
Labels: documentation, 3.x

#30015 feat(nuxt): experimental `extraPageMetaExtractionKeys`
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x

#30073 docs: format text case for consistency
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#29999 fix(nuxt): update `style` prop type for head components
  packages/nuxt/src/head/runtime/components.ts
Labels: 3.x, bug

#30088 refactor(nuxt): simplify and improve core plugins that parse ast
  packages/nuxt/src/components/plugins/component-names.ts
  packages/nuxt/src/components/plugins/tree-shake.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/composable-keys.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/plugins/prehydrate.ts
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/component-names.test.ts
  packages/nuxt/test/composable-keys.test.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/plugin-metadata.test.ts
  packages/nuxt/test/prehydrate.test.ts
  packages/nuxt/test/route-rules.test.ts
  packages/nuxt/test/treeshake-client.test.ts
Labels: 3.x, test
