Repository nuxt/nuxt, pull requests merged in 2024-07, with the labels that each got.

#27928 fix(nuxt): convert kebab to pascal name when loading server component
  packages/nuxt/src/components/loader.ts
  test/fixtures/basic/pages/islands.vue
Labels: 3.x

#27934 docs: more accurate async data warning (#27874)
  packages/nuxt/src/app/composables/asyncData.ts
Labels: documentation, 3.x

#27933 docs: warn about ref unwrapping when auto-importing `ref`s
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#27939 chore(deps): bump nitro-nightly version
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  pnpm-lock.yaml
Labels: 3.x, chore, 4.x

#27936 fix(nuxt): allow configuring server components in modules
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/app.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#27889 perf(nuxt)!: return island earlier in renderer
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, performance, server components

#27940 fix(vite): omit css `?raw` from head when in dev mode
  packages/vite/src/manifest.ts
  packages/vite/src/vite-node.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#27955 fix(nuxt): seed crawler when prerendering pages
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, 4.x

#27965 fix(nuxt): improve dx around compatibility date prompt
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, dx, bug, nitro

#27963 perf(vite): start warmups after nitro build
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
Labels: 3.x, dx, bug, vite, performance

#27971 perf(vite): avoid an extra resolve call for every `resolveId` in layers
  packages/vite/src/vite.ts
Labels: 3.x, performance, layers, 4.x

#27957 perf(vite): don't write stub manifest for legacy bundler
  packages/vite/src/manifest.ts
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
Labels: 3.x, vite, performance, 4.x

#27946 refactor: replace requireModule with ESM imports in getPostcssConfig
  package.json
  packages/schema/build.config.ts
  packages/schema/src/config/postcss.ts
  packages/schema/src/types/config.ts
  packages/vite/src/css.ts
  packages/vite/src/vite.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/presets/base.ts
  packages/webpack/src/presets/nuxt.ts
  packages/webpack/src/presets/style.ts
  packages/webpack/src/utils/config.ts
  packages/webpack/src/utils/postcss.ts
  packages/webpack/src/webpack.ts
  pnpm-lock.yaml
Labels: 3.x, refactor

#27975 fix(schema): resolve public alias correctly
  packages/schema/src/config/common.ts
Labels: 3.x, bug

#27972 fix(nuxt): omit rendering payload prefetch when `noScripts`
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🔨 p3-minor, performance

#27989 docs: fix Cloudflare spelling
  docs/1.getting-started/10.deployment.md
Labels: 3.x

#27995 feat(deps): upgrade to latest versions of c12, jiti and unbuild
  package.json
  packages/kit/package.json
  packages/kit/src/internal/cjs.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/schema.ts
  packages/schema/package.json
  packages/ui-templates/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
Labels: enhancement, 3.x, 🍰 p2-nice-to-have, 4.x

#28000 docs: update example to use `nuxtApp.runWithContext`
  docs/2.guide/4.recipes/3.custom-usefetch.md
Labels: documentation, 3.x

#27998 perf(kit,nuxt,schema,vite,webpack): use explicit exports
  packages/kit/src/index.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/core/utils/index.ts
  packages/nuxt/src/index.ts
  packages/nuxt/src/pages/runtime/index.ts
  packages/schema/src/index.ts
  packages/vite/src/index.ts
  packages/webpack/src/index.ts
  test/setup-runtime.ts
Labels: 3.x, chore, 🍰 p2-nice-to-have, performance

#28008 refactor(kit,nuxt,vite,webpack)!: remove legacy require utils in favour of`jiti`
  docs/1.getting-started/12.upgrade.md
  packages/kit/index.d.ts
  packages/kit/src/index.ts
  packages/kit/src/internal/cjs.ts
  packages/kit/src/module/install.ts
  packages/kit/src/template.ts
  packages/nuxt/index.d.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/cache-driver.js
  packages/vite/package.json
  packages/vite/src/css.ts
  packages/webpack/package.json
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
Labels: 3.x, dx, refactor, performance

#27819 refactor(nuxt): remove _registeredComponents from ssrContext
  packages/nuxt/src/app/plugins/preload.server.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, refactor

#28009 chore(deps): bump nitro edge release
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  pnpm-lock.yaml
Labels: 3.x, chore

#28012 feat(kit): reimplement cjs utils using `mlly`
  docs/1.getting-started/12.upgrade.md
  packages/kit/src/index.ts
  packages/kit/src/internal/esm.ts
  packages/kit/src/loader/nuxt.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/schema.ts
  packages/webpack/src/nitro/plugins/dynamic-require.ts
Labels: enhancement, 3.x, 🔨 p3-minor

#28011 docs: remove deprecated `pending` variable from data fetching docs
  docs/1.getting-started/6.data-fetching.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  docs/3.api/2.composables/use-lazy-async-data.md
  docs/3.api/2.composables/use-lazy-fetch.md
  docs/3.api/3.utils/refresh-nuxt-data.md
Labels: documentation, 3.x

#28013 fix(kit): add back requireModule and tryRequireModule
  docs/1.getting-started/12.upgrade.md
  packages/kit/src/index.ts
  packages/kit/src/internal/esm.ts
Labels: 3.x, bug

#28024 fix(ui-templates): validate templates with `html-validate`
  packages/ui-templates/lib/render.ts
  packages/ui-templates/package.json
  packages/ui-templates/templates/welcome/index.html
  packages/ui-templates/test/__snapshots__/templates.spec.ts.snap
  packages/ui-templates/test/snapshots.spec.ts
  packages/ui-templates/test/templates.spec.ts
  pnpm-lock.yaml
Labels: 3.x, bug, 🔨 p3-minor, a11y

#28045 fix(schema): don't constrain postcss plugin options
  packages/schema/src/config/postcss.ts
Labels: 3.x, bug, 🔨 p3-minor

#28053 docs(nuxt): update 7.state-management.md
  docs/1.getting-started/7.state-management.md
Labels: documentation, 3.x

#28113 docs: deprecate pending and emphasis undefined
  docs/1.getting-started/6.data-fetching.md
  packages/nuxt/src/app/nuxt.ts
Labels: documentation, 3.x

#28108 docs: update phrasing in route announcer
  docs/3.api/1.components/12.nuxt-route-announcer.md
Labels: documentation, 3.x

#28088 fix(nuxt): solve unhead module name error
  packages/nuxt/src/head/module.ts
Labels: 3.x, bug

#28094 docs: switch to using code groups to have yarn, pnpm and bun in module guide
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#28056 docs: capitalize text
  README.md
Labels: documentation, 3.x

#28091 docs: removed a known issue from the docs Transition section
  docs/1.getting-started/5.transitions.md
Labels: documentation, 3.x

#28114 fix(nuxt): use native vue-router composables
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug

#28092 docs: update navigateTo for clarity
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/3.utils/navigate-to.md
Labels: documentation, 3.x

#28062 docs: warn about nested islands
  docs/2.guide/2.directory-structure/1.components.md
Labels: 3.x

#28125 fix: `getNuxtVersion` returning `any`
  packages/kit/src/compatibility.ts
Labels: 3.x, bug

#28131 fix(nuxt): always prerender at least one page when crawler activated
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, nitro, ❗ p4-important

#28128 docs: add info about auto-register layers in layers/ directory
  docs/1.getting-started/9.layers.md
Labels: documentation, 3.x

#28083 fix(nuxt): consider doc `scroll-padding-top` in scrollBehavior
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x, bug

#28154 fix(nuxt): only warn when `useAsyncData` returns undefined
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#28151 refactor(nuxt): useAsyncData isDefer in nuxt4
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, refactor

#28166 test(vite): add test for `typeCheck` functionality in minimal build
  packages/vite/package.json
  pnpm-lock.yaml
  renovate.json
  test/fixtures/minimal/nuxt.config.ts
Labels: 3.x, test

#28176 fix(schema): don't use `app/` as `srcDir` if it doesn't exist
  packages/nuxt/test/app.test.ts
  packages/schema/src/config/common.ts
  packages/schema/test/folder-structure.spec.ts
Labels: 3.x, bug, schema, 4.x

#28177 fix(kit): normalise `serverDir` within layers using v4 compat
  packages/kit/src/loader/config.ts
Labels: 3.x, bug, 🔨 p3-minor, 4.x

#28187 fix(nuxt): allow `getCachedData` to return undefined
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#28156 fix(nuxt): hide unhandled error messages in prod
  packages/nuxt/src/core/runtime/nitro/error.ts
Labels: 3.x, bug, nitro

#28193 fix(nuxt): use `addEventListener` to register cookie store listener
  packages/nuxt/index.d.ts
  packages/nuxt/src/app/composables/cookie.ts
  test/basic.test.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x, bug, ❗ p4-important, 4.x

#28170 fix(nuxt): merge meta properties
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug

#28027 refactor(nuxt): use errx to handle dev log traces
  packages/kit/package.json
  packages/kit/src/internal/esm.ts
  packages/nuxt/package.json
  packages/nuxt/src/app/plugins/dev-server-logs.ts
  packages/nuxt/src/core/runtime/nitro/dev-server-logs.ts
  pnpm-lock.yaml
Labels: 3.x, bug, refactor, 🔨 p3-minor

#28072 docs: codemods for migrating to Nuxt 4
  docs/1.getting-started/12.upgrade.md
Labels: 3.x

#28211 fix(nuxt): prevent duplicate `set-cookie` headers
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/app/nuxt.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x, bug, 🔨 p3-minor

#28223 docs: fix issue in cookie passing example
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#28236 docs: fix note in layers usage chapter
  docs/1.getting-started/9.layers.md
Labels: documentation, 3.x

#28247 docs: wrap use-route-announcer.md sample code in vue section
  docs/3.api/2.composables/use-route-announcer.md
Labels: documentation, 3.x

#28246 fix(nuxt): ignore definePageMeta warning for client only pages in dev
  packages/nuxt/src/components/runtime/client-component.ts
  packages/nuxt/src/pages/runtime/composables.ts
Labels: 3.x, bug

#28237 fix(kit): include types in module `dist/runtime/` in tsconfig file
  packages/kit/src/template.ts
Labels: 3.x, bug

#28249 fix(schema): fix srcDir being overriden by default value
  packages/schema/src/config/common.ts
  packages/schema/test/folder-structure.spec.ts
Labels: 3.x, bug

#28279 docs: fix codemod command typos
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#28277 docs: `bunx` -> `bun x`
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/2.installation.md
  docs/1.getting-started/9.prerendering.md
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#28259 docs: indicate what `useAsyncData` must return
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, chore

#27839 test: disable pageTransition in clientonly page
  test/basic.test.ts
  test/fixtures/basic/pages/client-only-page/index.client.vue
  test/fixtures/basic/pages/client-only-page/normal.vue
Labels: 3.x, chore

#28294 docs: add language to example schema codeblock
  packages/schema/src/config/dev.ts
Labels: 3.x, bug

#28336 docs: update link to RuntimeNuxtHooks
  docs/3.api/6.advanced/1.hooks.md
Labels: documentation, 3.x
