Repository nuxt/nuxt, pull requests merged in 2024-12, with the labels that each got.

#30087 docs: update configuration files format
  docs/1.getting-started/3.configuration.md
Labels: documentation, 3.x

#30111 docs: update links to `vite.dev`
  docs/1.getting-started/1.introduction.md
  docs/1.getting-started/3.configuration.md
  docs/1.getting-started/4.assets.md
  docs/1.getting-started/4.styling.md
  docs/2.guide/1.concepts/2.vuejs-development.md
  docs/2.guide/3.going-further/1.features.md
  docs/3.api/5.kit/14.builder.md
  docs/5.community/5.framework-contribution.md
  docs/7.migration/10.bundling.md
  packages/schema/src/config/vite.ts
  packages/schema/src/types/builder-env/vite.ts
Labels: documentation, 3.x

#30115 fix(kit,nuxt): provide `buildDir` to `normalizeTemplate`
  packages/kit/src/template.ts
  packages/nuxt/src/core/app.ts
Labels: 3.x, bug, 🔨 p3-minor

#30019 docs: improve development documentation for using the Bun runtime
  docs/1.getting-started/2.installation.md
Labels: 3.x

#30117 fix(nuxt): correct return type of `useRequestFetch`
  packages/nuxt/src/app/composables/ssr.ts
  test/fixtures/basic-types/types.ts
Labels: 3.x, bug

#30113 fix(nuxt,vite): support hmr for templates, pages and page metadata
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/vite/src/vite-node.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
  test/fixtures/hmr/components/islands/HmrComponent.vue
  test/fixtures/hmr/nuxt.config.ts
  test/fixtures/hmr/package.json
  test/fixtures/hmr/pages/index.vue
  test/fixtures/hmr/pages/page-meta.vue
  test/fixtures/hmr/pages/route-rules.vue
  test/fixtures/hmr/pages/routes/index.vue
  test/fixtures/hmr/pages/server-component.vue
  test/fixtures/hmr/tsconfig.json
  test/hmr.test.ts
  test/utils.ts
Labels: 3.x, bug

#30122 docs: add giget limitation in nuxt layers documentation
  docs/2.guide/3.going-further/7.layers.md
Labels: 3.x

#29922 feat(nuxt): add support for printing nuxt hook timing in browser devtools
  packages/nuxt/src/app/plugins/browser-devtools-timing.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#30017 perf(nuxt): preload app manifest
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/vite/src/server.ts
  packages/webpack/src/configs/server.ts
  test/bundle.test.ts
Labels: 3.x, performance

#29818 feat(nuxt): support vue directive auto-imports within unimport
  packages/nuxt/src/imports/module.ts
Labels: enhancement, 3.x

#30171 docs: added note about awaiting `useLazyFetch`
  docs/3.api/2.composables/use-lazy-fetch.md
Labels: documentation, 3.x

#30189 Minor: Add missing comma to upgrade doc - Update 12.upgrade.md
  docs/1.getting-started/12.upgrade.md
Labels: 3.x

#30192 fix(schema): fix router-options type
  packages/schema/src/types/router.ts
Labels: 3.x, bug

#30201 docs: added options and option definitions for sourcemap
  packages/schema/src/config/build.ts
Labels: documentation, 3.x

#30061 fix(nuxt): render client page directly when not hydrating
  packages/nuxt/src/components/runtime/client-component.ts
  test/nuxt/client.test.ts
Labels: 3.x, bug

#30151 fix(nuxt): useId instead of build time hash for island client component teleport
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
  packages/nuxt/test/island-transform.test.ts
  test/basic.test.ts
Labels: 3.x, bug

#30203 fix(nuxt): de-default async layout components
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug, ❗ p4-important

#30148 fix(nuxt): `nuxt` and `nuxt/app` resolutions
  packages/nuxt/app.d.ts
  packages/nuxt/package.json
  packages/nuxt/src/app/types/augments.d.ts
Labels: 3.x, bug

#30206 test: add additional attw test for built packages
  .github/workflows/ci.yml
  package.json
  packages/kit/.attw.json
  packages/kit/package.json
  packages/nuxt/.attw.json
  packages/nuxt/package.json
  packages/nuxt/src/app/components/nuxt-route-announcer.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/rspack/.attw.json
  packages/rspack/package.json
  packages/schema/.attw.json
  packages/schema/build.config.ts
  packages/schema/builder-env.d.ts
  packages/schema/package.json
  packages/schema/src/config/experimental.ts
  packages/vite/.attw.json
  packages/vite/package.json
  packages/webpack/.attw.json
  packages/webpack/package.json
  pnpm-lock.yaml
Labels: 3.x, test

#30028 refactor(nuxt): prefix all core modules with `nuxt:`
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
Labels: 3.x, chore

#29871 feat(schema): add snow effect on loading screen in winter
  packages/ui-templates/templates/loading/index.html
Labels: 3.x

#29776 fix(nuxt,schema): allow showing spa loader til after hydration
  docs/1.getting-started/12.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/spa-loader/app.vue
  test/fixtures/spa-loader/app/spa-loading-template.html
  test/fixtures/spa-loader/nuxt.config.ts
  test/fixtures/spa-loader/package.json
  test/fixtures/spa-loader/tsconfig.json
  test/spa-loader/spa-preloader-outside-disabled.test.ts
  test/spa-loader/spa-preloader-outside-enabled.test.ts
Labels: 3.x, bug

#29816 docs: first pass at the shared directory documentation
  docs/2.guide/2.directory-structure/1.shared.md
Labels: documentation, 3.x

#30230 fix(nuxt): hoist environment types
  packages/nuxt/src/core/nuxt.ts
Labels: types, 3.x, dx, bug, 🔨 p3-minor

#30251 ci: bump node v22
  .github/workflows/autofix-docs.yml
  .github/workflows/autofix.yml
  .github/workflows/benchmark.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint-monorepo.yml
Labels: 3.x, chore

#30274 docs: add a note about compatibilityVersion feature flag
  docs/1.getting-started/12.upgrade.md
  docs/2.guide/3.going-further/1.features.md
Labels: documentation, 3.x

#30277 fix(nuxt): ensure `getRouteRules` works with nitro signature
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/middleware/manifest-route-rule.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/fixtures/basic-types/types.ts
  test/nuxt/composables.test.ts
Labels: types, 3.x, bug, 🔨 p3-minor

#30292 docs: update auto-imports to advertise the scan feature
  docs/2.guide/1.concepts/1.auto-imports.md
  packages/schema/src/config/adhoc.ts
Labels: 3.x

#30241 feat(nuxt): support local functions in definePageMeta
  docs/2.guide/2.directory-structure/1.pages.md
  packages/nuxt/src/core/plugins/composable-keys.ts
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/fixture/scope-tracker.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/parse.test.ts
Labels: enhancement, 3.x

#30283 fix(nuxt): respect `replace` in middleware with `navigateTo`
  packages/nuxt/src/app/composables/router.ts
  test/bundle.test.ts
  test/nuxt/composables.test.ts
Labels: 3.x

#30199 docs: update `nuxi` command pages
  docs/3.api/4.commands/add.md
  docs/3.api/4.commands/analyze.md
  docs/3.api/4.commands/build-module.md
  docs/3.api/4.commands/build.md
  docs/3.api/4.commands/cleanup.md
  docs/3.api/4.commands/dev.md
  docs/3.api/4.commands/devtools.md
  docs/3.api/4.commands/generate.md
  docs/3.api/4.commands/info.md
  docs/3.api/4.commands/init.md
  docs/3.api/4.commands/module.md
  docs/3.api/4.commands/prepare.md
  docs/3.api/4.commands/preview.md
  docs/3.api/4.commands/typecheck.md
  docs/3.api/4.commands/upgrade.md
Labels: documentation, 3.x

#30260 feat(nuxt): add `mode: 'navigation'` to `callOnce`
  packages/nuxt/src/app/composables/once.ts
  packages/schema/src/config/build.ts
  test/basic.test.ts
  test/fixtures/basic/pages/once-nav-initial.vue
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#30297 perf(nuxt): use static `hashMode` option
  packages/nuxt/src/pages/build.d.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/plugins/prerender.server.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, performance

#30190 fix(nuxt): if href in nuxt-link starts with hash, render a tag directly
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/test/nuxt-link.test.ts
  test/mocks/router-options.ts
  vitest.config.ts
Labels: 3.x, bug

#30315 perf(vite): use vite to clear screen
  packages/vite/package.json
  packages/vite/src/utils/logger.ts
  pnpm-lock.yaml
Labels: 3.x, performance

#30314 fix(nuxt): use useId for client-fallback component uid
  packages/nuxt/src/app/components/client-fallback.client.ts
  packages/nuxt/src/app/components/client-fallback.server.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/client-fallback-auto-id.ts
Labels: 3.x, bug

#30305 perf(schema): only inline styles for vue components
  packages/schema/src/config/experimental.ts
Labels: 3.x, performance, 4.x, inline styles

#30322 docs: add bluesky
  .github/assets/bluesky.svg
  README.md
Labels: documentation, 3.x

#27287 docs: add recipe for session and authentication
  docs/2.guide/4.recipes/4.sessions-and-authentication.md
Labels: documentation, 3.x

#30324 chore: remove outdated comment
  packages/nuxt/src/app/components/client-fallback.client.ts
Labels: 3.x, chore

#30328 perf(nuxt): remove useId from composable key plugin
  packages/schema/src/config/build.ts
  test/fixtures/basic-types/types.ts
Labels: 3.x, performance

#30333 docs: fix filename for prerendering page
  docs/1.getting-started/9.prerendering.md
Labels: documentation, 3.x

#30331 docs: add spacing
  docs/2.guide/1.concepts/9.code-style.md
Labels: documentation, 3.x

#30348 fix(kit): initialize tsconfig paths in `addTemplate` if undefined
  packages/kit/src/template.ts
Labels: 3.x, bug

#30359 chore(nuxt): document div wrapper in client-only page
  packages/nuxt/src/components/runtime/client-component.ts
Labels: 3.x, chore

#30343 fix(nuxt): mark instance with empty sp array in useAsyncData
  packages/nuxt/src/app/composables/asyncData.ts
  test/basic.test.ts
  test/fixtures/basic/pages/useAsyncData/use-id.vue
Labels: 3.x, bug

#30360 fix(nuxt): use withAsyncContext from Vue on the client side
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug

#30371 fix(nuxt): update module path for defaults
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 4.x

#30381 fix(nuxt): ignore non-reference identifiers when extracting pageMeta
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug

#30380 chore: add configuration for JetBrains IDEs
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/nuxt.iml
Labels: 3.x, chore

#30408 refactor(nuxt): use consola with nuxt tag instead of console
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/external-config-files.ts
  packages/nuxt/src/core/features.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/src/utils.ts
  packages/nuxt/test/scan-components.test.ts
Labels: 3.x, refactor

#30411 perf(schema): drop unneeded (type-only) schema dependencies
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/common.ts
  packages/schema/src/config/vite.ts
  pnpm-lock.yaml
Labels: 3.x, schema, performance

#30413 docs: fix typos
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/4.recipes/4.sessions-and-authentication.md
Labels: documentation, 3.x

#30409 perf(rspack,webpack): drop `lodash-es` dependency
  packages/kit/src/template.ts
  packages/rspack/package.json
  packages/webpack/package.json
  packages/webpack/src/presets/base.ts
  packages/webpack/src/utils/config.ts
  packages/webpack/src/webpack.ts
  pnpm-lock.yaml
Labels: 3.x, webpack, performance, rspack
