Repository nuxt/nuxt, pull requests merged in 2024-02, with the labels that each got.

#25550 ci: retry flaky test when using Webpack
  test/basic.test.ts
Labels: 3.x, chore

#25569 fix(nuxt): add client flag for animationframe api
  packages/nuxt/src/app/composables/loading-indicator.ts
Labels: 3.x, bug

#25403 docs: add useGoogleAnalytics to api documentation
  docs/3.api/2.composables/use-google-analytics.md
Labels: documentation, 3.x

#25581 fix: use experimental.viewTransition value for app.viewTransition if none set
  packages/schema/src/config/app.ts
Labels: 3.x, bug

#25568 fix: remove return type of promise from refresh and execute.
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#25579 ci: simplify label PR workflow
  .github/workflows/label-pr.yml
Labels: 3.x, chore

#25580 ci: add label PR workflow
  .github/workflows/label-pr.yml
Labels: 2.x, chore

#25598 fix(nuxt): useCookie regression
  packages/nuxt/src/app/composables/cookie.ts
  test/basic.test.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x, bug

#25593 fix(nuxt): typed routes now generated during build
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug

#25610 docs: add nuxt-link defaults config in nuxt.config
  docs/3.api/1.components/4.nuxt-link.md
Labels: documentation, 3.x

#25514 perf(nuxt): invalidate `getRouteMeta` cache on page contents change
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, performance

#25614 fix(nuxt): remove key from `useId` type signature
  packages/nuxt/src/app/composables/id.ts
  test/fixtures/basic-types/types.ts
Labels: 3.x, bug

#25600 fix(nuxt): `NuxtLink` no default rel for relative external links
  docs/3.api/1.components/4.nuxt-link.md
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug

#25616 fix(nuxt): warn if `inheritAttrs: false` is set when using `useId`
  packages/nuxt/src/app/composables/id.ts
Labels: 3.x, bug

#25613 fix(nuxt): fetch island if there's no element on the vnode instance
  packages/nuxt/src/app/components/nuxt-island.ts
  test/basic.test.ts
  test/fixtures/basic/pages/islands.vue
Labels: 3.x, bug

#25628 fix(nuxt): don't check page/layout usage when redirecting
  packages/nuxt/src/app/plugins/check-if-layout-used.ts
  packages/nuxt/src/pages/runtime/plugins/check-if-page-unused.ts
Labels: 3.x, dx, bug

#25635 chore: export refreshCookie
  packages/nuxt/src/app/composables/index.ts
  test/nuxt/composables.test.ts
Labels: 3.x, chore

#25644 chore(schema): removed typo in useAsyncData section of documentation
  docs/1.getting-started/6.data-fetching.md
Labels: 3.x, chore

#25641 chore(schema): add missing closing code block
  packages/schema/src/config/experimental.ts
Labels: documentation, 3.x

#25658 fix(nuxt): allow prefetching urls with query string
  packages/nuxt/src/app/composables/payload.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#25669 docs: add quotes to clarify what site title is in example
  docs/1.getting-started/5.seo-meta.md
Labels: documentation, 3.x

#25667 fix(nuxt): remove undefined keys in route object
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, pages

#25673 fix(vite): treat `.pcss` extension as a CSS extension
  packages/vite/src/utils/index.ts
Labels: 3.x, bug

#25679 docs: enable twoslash for some code snippets
  docs/1.getting-started/2.installation.md
  docs/1.getting-started/3.configuration.md
  docs/1.getting-started/3.views.md
  docs/1.getting-started/4.assets.md
  docs/1.getting-started/4.styling.md
  docs/1.getting-started/5.routing.md
  docs/1.getting-started/5.seo-meta.md
  docs/1.getting-started/5.transitions.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/3.api/4.commands/module.md
  docs/6.bridge/4.plugins-and-middleware.md
Labels: documentation, 3.x

#25714 fix(nuxt): do not check for layout/page usage if `<ClientOnly>` present
  packages/nuxt/src/app/components/client-only.ts
Labels: 3.x, dx, bug

#25683 docs: add prepend option docs for `addComponentsDir`
  docs/3.api/5.kit/5.components.md
Labels: documentation, 3.x

#25720 docs: extend auto-scanned layer directories
  docs/2.guide/3.going-further/7.layers.md
Labels: documentation, 3.x

#25692 docs: improve wording in seo docs
  docs/1.getting-started/5.seo-meta.md
Labels: documentation, 3.x

#25731 docs: add how to debug nuxt with node inspector
  docs/2.guide/3.going-further/9.debugging.md
Labels: documentation, 3.x

#25764 fix(vite): strip query strings when generating style chunk filenames
  packages/vite/src/plugins/ssr-styles.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug, inline styles

#25752 fix(vite): optimise layer dependencies with vite
  packages/vite/src/vite.ts
Labels: 3.x, dx, bug, vite, 🔨 p3-minor-bug, layers

#25765 fix(nuxt): don't add an extra `baseURL` on server `useRequestURL`
  packages/nuxt/src/app/composables/url.ts
  test/basic.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#25766 fix(schema): use `rootDir` rather than `process.cwd` for `modulesDir`
  packages/schema/build.config.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/vite.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, schema

#25770 fix(nuxt): only warn for `useId` if there is no readable attribute
  packages/nuxt/src/app/composables/id.ts
Labels: 3.x, dx, bug, 🔨 p3-minor-bug

#25750 docs: <script setup> changed to <script setup lang="ts">
  README.md
  docs/1.getting-started/6.data-fetching.md
  docs/1.getting-started/7.state-management.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/2.directory-structure/1.public.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/2.guide/2.directory-structure/3.app-config.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  docs/3.api/2.composables/use-loading-indicator.md
  docs/3.api/2.composables/use-nuxt-data.md
  docs/3.api/2.composables/use-router.md
  docs/3.api/3.utils/call-once.md
  docs/3.api/3.utils/define-route-rules.md
Labels: documentation, 3.x

#25774 docs: fix export config
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/1.features.md
Labels: documentation, 3.x

#25783 docs: add import statement for mountSuspended
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#25786 fix(kit): don't mutate existing component entries when overriding
  packages/kit/src/components.ts
Labels: 3.x, bug, kit, 🔨 p3-minor-bug

#25788 docs: apply best practices to use-runtime-config
  docs/3.api/2.composables/use-runtime-config.md
Labels: documentation, 3.x

#25777 ci: typecheck code samples in docs
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .nuxtrc
  docs/1.getting-started/5.transitions.md
  package.json
  pnpm-lock.yaml
  test/fixtures/minimal/nuxt.config.ts
  vitest.nuxt.config.ts
Labels: documentation, 3.x

#25815 fix(nuxt): add dedupe option to useFetch composable
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, bug

#25813 fix(nuxt): skip browser cache when fetching latest manifest
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
Labels: 3.x, bug

#25822 fix(nuxt): in dev mode, don't add links to `css` files that have been inlined
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
  test/fixtures/basic/assets/inline-only.css
  test/fixtures/basic/pages/inline-only-css.vue
Labels: 3.x, bug

#25855 docs(nuxt): remove misleading .ts for resolve
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#25887 fix(nuxt): pass `external` prop to `navigate` fn of custom `<NuxtLink>`
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug

#25842 fix(nuxt): mark island specific components with @__PURE__
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
  packages/nuxt/src/app/components/nuxt-teleport-island-slot.ts
Labels: 3.x, bug

#25902 docs: fix incorrect wording
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: documentation, 3.x

#25817 fix(nuxt): scroll to top on page navigation when scroll-behavior: smo…
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x, bug

#25410 fix(nuxt): add missing type for `head` in `defineNuxtComponent`
  packages/nuxt/src/app/types/augments.d.ts
  test/fixtures/basic-types/types.ts
Labels: 3.x, bug

#25953 docs: mention when `useId` composable was introduced
  docs/3.api/2.composables/use-id.md
Labels: documentation, 3.x

#25647 perf: don't manipulate an empty value
  packages/kit/src/compatibility.ts
  packages/kit/src/loader/nuxt.ts
  packages/nuxt/src/app/components/nuxt-error-page.vue
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/src/head/runtime/components.ts
  packages/nuxt/src/pages/module.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/utils/warmup.ts
  test/basic.test.ts
Labels: 3.x, performance

#24954 feat(nuxt): server-only pages
  docs/2.guide/2.directory-structure/1.pages.md
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
  packages/schema/src/types/hooks.ts
  test/basic.test.ts
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/server-page.server.vue
Labels: enhancement, 3.x

#25965 fix(nuxt): strip extensions only for existing files
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/utils.ts
Labels: 3.x, refactor

#25969 fix(nuxt): produce valid css selector from `useId`
  packages/nuxt/src/app/composables/id.ts
Labels: 3.x, chore

#25924 fix(schema): add vueCompilerOptions property to TSConfig in defineNuxtConfig
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/typescript.ts
  packages/schema/src/types/hooks.ts
  pnpm-lock.yaml
Labels: 3.x, bug
