Repository nuxt/nuxt, pull requests merged in 2024-01, with the labels that each got.

#24957 fix(kit): incorrect error message on load nuxt module instance
  packages/kit/src/module/install.ts
Labels: 3.x

#24961 docs: warn about hydration issue with anchor
  docs/3.api/2.composables/use-route.md
Labels: 3.x

#24985 test: fix tests for vue 3.4.3
  test/basic.test.ts
Labels: 3.x

#24986 fix(nuxt): workaround deep watch due to vue 3.4.2
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x

#24990 docs: add callouts for `readValidatedBody` and `getValidatedQuery`
  docs/2.guide/2.directory-structure/1.server.md
Labels: 3.x

#24935 fix(nuxt): don't show transition on initial page load
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/pages/module.ts
Labels: 3.x

#25003 docs: add missing imports for nitro examples
  docs/3.api/5.kit/11.nitro.md
Labels: 3.x

#25007 fix(nuxt): clone cookie to detect changes within object
  packages/nuxt/src/app/composables/cookie.ts
  test/basic.test.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#25008 fix(nuxt): do not warn about missing layouts on error page
  packages/nuxt/src/app/plugins/check-if-layout-used.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#25010 fix(nuxt): ignore plugins typed as `any` when inferring injections
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#25009 fix(nuxt): reuse intermediate setup state in `<ClientOnly>`
  packages/nuxt/src/app/components/client-only.ts
  test/fixtures/basic/components/ClientWrapped.client.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#24993 docs: add an example of provide in object syntax plugins
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: documentation, 3.x

#25015 fix(nuxt): warn when scanning layout/middleware without name
  packages/nuxt/src/core/app.ts
  packages/nuxt/test/app.test.ts
Labels: 3.x, bug

#25026 fix(nuxt): wrap `currentRoute` in a `Ref` when not using `vue-router`
  packages/nuxt/src/app/plugins/router.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#24888 perf(nuxt): ensure `renderHTMLDocument` return more compact result
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x

#25057 docs: add callout for `getValidatedRouterParams`
  docs/2.guide/2.directory-structure/1.server.md
Labels: 3.x

#25054 docs: add documentation about lost reactivity from provide
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: 3.x

#24931 fix(nuxt): stop loading indicator if page keys are the same
  packages/nuxt/src/pages/runtime/page.ts
Labels: 3.x

#25067 refactor(nuxt): remove old reference to `nuxt-config-schema`
  packages/nuxt/src/core/schema.ts
Labels: 3.x

#25090 docs: fix incorrect nuxt image roadmap/discussion link
  docs/5.community/6.roadmap.md
Labels: 3.x

#25100 docs: fix typo
  docs/1.getting-started/10.deployment.md
Labels: 3.x

#24953 perf(nuxt): prefer iterating rather than `Object.fromEntries`
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/runtime/components.ts
  packages/vite/src/plugins/composable-keys.ts
Labels: 3.x

#25127 docs: fix typo
  docs/3.api/3.utils/$fetch.md
Labels: 3.x

#25148 fix(nuxt): add script block if there's none before island transformation
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x

#25109 chore(kit): improve types for addTemplate
  packages/kit/src/internal/template.ts
  packages/kit/src/template.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/types/nuxt.ts
Labels: 3.x

#25162 fix(nuxt): apply more import protections for nitro runtime
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/test/import-protection.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#25195 fix(nuxt): fix inconsistent `pages/*` file scanning order
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, bug

#25197 fix: check for layout after nextTick
  packages/nuxt/src/app/plugins/check-if-layout-used.ts
Labels: 3.x, bug

#25209 docs: remove invalid command alias
  docs/3.api/4.commands/cleanup.md
  docs/3.api/4.commands/init.md
  docs/3.api/4.commands/preview.md
Labels: 3.x

#25211 docs: add log-level desc
  docs/3.api/4.commands/build.md
Labels: 3.x

#25213 fix(nuxt): control nitro log level with nuxt options
  packages/nuxt/src/core/nitro.ts
Labels: 3.x

#25222 fix(nuxt): await async payload revivers
  packages/nuxt/src/app/composables/payload.ts
Labels: 3.x

#25224 docs: added "immediate: false" in the not immediate example
  docs/1.getting-started/6.data-fetching.md
Labels: 3.x

#25174 chore: use nuxt.new URLs in issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: 3.x

#25144 docs: mention `.global.vue` filename for global components
  docs/2.guide/2.directory-structure/1.components.md
Labels: 3.x

#23731 docs: clarify reactivity in composables directory
  docs/2.guide/2.directory-structure/1.composables.md
Labels: documentation, 3.x

#24955 chore: remove lagon
  docs/1.getting-started/8.server.md
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#24976 docs: add eslint setup guide
  docs/2.guide/1.concepts/9.code-style.md
Labels: documentation, 3.x

#25219 fix(nuxt): render user-inserted links in island responses
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/bundle.test.ts
Labels: 3.x, bug, server components

#25073 docs: add information on using a custom regexp in `definePageMeta`
  docs/3.api/3.utils/define-page-meta.md
Labels: documentation, 3.x

#25190 refactor(nuxt): refactor `NuxtIslandResponse` and improve nuxt-island render mechanism
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-teleport-island-client.ts
  packages/nuxt/src/app/components/nuxt-teleport-island-slot.ts
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/test/islandTransform.test.ts
  test/basic.test.ts
Labels: 3.x, server components

#25232 refactor(nuxt): rename to `data-island-component`
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/test/islandTransform.test.ts
  test/basic.test.ts
Labels: 3.x

#25243 fix(nuxt): render stylesheets in dev for non-islands
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, ❗ p4-important

#25238 docs: corrects variable name used in comment
  docs/1.getting-started/6.data-fetching.md
Labels: 3.x

#25248 docs: deleted an extra character
  docs/2.guide/1.concepts/9.code-style.md
Labels: 3.x

#25245 fix(nuxt): check for uid before replacing data-island-uid attribute in island
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x

#22947 test: add separate suspense test suite
  package.json
  pnpm-lock.yaml
  test/fixtures/suspense/app.vue
  test/fixtures/suspense/nuxt.config.ts
  test/fixtures/suspense/package.json
  test/fixtures/suspense/pages/index.vue
  test/fixtures/suspense/pages/target.vue
  test/fixtures/suspense/tsconfig.json
  test/prepare.ts
  test/suspense.test.ts
Labels: 3.x

#25255 fix(nuxt): inability to update same useCookie with same initial value
  packages/nuxt/src/app/composables/cookie.ts
  test/basic.test.ts
  test/fixtures/basic/pages/cookies.vue
Labels: 3.x

#25265 chore: fix typo
  packages/nuxt/src/core/plugins/import-protection.ts
Labels: 3.x

#22292 fix(nuxt): disable View Transitions when `prefers-reduced-motion: reduce`
  packages/nuxt/src/app/plugins/view-transitions.client.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug

#24894 feat(nuxt): add experimental sharedPrerenderData option
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, nitro, performance

#25266 fix(nuxt): create second declaration file with correct node16 imports
  packages/nuxt/package.json
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/types.d.mts
Labels: 3.x

#24837 feat(schema): default to `bundler` module resolution
  packages/schema/src/config/experimental.ts
Labels: enhancement, types, 3.x

#24250 docs: update note about auto-installing layer deps with git sources
  docs/2.guide/3.going-further/7.layers.md
Labels: documentation, 3.x

#25071 feat(nuxt): warn when using data-fetching composables outside setup/plugin
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
Labels: enhancement, 3.x

#24922 feat(nuxt): add `pages:routerOptions` hook
  docs/3.api/6.advanced/1.hooks.md
  packages/nuxt/src/pages/module.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x

#25028 feat: experimental Node.js imports compatibility for client-side
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/experimental.ts
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/webpack/package.json
  packages/webpack/src/configs/client.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/node-compat.vue
Labels: enhancement, 3.x

#25296 fix(nuxt): make slot response fallback property undefineable
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: 3.x

#25306 chore: remove reference to "experimental" `defineModel`
  docs/1.getting-started/3.configuration.md
  packages/schema/src/config/app.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/config/webpack.ts
Labels: 3.x

#25326 docs: fix typo
  docs/1.getting-started/8.server.md
Labels: 3.x

#25086 docs(nuxt): add `@since` annotations to exported composables
  packages/nuxt/src/app/composables/asyncContext.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/chunk.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/composables/hydrate.ts
  packages/nuxt/src/app/composables/loading-indicator.ts
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/once.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/composables/ready.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/composables/state.ts
  packages/nuxt/src/app/composables/url.ts
Labels: 3.x

#25329 fix(vite): pass `hidden` sourcemap values to vite
  packages/vite/src/client.ts
  packages/vite/src/server.ts
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#25286 fix(nuxt): fix lazy import of named components
  packages/nuxt/src/components/loader.ts
  test/basic.test.ts
  test/fixtures/basic/modules/lazy-import-components/index.ts
  test/fixtures/basic/modules/lazy-import-components/runtime/components.ts
  test/fixtures/basic/pages/lazy-import-components/index.vue
Labels: 3.x

#25337 refactor: remove currentRoute non-ref deprecation warning
  packages/nuxt/src/app/plugins/router.ts
Labels: 3.x

#25334 fix(nuxt): deprecate boolean values for `dedupe`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x

#25282 fix(nuxt): fix import path of named components
  packages/nuxt/src/components/loader.ts
  test/basic.test.ts
  test/fixtures/basic/modules/import-components/index.ts
  test/fixtures/basic/modules/import-components/runtime/components.ts
  test/fixtures/basic/pages/import-components/index.vue
Labels: 3.x

#25354 ci: only release from main repo
  .github/workflows/ci.yml
Labels: 3.x

#25346 test(nuxt): test data-island-uid replacement
  test/nuxt/nuxt-island.test.ts
Labels: 3.x

#25347 test: remove miswritten test
  test/basic.test.ts
Labels: 3.x

#25318 fix(nuxt): load plugin that depends on loaded and unloaded plugins
  packages/nuxt/src/app/nuxt.ts
  test/nuxt/plugin.test.ts
Labels: 3.x

#25381 fix(nuxt): preserve `instance.attrs` object in client-only components
  packages/nuxt/src/app/components/client-only.ts
  test/nuxt/client.test.ts
Labels: 3.x

#25389 fix(nuxt): stop tracking suspense resolution if error in page/layout
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/app/components/nuxt-root.vue
  packages/nuxt/src/pages/runtime/page.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, suspense

#25320 docs: add documentation for the error.vue file
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/2.directory-structure/3.error.md
Labels: documentation, 3.x

#25396 docs: add explanation about layout usage in error.vue
  docs/2.guide/2.directory-structure/3.error.md
Labels: 3.x

#25397 fix(nuxt): add router.options files in definite order
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#25395 test: avoid explicit timeouts
  test/basic.test.ts
Labels: 3.x, test

#25404 ci: label pull request based on type in its title
  .github/workflows/label-pr.yml
Labels: 3.x, chore

#25432 ci: wrap PR's base label into quotes in label PR workflow
  .github/workflows/label-pr.yml
Labels: 3.x, chore

#25431 fix(nuxt): on `callOnce` only run once callbacks with falsy return values
  packages/nuxt/src/app/composables/once.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#25437 ci: update extracting PR labels' names
  .github/workflows/label-pr.yml
Labels: 3.x, chore

#25464 fix(nuxt): remove nuxt-client attribute with : within template code
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x, bug

#25459 Update 10.deployment.md
  docs/1.getting-started/10.deployment.md
Labels: 3.x

#25436 docs: update nuxt.config example for rendering modes for better clarity on SWR/ISR
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#25454 docs: warn about slots to client components within islands
  docs/2.guide/2.directory-structure/1.components.md
Labels: documentation, 3.x

#25409 fix(nuxt): add runtime check to filter plugins in `dependsOn`
  packages/nuxt/src/app/nuxt.ts
  test/nuxt/plugin.test.ts
Labels: 3.x, bug

#25468 docs: updated addPluginTemplate example to add filename property
  docs/3.api/5.kit/9.plugins.md
Labels: documentation, 3.x

#25398 refactor(nuxt): replace Nuxt payload's error type with NuxtError
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/2.directory-structure/3.error.md
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x

#25475 ci: skip adding PR labels if there are none to add
  .github/workflows/label-pr.yml
Labels: 3.x, chore

#25455 fix(vite): extract styles for shared chunks
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/utils/index.ts
  test/basic.test.ts
  test/fixtures/basic/components/ServerOnlyComponent.server.vue
  test/fixtures/basic/components/ServerOnlyComponentChild.vue
  test/fixtures/basic/components/SharedComponent.vue
  test/fixtures/basic/pages/styles.vue
  test/fixtures/basic/pages/vueuse-head.vue
Labels: 3.x, bug, vite, 🔨 p3-minor-bug

#25198 feat(nuxt): `refreshCookie` util and experimental `cookieStore ` support
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/3.api/3.utils/refresh-cookie.md
  packages/nuxt/index.d.ts
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic/pages/cookies.vue
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#25391 fix(nuxt): avoid `vue-router` warning with routeRule redirect
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/component-stub.ts
Labels: 3.x, dx, bug, pages, 🔨 p3-minor-bug

#24746 perf(vite): rework endsWith to direct index
  packages/vite/src/plugins/composable-keys.ts
Labels: 3.x, performance

#25480 fix(nuxt): improve return type of `useRequestEvent`
  docs/1.getting-started/6.data-fetching.md
  docs/3.api/2.composables/use-request-event.md
  docs/3.api/3.utils/set-response-status.md
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/cookie.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/composables/url.ts
  test/fixtures/basic-types/modules/runtime/page.vue
  test/fixtures/basic/components/islands/LongAsyncComponent.vue
  test/fixtures/basic/modules/runtime/page.vue
  test/fixtures/basic/plugins/server-only.server.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#25440 fix(nuxt): match signature for nitro + nuxt `useRuntimeConfig` composables
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x

#25264 feat(nuxt): controllable view transition
  docs/1.getting-started/5.transitions.md
  docs/3.api/3.utils/define-page-meta.md
  packages/nuxt/src/app/plugins/view-transitions.client.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/app.ts
  packages/schema/src/types/config.ts
Labels: 3.x

#25483 fix(nuxt): prevent initial scroll jump when loading page
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug

#25210 feat(nuxt): experimentally extract route metadata at build time
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, pages, 🍰 p2-nice-to-have

#25509 fix(nuxt): ensure later items in `pages:routerOptions` hook override earlier ones
  docs/2.guide/3.going-further/8.custom-routing.md
  docs/3.api/6.advanced/1.hooks.md
  packages/nuxt/src/pages/module.ts
  packages/schema/src/types/hooks.ts
  test/fixtures/basic/extends/node_modules/foo/middleware/override.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#25523 docs: correct typo
  docs/2.guide/2.directory-structure/1.layouts.md
Labels: documentation, 3.x

#23546 docs: add the Nuxt context section for normalized context-only composable wording
  docs/2.guide/3.going-further/6.nuxt-app.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-cookie.md
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/2.composables/use-request-event.md
  docs/3.api/3.utils/navigate-to.md
  docs/3.api/3.utils/prerender-routes.md
  docs/3.api/3.utils/set-page-layout.md
  docs/3.api/3.utils/set-response-status.md
  docs/3.api/3.utils/show-error.md
Labels: documentation, 3.x

#25515 fix(nuxt): route meta serialization
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug

#25527 ci: fix playwright cache
  .github/workflows/ci.yml
Labels: 3.x, chore

#25536 ci: retry flaky test when running in Windows with Webpack
  test/basic.test.ts
Labels: 3.x, chore

#25543 ci: retry flaky test when running in Windows with Webpack
  test/basic.test.ts
Labels: 3.x, chore
