Repository nuxt/nuxt, pull requests merged in 2024-06, with the labels that each got.

#27430 build(ui-templates): directly copy templates on build
  packages/nuxt/.gitignore
  packages/nuxt/src/app/components/error-404.vue
  packages/nuxt/src/app/components/error-500.vue
  packages/nuxt/src/app/components/error-dev.vue
  packages/nuxt/src/app/components/welcome.vue
  packages/nuxt/src/core/runtime/nitro/error-500.ts
  packages/nuxt/src/core/runtime/nitro/error-dev.ts
  packages/ui-templates/lib/render.ts
Labels: 3.x

#27446 chore: build ui-templates when stubbing projects
  package.json
Labels: 3.x, chore

#27422 docs: added recipes to consume SSE via POST req
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#27426 docs: add spa mode section in rendering
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#27468 test: don't register promise in external nav
  test/e2e/basic.browser.test.js
Labels: 2.x, test

#27472 docs: add external parameter behavior navigateTo
  docs/3.api/3.utils/navigate-to.md
Labels: documentation, 3.x

#27441 fix(nuxt): handle errors loading app manifest
  packages/nuxt/src/app/composables/manifest.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#27475 perf(nuxt): deduplicate string modules to install
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, dx, performance

#27478 fix(schema): exclude non-serialisable types from `app` options
  packages/schema/src/types/config.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, dx, bug

#27480 fix(nuxt): deduplicate `app.head` arrays
  packages/nuxt/src/core/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/extends/bar/nuxt.config.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#27324 feat: make checking for outdated interval configurable
  packages/nuxt/src/app/plugins/check-outdated-build.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x

#26441 feat(nuxt): warn when accessing private runtimeConfig on client
  packages/nuxt/src/app/nuxt.ts
Labels: enhancement, 3.x

#27293 chore: improve types in tests
  test/nuxt/composables.test.ts
  test/nuxt/nuxt-island.test.ts
  test/nuxt/plugin.test.ts
  test/nuxt/tsconfig.json
  tsconfig.json
Labels: 3.x, chore

#27481 docs: add note about middleware re-running for error pages
  docs/1.getting-started/8.error-handling.md
  docs/2.guide/2.directory-structure/1.middleware.md
Labels: documentation, 3.x

#27485 fix(kit): update generated `tsconfig.json` with improved defaults
  docs/1.getting-started/6.data-fetching.md
  packages/kit/src/template.ts
  tsconfig.json
Labels: 3.x, bug

#27469 fix(nuxt): use buildAssetsDir in nuxt-teleport-island-component
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
Labels: 3.x, bug

#27483 chore: disable shamefully-hoist
  .npmrc
  package.json
  packages/nuxt/package.json
  packages/ui-templates/package.json
  packages/webpack/package.json
  playground/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/basic-types/package.json
  test/fixtures/basic/package.json
  test/fixtures/runtime-compiler/package.json
  test/fixtures/suspense/package.json
Labels: 3.x, chore

#27488 perf(webpack): decrease iteration count and improve type safety
  packages/webpack/src/plugins/vue/client.ts
  packages/webpack/src/plugins/vue/server.ts
  packages/webpack/src/plugins/vue/util.ts
  packages/webpack/src/presets/esbuild.ts
  packages/webpack/src/presets/style.ts
  packages/webpack/src/utils/postcss.ts
  packages/webpack/src/virtual-modules.ts
Labels: 3.x, webpack, chore, performance

#26744 feat(kit): provide type support for module options in `installModule`
  packages/kit/src/module/install.ts
  packages/nuxt/src/core/templates.ts
  test/fixtures/basic-types/nuxt.config.ts
Labels: 3.x, chore

#27506 fix(nuxt): ensure payload script executes before loading entry
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/bundle.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#27507 fix(kit): avoid falling back to normalized path for `loadNuxtModuleInstance`
  packages/kit/src/module/install.ts
  packages/kit/src/resolve.ts
Labels: 3.x, bug

#27134 fix(nuxt): augment pages with metadata before/after `pages:extend` hook
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/pages.test.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug

#27479 chore: bump jiti
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/ui-templates/package.json
  pnpm-lock.yaml
  renovate.json
Labels: 3.x, chore

#27449 feat(nuxt): register plugin hooks before executing plugins
  docs/2.guide/2.directory-structure/1.plugins.md
  packages/nuxt/src/app/nuxt.ts
  test/nuxt/plugin.test.ts
Labels: enhancement, 3.x

#27286 docs: add docs page for prerendering
  docs/1.getting-started/10.deployment.md
  docs/1.getting-started/9.prerendering.md
Labels: documentation, 3.x

#27511 fix(nuxt): remove `boolean` value for `dedupe` in v4 compat mode
  docs/1.getting-started/12.upgrade.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/defaults.ts
  packages/nuxt/src/core/templates.ts
  test/fixtures/basic/pages/useAsyncData/override.vue
Labels: 3.x, bug, 🔨 p3-minor-bug, 4.x

#27512 feat(nuxt,schema): add `compatibilityDate` flag for future support
  packages/nuxt/src/core/nitro.ts
  packages/schema/package.json
  packages/schema/src/config/common.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x

#27497 fix(nuxt): server components missing parent scopeId
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
  test/nuxt/nuxt-island.test.ts
Labels: 3.x, bug

#27526 chore: bump `nuxi` dependency
  package.json
  packages/nuxt/package.json
  pnpm-lock.yaml
  test/fixtures/basic-types/package.json
Labels: 3.x, chore

#27428 fix(nuxt): missing `onNuxtReady` deadline types
  packages/nuxt/src/app/composables/ready.ts
Labels: types, 3.x

#27540 fix(schema): don't narrow head string types to literals
  packages/schema/src/types/config.ts
  test/fixtures/basic-types/nuxt.config.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#27529 fix(schema): v3 app dir backwards compatibility
  packages/schema/src/config/common.ts
Labels: 3.x, bug

#27542 fix(nuxt): manually assign payload reactivity when `ssr: false`
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, ❗ p4-important

#27567 fix(nuxt): overwrite `#app/defaults` rather than augmenting
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug, 4.x

#27562 fix(nuxt): export `useRouteAnnouncer`
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/imports/presets.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#27571 fix(nuxt): close top-level watcher on nuxt 'close'
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#27564 feat(kit): add `isNuxtMajorVersion` compatibility util, deprecate `isNuxt2` and `isNuxt3`
  packages/kit/src/compatibility.ts
Labels: enhancement, 🍰 p2-nice-to-have, 4.x

#27575 docs: add warning about bridge migration with `head`
  docs/6.bridge/6.meta.md
Labels: 3.x

#27582 perf(kit): deduplicate layers before resolving config
  packages/kit/src/loader/config.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance, layers

#27487 fix(nuxt): handle more edge cases with external/custom links
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
  test/basic.test.ts
  test/fixtures/basic/pages/nuxt-link/custom-external.vue
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#27587 fix(nuxt): preserve route metadata assigned outside page
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/page-metadata.test.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/meta.vue
Labels: 3.x, bug, 🔨 p3-minor-bug

#27596 fix(nuxt): use portal to sync nitro/nuxt runtimeConfig + routeRules
  packages/nuxt/src/core/nuxt.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug, ❗ p4-important

#27600 perf(kit): various performance improvements
  packages/kit/src/internal/cjs.ts
  packages/kit/src/internal/template.ts
  packages/kit/src/loader/config.ts
  packages/kit/src/module/compatibility.ts
  packages/kit/src/pages.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
Labels: 3.x, performance

#27601 perf(vite): various performance improvements
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/vite/src/css.ts
  packages/vite/src/dev-bundler.ts
  packages/vite/src/manifest.ts
  packages/vite/src/plugins/analyze.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/server.ts
  packages/vite/src/utils/transpile.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
Labels: 3.x, performance

#27569 fix(nuxt): include build-time pages in prerender routes
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#10874 fix(vue-app): Page mount twice
  packages/vue-app/template/client.js
  test/dev/async-config.size-limit.test.js
  test/e2e/page-mount-with-layouts.test.js
  test/fixtures/page-mount-with-layouts/layouts/layout-1.vue
  test/fixtures/page-mount-with-layouts/layouts/layout-2.vue
  test/fixtures/page-mount-with-layouts/nuxt.config.js
  test/fixtures/page-mount-with-layouts/page-mount-with-layouts.test.js
  test/fixtures/page-mount-with-layouts/pages/page-1.vue
  test/fixtures/page-mount-with-layouts/pages/page-2.vue
Labels: 2.x, bug

#10193 fix(core): accidentally adding an extra comma silently disables all modules
  packages/core/src/module.js
  packages/core/test/module.test.js
Labels: 2.x, bug

#27484 fix(vue-app): Error mount twice
  packages/vue-app/template/App.js
  packages/vue-app/template/client.js
  packages/vue-app/template/components/nuxt.js
  packages/vue-app/template/index.js
  test/e2e/page-mount-with-layouts.test.js
  test/fixtures/page-mount-with-layouts/layouts/error.vue
  test/fixtures/page-mount-with-layouts/layouts/layout-error.vue
  test/fixtures/page-mount-with-layouts/pages/403.vue
Labels: 2.x, bug

#27615 docs: added docs for new `clear()` function added in 3.11
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#27599 fix(nuxt): warn when async data doesn't return a value
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#27630 fix(nuxt): replace deprecated `app.rootId` with `app.rootAttrs.id`
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#27622 fix(nuxt): add `mergeProps` import in islands transform
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, server components

#27632 fix(nuxt): cookie timeoutLength after expiration
  packages/nuxt/src/app/composables/cookie.ts
Labels: 3.x, bug

#27633 fix: not correctly matching client component when teleporting
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug

#27398 docs: add string vs object errors and tip on accessing data of server-thrown errors in create error and handling error pages
  docs/1.getting-started/8.error-handling.md
  docs/3.api/3.utils/create-error.md
Labels: documentation, 3.x

#27628 fix(schema,vite): respect `vite.cacheDir` if defined
  packages/schema/src/config/vite.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
Labels: enhancement, 3.x

#27638 perf(nuxt): don't wait for key deps check
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, performance

#27641 docs: correct Cloudflare deployment recommendations
  docs/1.getting-started/10.deployment.md
Labels: documentation, 3.x

#27637 fix(nuxt): unregister hooks the moment `close` is called
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#27640 fix(nuxt): add missing script stubs
  packages/nuxt/src/app/composables/script-stubs.ts
Labels: 3.x, bug

#27642 fix(nuxt): reduce usage of cjs utilities
  packages/kit/src/plugin.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/test/auto-imports.test.ts
  packages/nuxt/test/import-protection.test.ts
  packages/nuxt/test/scan-components.test.ts
  packages/nuxt/test/utils.ts
  packages/ui-templates/lib/dev.ts
  packages/ui-templates/lib/prerender.ts
  packages/ui-templates/vite.config.ts
  packages/vite/src/css.ts
  packages/webpack/src/utils/postcss.ts
Labels: 3.x, chore, 🍰 p2-nice-to-have

#27654 test(schema): normalize snapshot paths for windows
  packages/schema/test/folder-structure.spec.ts
Labels: 3.x, test

#27653 test(nuxt): normalize paths for windows
  packages/nuxt/test/components-transform.test.ts
Labels: 3.x, test

#27662 fix(vue-app): don't throw if we can't read `sessionStorage`
  packages/vue-app/template/utils.js
Labels: 2.x, bug, 🔨 p3-minor-bug

#27670 docs: add referral query variable to Vue School Links
  docs/2.guide/2.directory-structure/1.modules.md
  docs/2.guide/3.going-further/3.modules.md
  docs/3.api/5.kit/12.resolving.md
  docs/3.api/5.kit/4.autoimports.md
  docs/3.api/5.kit/5.components.md
  docs/3.api/5.kit/7.pages.md
  docs/3.api/5.kit/9.plugins.md
Labels: documentation, 3.x

#27675 docs: fix variable name
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#27679 docs: fix grammatical error in transitions.md
  docs/1.getting-started/5.transitions.md
Labels: documentation, 3.x

#27690 fix(nuxt): flag async data promise as cancelled only if defined
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#27691 docs: remove outdated recommendation
  docs/1.getting-started/5.seo-meta.md
Labels: documentation, 3.x

#27706 refactor(kit,nuxt)!: drop support for nuxt 2 and compiling templates with ejs
  packages/kit/build.config.ts
  packages/kit/package.json
  packages/kit/src/compatibility.ts
  packages/kit/src/index.ts
  packages/kit/src/internal/template.ts
  packages/kit/src/layout.ts
  packages/kit/src/module/define.ts
  packages/kit/src/module/install.ts
  packages/kit/src/pages.ts
  packages/nuxt/src/core/app.ts
  packages/schema/src/config/experimental.ts
  packages/ui-templates/lib/dev.ts
  packages/ui-templates/package.json
  pnpm-lock.yaml
Labels: 3.x, refactor, performance, ⚠️ breaking change, 4.x

#27707 fix(schema,vite)!: do not allow configuring vite dev bundler
  docs/1.getting-started/12.upgrade.md
  packages/schema/src/types/config.ts
  packages/vite/src/dev-bundler.ts
  packages/vite/src/server.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug, vite, ⚠️ breaking change, 4.x

#27709 fix(nuxt)!: emit absolute paths in `builder:watch` hook
  packages/nuxt/src/core/builder.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug, ⚠️ breaking change, 4.x

#27718 fix(nuxt)!: improve default `asyncData` value behaviour
  docs/1.getting-started/12.upgrade.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/defaults.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/pages/useAsyncData/immediate-remove-unmounted.vue
  test/nuxt/composables.test.ts
Labels: 3.x, bug, ⚠️ breaking change, 4.x

#27720 fix(nuxt): support hoisting types of subpath imports
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/typescript.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#27604 ci: use correct SHA calculation for release-pr action
  .github/workflows/release-pr.yml
Labels: 3.x, bug

#27742 fix(nuxt): resolve object-syntax routes with `open` in `navigateTo`
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug

#27744 docs: add `refreshCookie` on `useCookie` doc page
  docs/3.api/2.composables/use-cookie.md
Labels: documentation, 3.x

#27644 feat(nuxt): await custom `routes` function in `router.options`
  packages/nuxt/src/pages/build.d.ts
  packages/nuxt/src/pages/runtime/plugins/prerender.server.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/schema/src/types/router.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#27743 fix(nuxt): delay navigation until user input is acknowledged
  packages/nuxt/src/app/plugins/navigation-repaint.client.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/app.test.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug, pages, 🔨 p3-minor-bug, performance

#27741 fix(nuxt): resolve aliases used in nitro plugin paths
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, nitro, 🔨 p3-minor-bug

#27579 feat(kit): add `isNuxtMajorVersion` compatibility util, deprecate `isNuxt2` and `isNuxt3`
  packages/kit/src/compatibility.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#27749 fix(nuxt)!: remove old experimental options
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/runtime/plugins/vueuse-head-polyfill.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug, ⚠️ breaking change, 4.x

#27520 feat(kit,schema): improve type safety of `defineNuxtModule` options
  packages/kit/src/module/define.ts
  packages/kit/src/module/install.ts
  packages/schema/src/types/module.ts
  test/fixtures/basic-types/types.ts
Labels: enhancement, 3.x

#27787 perf(nuxt,vite): use native node fs utils rather than `fs-extra`
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/vite/package.json
  packages/vite/src/manifest.ts
  packages/vite/src/utils/index.ts
  packages/vite/src/utils/wpfs.ts
  packages/vite/src/vite-node.ts
  packages/webpack/package.json
  packages/webpack/src/plugins/vue/client.ts
  pnpm-lock.yaml
  test/prepare.ts
  test/setup.ts
Labels: 3.x, performance

#27789 fix(security): resolve bash syntax error
  .github/workflows/release-pr.yml
Labels: 3.x, bug

#27778 fix(nuxt): type refresh in exposed function for server components
  packages/nuxt/src/components/templates.ts
Labels: 3.x, bug

#27785 docs: add warning about awaiting useFetch/AsyncData in wrappers
  docs/2.guide/4.recipes/3.custom-usefetch.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#27811 test: slightly improve test reliability
  test/basic.test.ts
  test/fixtures/basic/pages/experimental/node-compat.vue
  test/runtime-compiler.test.ts
  test/suspense.test.ts
Labels: 3.x, test

#27821 fix(nuxt): extract all-literal page meta
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug

#27791 docs: update some code groups with package manager examples
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/2.installation.md
  docs/1.getting-started/4.styling.md
  docs/1.getting-started/9.prerendering.md
Labels: 3.x

#27837 fix(kit)!: support loading nuxt 4 and drop support for <=2
  packages/kit/src/loader/nuxt.ts
Labels: 3.x, bug, kit, ⚠️ breaking change, 4.x

#27829 fix(nuxt): handle external links to named route objects
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: 3.x

#27822 fix(nuxt): use URL to encode redirected URLs
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/redirect-with-encode.vue
  test/nuxt/composables.test.ts
Labels: 3.x, bug, ❗ p4-important

#27745 fix(nuxt)!: remove `__NUXT__` after hydration
  docs/1.getting-started/12.upgrade.md
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/core/templates.ts
  test/bundle.test.ts
  test/fixtures/basic/components/BreakInAsyncSetup.vue
  test/fixtures/basic/components/BreakInSetup.vue
Labels: 3.x, bug, ⚠️ breaking change, 4.x

#27859 docs: hint to use runtime config
  docs/2.guide/2.directory-structure/2.env.md
Labels: documentation, 3.x

#27838 feat(nuxt): warn when components have a name conflict
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/scan.ts
Labels: enhancement, 3.x

#27864 fix(nuxt): do not read user's package.json when looking for nuxt deps
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/load-nuxt.test.ts
Labels: 3.x, bug

#27843 chore(ui-templates): new templates branding for v4
  packages/ui-templates/lib/dev.ts
  packages/ui-templates/lib/render.ts
  packages/ui-templates/templates/error-404/index.html
  packages/ui-templates/templates/error-404/messages.json
  packages/ui-templates/templates/error-500/index.html
  packages/ui-templates/templates/error-500/messages.json
  packages/ui-templates/templates/error-dev/index.html
  packages/ui-templates/templates/error-dev/messages.json
  packages/ui-templates/templates/loading/index.html
  packages/ui-templates/templates/loading/messages.json
  packages/ui-templates/templates/messages.json
  packages/ui-templates/templates/welcome/index.html
  packages/ui-templates/templates/welcome/messages.json
  packages/ui-templates/test/__snapshots__/snapshots.spec.ts.snap
  test/bundle.test.ts
Labels: 3.x, chore

#27626 chore: improve type safety with indexed access
  packages/kit/src/components.ts
  packages/kit/src/ignore.ts
  packages/kit/src/layout.ts
  packages/kit/src/pages.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/ui-templates/lib/render.ts
  packages/vite/src/plugins/analyze.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/plugins/type-check.ts
  packages/vite/src/plugins/virtual.ts
  packages/vite/src/utils/transpile.ts
  packages/vite/src/vite.ts
  test/basic.test.ts
  test/hmr.test.ts
  test/utils.ts
Labels: 3.x, chore

#27865 fix(config): add back md4 monkey-patch if needed for wider ecosystem
  packages/config/src/options.js
  packages/config/test/config/index.test.js
  packages/config/test/options.test.js
Labels: 2.x, bug

#27871 perf(schema): use `chokidar` when a custom `srcDir` is provided
  packages/schema/src/config/experimental.ts
Labels: 3.x, performance, 4.x

#27883 docs: use internal link
  docs/2.guide/2.directory-structure/2.env.md
Labels: 3.x

#27895 docs: Broken links fixed
  docs/3.api/1.components/4.nuxt-link.md
  docs/3.api/2.composables/use-route.md
  docs/3.api/3.utils/define-nuxt-route-middleware.md
  docs/3.api/3.utils/navigate-to.md
Labels: documentation, 3.x

#27894 docs: use internal link
  docs/3.api/1.components/4.nuxt-link.md
  docs/3.api/6.advanced/1.hooks.md
  docs/6.bridge/4.plugins-and-middleware.md
Labels: documentation, 3.x

#27893 fix(nuxt): prompt to set compatibility date with latest nitro
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  playground/nuxt.config.ts
  pnpm-lock.yaml
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/minimal-types/nuxt.config.ts
  test/fixtures/minimal/nuxt.config.ts
  test/fixtures/runtime-compiler/nuxt.config.ts
  test/fixtures/suspense/nuxt.config.ts
Labels: 3.x, bug, nitro, 4.x

#27900 fix(nuxt): move app augments to core `nuxt` types
  packages/nuxt/src/app/index.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug, 4.x

#27905 feat(nuxt): ensure `prefetchComponents` be treeshake on server
  packages/nuxt/src/app/composables/preload.ts
Labels: enhancement, 3.x

#27911 docs: remove warning about type checking
  docs/2.guide/1.concepts/8.typescript.md
Labels: 3.x

#27919 docs: `compatibilityVersion` is available in the latest release.
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#27929 docs: remove duplicate server-side notice in runtime config
  docs/2.guide/3.going-further/10.runtime-config.md
Labels: documentation, 3.x
