Repository nuxt/nuxt, pull requests merged in 2024-09, with the labels that each got.

#28773 fix(nuxt): allow updating `appConfig` with non-iterable objects
  packages/nuxt/src/app/config.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#28768 perf(nuxt): use reducer array and avoid crashing if prototype is modified
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  packages/nuxt/src/core/runtime/nitro/dev-server-logs.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, bug, 🍰 p2-nice-to-have, performance

#28793 chore: tidying workflows + add sherif workflow
  .github/workflows/docs-check-links.yml
  .github/workflows/docs-deploy.yml
  .github/workflows/docs.yml
  .github/workflows/label-pr.yml
  .github/workflows/lint-sherif.yml
  .github/workflows/lint-workflows.yml
  .github/workflows/reproduire-sur-stackblitz.yml
  .github/workflows/reproduire.yml
  .github/workflows/scorecards.yml
  .github/workflows/semantic-pull-requests.yml
  .github/workflows/stackblitz-link.yml
  .github/workflows/stale.yml
  package.json
  packages/nuxt/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/fixtures/remote-provider/package.json
Labels: 3.x, chore

#28795 chore(nuxt): fix lint `console log/info` in nuxt core
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, chore

#28801 docs: fix postcss codeblock typo
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#28794 docs: include `--frozen-lockfile` when installing dependencies
  docs/5.community/5.framework-contribution.md
Labels: documentation, 3.x

#28285 refactor(nuxt): update to vue v3.5 + native `useId`
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/id.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/schema/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
  test/nuxt/composables.test.ts
Labels: 3.x, chore

#28814 feat: improve `isNuxtError()` type inference
  packages/nuxt/src/app/composables/error.ts
Labels: enhancement, 3.x

#28830 fix(schema): enable `propsDestructure` by default
  packages/schema/src/config/app.ts
Labels: 3.x, bug

#28841 fix(nuxt): ensure injected `route` has enumerable keys
  packages/nuxt/src/app/components/route-provider.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug

#28842 fix(nuxt): call client legacy `asyncData` without overriding vue instance
  packages/nuxt/src/app/composables/component.ts
Labels: 3.x, bug, 🍰 p2-nice-to-have

#28854 chore: use consola to log out compatibility info
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, chore

#28843 fix(nuxt): resolve full component paths
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/test/scan-components.test.ts
Labels: types, 3.x, bug, 🍰 p2-nice-to-have

#28864 fix(nuxt): fix ssr log querySelector
  packages/nuxt/src/app/plugins/dev-server-logs.ts
Labels: 3.x, bug

#28875 docs: add known limitations for app.config.ts
  docs/2.guide/2.directory-structure/3.app-config.md
Labels: documentation, 3.x

#28880 docs: typo fixed missing closing angle bracket
  docs/3.api/2.composables/use-async-data.md
Labels: 3.x

#28890 fix(nuxt): fix ssr log querySelector
  packages/nuxt/src/app/plugins/dev-server-logs.ts
Labels: 3.x, bug

#28895 fix(nuxt): log more context of prerendering errors
  packages/nuxt/src/core/runtime/nitro/error.ts
Labels: 3.x, dx, bug, nitro, 🍰 p2-nice-to-have

#28822 fix(nuxt): enable `injectAtEnd` for `unimport`, close #19480
  packages/nuxt/src/components/transform.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/test/auto-imports.test.ts
  packages/nuxt/test/components-transform.test.ts
Labels: 3.x, bug

#28899 fix(nuxt): ensure we process files in `buildDir` for auto-imports
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/imports/transform.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: 3.x, bug

#28901 fix(nuxt): do not accept attrs on NuxtErrorBoundary
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
Labels: 3.x, bug, 🔨 p3-minor

#28903 chore: enable `noUncheckedSideEffectImports`
  packages/nuxt/src/app/entry.ts
  packages/ui-templates/styles.ts
  tsconfig.json
Labels: 3.x, chore

#28912 perf(nuxt): remove interop default for dynamic components
  docs/2.guide/4.recipes/1.custom-routing.md
  packages/nuxt/src/app/components/nuxt-error-page.vue
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, performance

#28918 docs: update useFetch troubleshooting section
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#28923 chore: add `pending triage` to blank issues
  .github/workflows/label-issue.yml
Labels: 3.x, chore

#28925 fix(nuxt): fall back to original component `filePath`
  packages/nuxt/src/components/module.ts
Labels: 3.x, bug, 🔨 p3-minor

#28926 fix(nuxt): make `runWithContext` generic
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, bug

#28862 refactor(nuxt): use `vite:preloadError` event
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/chunk-reload.client.ts
  packages/nuxt/src/core/templates.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/chunk-error.ts
  packages/webpack/src/plugins/chunk.ts
  test/basic.test.ts
  test/fixtures/basic/pages/chunk-error.vue
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/plugins/chunk-error.ts
Labels: 3.x, bug, vite, 🔨 p3-minor

#28936 fix(kit,nuxt,schema)!: remove other support for nuxt2/bridge
  packages/kit/src/components.ts
  packages/kit/src/imports.ts
  packages/kit/src/layout.ts
  packages/kit/src/module/define.ts
  packages/kit/src/template.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/test/plugin-metadata.test.ts
  packages/schema/src/types/compatibility.ts
  test/fixtures/basic/plugins/invalid-plugin-2.ts
Labels: 3.x, bug

#28943 ci: scan source files with codeql
  .github/workflows/ci.yml
Labels: 3.x, chore

#28944 fix(nuxt): ensure component imports are injected last
  packages/nuxt/src/components/transform.ts
Labels: 3.x, bug

#28946 chore: refresh lockfile, use `htmlnano`, + pin workflow deps
  .devcontainer/Dockerfile
  .github/workflows/cache-cleanup.yml
  .github/workflows/lint-workflows.yml
  .github/workflows/release-pr.yml
  .github/workflows/stackblitz-link.yml
  package.json
  packages/ui-templates/lib/render.ts
  packages/ui-templates/package.json
  packages/ui-templates/test/__snapshots__/templates.spec.ts.snap
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x, chore

#28967 test: add regression test for using `route` in template
  test/fixtures/basic/pages/index.vue
Labels: 3.x, bug, pages, 🔨 p3-minor

#28972 docs: capitalize text
  docs/1.getting-started/3.configuration.md
Labels: documentation, 3.x

#28983 docs: fix typo
  docs/2.guide/1.concepts/4.server-engine.md
Labels: documentation, 3.x

#28993 docs: add clarity to useFetch parameter signature
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#28991 docs: change SPA to CSR in the ssr param of Rendering Route Rules
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#29016 fix(nuxt): add missing isNuxtMajorVersion export
  packages/kit/src/index.ts
Labels: 3.x, bug

#28996 fix(nuxt): correct type for `useError`
  packages/nuxt/src/app/composables/error.ts
Labels: documentation, 3.x

#29011 docs: add tip about using defineNuxtComponent instead of defineComponent
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: documentation, 3.x

#29023 fix(nuxt): simplify plugin InjectionType template conditional
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#29027 fix(nuxt): access server build from `webpack` memfs
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, webpack, ❗ p4-important

#29037 fix(nuxt): defer unsetting error handler until suspense resolves
  packages/nuxt/src/app/entry.ts
Labels: 3.x, bug, 🔨 p3-minor

#29045 Minor code comment improvement.
  docs/2.guide/1.concepts/3.rendering.md
Labels: 3.x

#29058 fix(nuxt): changed abort exceptions from string to DOMException
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x

#29060 chore: add more checks around indexed access
  packages/nuxt/src/app/components/client-fallback.server.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/plugins/prehydrate.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/src/head/runtime/components.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/app.test.ts
  packages/nuxt/test/pages.test.ts
  packages/ui-templates/lib/dev.ts
  packages/vite/src/manifest.ts
  packages/vite/src/plugins/analyze.ts
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/vite.ts
  packages/webpack/src/plugins/vue/client.ts
  test/bundle.test.ts
  tsconfig.json
Labels: 3.x, chore

#29049 fix(vite): don't force hmr protocol if `devServer.https` is disabled
  packages/vite/src/client.ts
Labels: 3.x, bug

#29068 fix(nuxt): empty nitro `buildDir` in dev mode
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug, nitro

#28873 feat(nuxt,schema): allow configuring vue `AppConfig`
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/app.ts
  packages/schema/src/types/config.ts
Labels: enhancement, 3.x

#29073 feat(kit,nuxt,vite,webpack): reimplement cjs utils using `jiti`
  packages/kit/index.d.ts
  packages/kit/src/index.ts
  packages/kit/src/internal/cjs.ts
  packages/kit/src/internal/esm.ts
  packages/kit/src/loader/nuxt.ts
  packages/kit/src/module/install.ts
  packages/kit/src/template.ts
  packages/nuxt/index.d.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/cache-driver.js
  packages/nuxt/src/core/schema.ts
  packages/vite/package.json
  packages/vite/src/css.ts
  packages/vite/src/server.ts
  packages/webpack/package.json
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/package.json
  test/fixtures/basic/postcss/plugin.ts
Labels: enhancement, 3.x

#29096 fix(kit,vite,webpack): postcss paths from each modules dir
  packages/kit/src/module/install.ts
  packages/vite/src/css.ts
  packages/webpack/src/utils/postcss.ts
Labels: 3.x, bug

#29100 docs: move custom directories note to the correct place
  docs/2.guide/2.directory-structure/1.components.md
Labels: documentation, 3.x

#29099 docs: add a section about `useRequestFetch` and `event.$fetch`
  docs/2.guide/2.directory-structure/1.server.md
  docs/3.api/2.composables/use-request-fetch.md
Labels: documentation, 3.x

#29138 fix(nuxt): add `crossorigin` attribute for stylesheets
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: 3.x, bug, 🔨 p3-minor

#29151 docs: remove specific Nuxt 4 release date
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#28745 feat(nuxt): normalise component names to match nuxt pattern
  docs/1.getting-started/12.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/1.features.md
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/client-fallback-auto-id.ts
  packages/nuxt/src/components/plugins/component-names.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/plugins/transform.ts
  packages/nuxt/src/components/plugins/tree-shake.ts
  packages/nuxt/test/components-transform.test.ts
  packages/nuxt/test/islandTransform.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, dx, ⚠️ breaking change

#29162 ci: update lychee config
  lychee.toml
Labels: 3.x

#29157 refactor(nuxt): use `addBuildPlugin` internally
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/client-fallback-auto-id.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/plugins/transform.ts
  packages/nuxt/src/components/plugins/tree-shake.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/components-transform.test.ts
  packages/nuxt/test/devonly.test.ts
  packages/nuxt/test/island-transform.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/nuxt/test/unctx-transform.test.ts
Labels: 3.x, refactor

#29172 fix(nuxt): use `routeRules` to hint pages to prerender
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/plugins/prerender.server.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/prerender/test.vue
Labels: 3.x, dx, bug, nitro, pages, 🔨 p3-minor

#29190 docs: remove redundant line newers and indentations
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/3.configuration.md
Labels: documentation, 3.x

#29185 docs: add links to Daniel Roe's short videos
  docs/1.getting-started/10.deployment.md
  docs/2.guide/2.directory-structure/1.components.md
Labels: documentation, 3.x

#29195 docs: update auto-imports.md to reflect useFetch() use correct
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: 3.x, chore

#29230 docs: add missing word
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: 3.x
