Repository nuxt/nuxt, pull requests merged in 2024-04, with the labels that each got.

#26611 docs: replace `process.*` with `import.meta.*`
  docs/1.getting-started/7.state-management.md
  docs/2.guide/2.directory-structure/1.middleware.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/2.guide/3.going-further/10.runtime-config.md
  docs/2.guide/3.going-further/8.custom-routing.md
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/5.kit/10.templates.md
  docs/3.api/5.kit/9.plugins.md
  test/fixtures/basic/pages/preview/index.vue
Labels: documentation, 3.x

#26595 fix(nuxt): suppress warning about resolve cache-driver
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, dx, bug, 🍰 p2-nice-to-have

#26554 perf(nuxt): unsubscribe from watch when scope is disposed
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#26556 fix(nuxt): handle auto-importing named components
  packages/nuxt/src/components/transform.ts
  packages/nuxt/test/components-transform.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#26563 fix(schema): update webpack `transformAssetUrls` + pass `hoistStatic` to vite plugin
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/app.ts
  packages/schema/src/config/typescript.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/config/webpack.ts
  packages/schema/src/types/config.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
Labels: 3.x, bug, vite, webpack, 🔨 p3-minor-bug

#26607 fix(schema): document use case for `typescript.shim`
  packages/schema/src/config/typescript.ts
Labels: 3.x, bug

#26519 perf(nuxt): only resolve initial route once
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug, performance

#26589 fix(nuxt): remove cast on rollup input for island chunks
  packages/nuxt/src/components/islandsTransform.ts
Labels: 3.x, bug

#26633 fix(nuxt): solve false warning when using `useRoute`
  packages/nuxt/src/app/composables/router.ts
Labels: 3.x, bug

#26644 docs: add one necessary comma to the code block in the documentation
  docs/2.guide/3.going-further/8.custom-routing.md
Labels: 3.x

#26658 chore: update `moduleResolution` to `Bundler`
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/schema/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
  tsconfig.json
Labels: 3.x, chore

#26663 docs: update Nuxt 4 scheduled release date
  docs/5.community/6.roadmap.md
Labels: documentation, 3.x

#26676 docs: remove step of installing deps in new nuxt project
  docs/1.getting-started/2.installation.md
Labels: 3.x

#26666 perf(nuxt): don't push build plugin if its option is not enabled
  packages/nuxt/src/components/module.ts
Labels: 3.x, performance

#25946 fix(nuxt): return types of `useAsyncData` when using with `getCachedData`
  packages/nuxt/src/app/composables/asyncData.ts
  test/fixtures/basic-types/types.ts
Labels: types, 3.x, bug

#26707 docs: fix plugins docs
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: documentation, 3.x

#26712 fix(nuxt): encode location header in navigateTo
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/fixtures/basic/pages/redirect-with-encode.vue
Labels: 3.x, bug

#26725 fix(nuxt): correctly remove extension from path in `hasSuffix` util
  packages/nuxt/src/core/utils/names.ts
Labels: 3.x, bug

#26759 docs: add `--preset` flag to `nuxi build`
  docs/3.api/4.commands/build.md
Labels: documentation, 3.x

#26752 docs: fix typo
  docs/2.guide/2.directory-structure/3.nuxt-config.md
Labels: documentation, 3.x

#26694 fix(nuxt): use runtime routes to hint more accurate routes to prerender
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/plugins/prerender.server.ts
Labels: 3.x, bug

#26748 docs: remove misleading reference to `useFetch`
  docs/1.getting-started/6.data-fetching.md
Labels: documentation, 3.x

#26792 docs: update the code style page
  docs/2.guide/1.concepts/9.code-style.md
Labels: documentation, 3.x

#26776 chore: update `devcontainer.json` based on documentation
  .devcontainer/devcontainer.json
Labels: 3.x, chore

#26771 docs: fix jsdoc for callWithNuxt
  packages/nuxt/src/app/nuxt.ts
Labels: documentation, 3.x

#26796 docs: add sample app.vue
  docs/1.getting-started/3.views.md
Labels: 3.x

#26775 docs: remove direct link to subheading
  README.md
Labels: documentation, 3.x

#26804 docs: fix `srcDir` description mentioning deprecated `static/` directory
  packages/schema/src/config/common.ts
Labels: documentation, 3.x

#26805 docs: improvement in nuxtPages documentation when passing parameters to child pages
  docs/2.guide/2.directory-structure/1.pages.md
Labels: 3.x

#26806 docs: documentation improvement to better understand how to use pageRef on the parent page
  docs/3.api/1.components/2.nuxt-page.md
Labels: documentation, 3.x

#25741 feat(nuxt): route announcer
  docs/3.api/1.components/12.nuxt-route-announcer.md
  docs/3.api/2.composables/use-route-announcer.md
  packages/kit/src/ignore.ts
  packages/nuxt/src/app/components/nuxt-route-announcer.ts
  packages/nuxt/src/app/composables/route-announcer.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/layouts/with-route-announcer.vue
  test/fixtures/basic/pages/route-announcer.vue
  test/fixtures/basic/pages/route-announcer2.vue
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#26829 docs: correct definePageMeta scrollToTop docs link
  docs/2.guide/2.directory-structure/1.pages.md
  docs/3.api/3.utils/define-page-meta.md
Labels: 3.x

#26845 docs: advise correct extension for vitest config
  docs/1.getting-started/11.testing.md
Labels: 3.x

#26766 docs: add deprecated to `pending`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: documentation, 3.x

#26852 docs: correct file name
  docs/2.guide/2.directory-structure/1.pages.md
Labels: documentation, 3.x

#26667 fix(kit): set tsConfig moduleDetection to 'force'
  packages/kit/src/template.ts
Labels: 3.x, bug

#26501 docs: add info about self-hosted github/gitlab instances
  docs/2.guide/3.going-further/7.layers.md
Labels: documentation, 3.x

#26680 fix(nuxt): re-initialise `nuxt._ignore` after all modules run
  packages/kit/src/ignore.test.ts
  packages/kit/src/ignore.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/types/nuxt.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#26465 feat(kit): allow finding virtual files with `resolvePath` and `findPath`
  packages/kit/src/resolve.test.ts
  packages/kit/src/resolve.ts
Labels: enhancement, 3.x

#26205 docs: add vue-test-utils specific section in getting started with Unit Testing
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#26481 docs: add a note for https call with self-signed certificate
  docs/3.api/2.composables/use-fetch.md
  docs/3.api/3.utils/$fetch.md
Labels: documentation, 3.x

#26856 docs: fix minor syntax error in 2.vuejs-development.md
  docs/2.guide/1.concepts/2.vuejs-development.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#26859 docs: fix code block formatting
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#26602 docs: add usePreviewMode explanation
  docs/3.api/2.composables/use-preview-mode.md
Labels: documentation, 3.x

#25365 docs: add `@since` annotations to exported functions
  packages/kit/src/utils.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/utils.ts
  packages/nuxt/src/pages/runtime/utils.ts
  packages/nuxt/src/utils.ts
  packages/vite/src/utils/index.ts
  packages/webpack/src/utils/index.ts
Labels: documentation, 3.x

#26818 docs: add watch example link
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#26863 perf(nuxt): remove state from nuxt island response
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: 3.x, performance

#26884 docs: add source tag
  docs/3.api/2.composables/use-id.md
  docs/3.api/2.composables/use-preview-mode.md
Labels: documentation, 3.x

#26880 fix(nuxt): assign v-for to slot in islands
  packages/nuxt/src/components/islandsTransform.ts
Labels: 3.x, bug

#26893 fix(nuxt): don't encode location header
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/fixtures/basic/pages/redirect-with-encode.vue
Labels: 3.x

#26904 fix(nuxt): check if `_scope` is active before calling `run` function (#26756)
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, bug

#26906 fix(nuxt): skip scanning component directories when `enabled` is set to `false`
  packages/nuxt/src/components/scan.ts
  packages/nuxt/test/scan-components.test.ts
  packages/schema/src/types/components.ts
Labels: 3.x, bug

#26907 chore: fix small typos
  docs/1.getting-started/11.testing.md
  docs/2.guide/1.concepts/9.code-style.md
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/test/treeshake-client.test.ts
  test/basic.test.ts
  test/fixtures/basic-types/extends/node_modules/foo/layouts/override.vue
  test/fixtures/basic-types/extends/node_modules/foo/middleware/override.ts
  test/fixtures/basic-types/extends/node_modules/foo/pages/override.vue
  test/fixtures/basic/composables/keep-alive.ts
  test/fixtures/basic/composables/override-base.ts
  test/fixtures/basic/extends/bar/composables/base.ts
  test/fixtures/basic/extends/node_modules/foo/components/ExtendsOverride.vue
  test/fixtures/basic/extends/node_modules/foo/layouts/override.vue
  test/fixtures/basic/extends/node_modules/foo/pages/override.vue
  test/fixtures/basic/pages/extends.vue
  test/fixtures/basic/pages/islands.vue
  test/fixtures/basic/pages/keepalive/keepalive-in-config.vue
  test/fixtures/basic/pages/keepalive/keepalive-in-nuxtpage-2.vue
  test/fixtures/basic/pages/keepalive/keepalive-in-nuxtpage.vue
  test/fixtures/basic/pages/keepalive/not-keepalive-in-nuxtpage.vue
  test/fixtures/basic/pages/keepalive/not-keepalive.vue
  test/nuxt/nuxt-island.test.ts
  test/nuxt/plugin.test.ts
Labels: 3.x, chore

#26912 fix(vite): inline styles for vue components with `lang="ts"`
  packages/vite/src/plugins/ssr-styles.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, inline styles

#26914 fix(generator): use maintained `html-minifier-terser`
  packages/generator/package.json
  packages/generator/src/generator.js
  packages/generator/test/generator.route.test.js
  packages/types/config/build.d.ts
  packages/types/package.json
  yarn.lock
Labels: 2.x, bug

#26949 fix(nuxt): updateAppConfig does not convert arrays into objects
  packages/nuxt/src/app/config.ts
Labels: 3.x, bug

#26965 docs: update outdated strict checks section
  docs/2.guide/1.concepts/8.typescript.md
Labels: documentation, 3.x

#26937 ci: fix potential GitHub Actions smells
  .github/workflows/reproduire-close.yml
  .github/workflows/scorecards.yml
Labels: 3.x, chore

#26928 fix(nuxt): call useState in setup function in `NuxtClientFallback`
  packages/nuxt/src/app/components/client-fallback.server.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#26984 docs: add link to one of @manniL's videos on layers
  docs/1.getting-started/9.layers.md
Labels: 3.x

#26925 feat(schema): enable opt-in to Nuxt v4 features/flags with `future. compatibilityVersion`
  .github/workflows/ci.yml
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/experimental.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/minimal-types/nuxt.config.ts
  test/fixtures/minimal/nuxt.config.ts
  test/fixtures/runtime-compiler/nuxt.config.ts
  test/fixtures/suspense/nuxt.config.ts
Labels: enhancement, 3.x, schema, 4.x
