Repository nuxt/nuxt, pull requests merged in 2024-10, with the labels that each got.

#29280 refactor: update jiti
  package.json
  packages/kit/package.json
  packages/kit/src/module/install.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/schema.ts
  packages/schema/package.json
  packages/vite/package.json
  packages/vite/src/css.ts
  packages/webpack/package.json
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
Labels: 3.x, refactor

#29281 refactor: update jiti
  package.json
  packages/kit/package.json
  packages/kit/src/module/install.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/schema.ts
  packages/schema/package.json
  packages/ui-templates/package.json
  packages/vite/package.json
  packages/vite/src/css.ts
  packages/webpack/package.json
  packages/webpack/src/utils/postcss.ts
  pnpm-lock.yaml
Labels: 3.x, refactor

#29253 docs: add example of typing custom useFetch errors
  docs/2.guide/4.recipes/3.custom-usefetch.md
Labels: documentation, 3.x

#29273 docs: add pnpm tip to LCP optimisation 💡
  docs/1.getting-started/4.styling.md
Labels: documentation, 3.x

#29321 fix(nuxt): call `link:prefetch` with absolute urls for external links
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug

#29287 fix(nuxt): error on build when required module is missing
  packages/nuxt/src/components/plugins/loader.ts
Labels: 3.x, bug, 🔨 p3-minor

#29292 docs: consistent directory structure
  docs/1.getting-started/5.routing.md
  docs/2.guide/2.directory-structure/1.components.md
  docs/2.guide/2.directory-structure/1.composables.md
  docs/2.guide/2.directory-structure/1.middleware.md
  docs/2.guide/2.directory-structure/1.pages.md
Labels: documentation, 3.x

#29118 docs: update to new `ofetch` headers for interceptors
  docs/2.guide/4.recipes/3.custom-usefetch.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#27768 docs: upgrade guide, remind people to upgrade third-party configs like tailwind.config.js
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#29320 feat(kit,schema): add `addServerTemplate` utility
  packages/kit/src/template.ts
  packages/schema/src/index.ts
  packages/schema/src/types/nuxt.ts
Labels: enhancement, 3.x, nitro, kit, 🍰 p2-nice-to-have

#29010 docs: improve explanation of ssr + data fetching
  docs/1.getting-started/6.data-fetching.md
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#29054 fix(nuxt): avoid throwing 404 error before middleware finishes
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, bug

#29165 refactor(nuxt,schema,vite,webpack): use unplugin for vfs
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/plugins/transform.ts
  packages/nuxt/src/components/plugins/tree-shake.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/nuxt/src/core/plugins/virtual.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/components-transform.test.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/pages.test.ts
  packages/schema/src/config/common.ts
  packages/vite/src/client.ts
  packages/vite/src/plugins/virtual.ts
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
  packages/vite/src/vite.ts
  packages/webpack/build.config.ts
  packages/webpack/package.json
  packages/webpack/src/presets/base.ts
  packages/webpack/src/virtual-modules.ts
  packages/webpack/src/webpack.ts
  pnpm-lock.yaml
Labels: 3.x, refactor

#29370 feat(schema): expose ConfigLayer from c12
  packages/schema/package.json
  packages/schema/src/types/config.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x

#29352 fix(nuxt): correct RouteNamedMap generation for duplicate pages
  packages/nuxt/src/pages/module.ts
  test/fixtures/basic-types/pages/param/index.vue
  test/fixtures/basic-types/types.ts
Labels: 3.x, bug

#29186 fix(nuxt): allow islands to manipulate head client-side
  packages/nuxt/src/app/components/nuxt-island.ts
  test/basic.test.ts
Labels: 3.x, bug

#29392 fix(vite): dim repeat count in logs
  packages/vite/src/utils/logger.ts
Labels: 3.x, chore

#29398 docs: add a description for `.env.test`
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#29397 docs: add section on 'updateAppConfig' in the 'app.config' page
  docs/2.guide/2.directory-structure/3.app-config.md
Labels: documentation, 3.x

#29514 chore(nuxt): remove double call to `useNuxtApp`
  packages/nuxt/src/app/composables/component.ts
Labels: 3.x, chore

#29611 docs: add example to navigateTo util
  docs/3.api/3.utils/navigate-to.md
Labels: documentation, 3.x

#29619 chore(vite): avoid redundant postcss plugins overwrite
  packages/vite/src/css.ts
Labels: 3.x, chore

#28861 feat(nuxt,schema): `pages:resolved` hook + scan meta post extend
  docs/1.getting-started/12.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/1.features.md
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/hooks.ts
  test/fixtures/basic/modules/page-extend/index.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x

#29586 feat(nuxt): add definePageMeta props
  docs/3.api/3.utils/define-page-meta.md
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/pages.test.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x

#29620 perf: extract regex patterns
  packages/kit/src/compatibility.ts
  packages/kit/src/components.ts
  packages/kit/src/layout.ts
  packages/kit/src/nitro.ts
  packages/kit/src/plugin.ts
  packages/kit/src/template.ts
  packages/kit/src/utils.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/components/utils.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/client-fallback-auto-id.ts
  packages/nuxt/src/components/plugins/component-names.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/virtual.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/core/utils/index.ts
  packages/nuxt/src/core/utils/names.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/src/pages/runtime/utils.ts
  packages/nuxt/src/pages/utils.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/utils/logger.ts
  packages/webpack/src/nitro/plugins/dynamic-require.ts
  packages/webpack/src/plugins/vue/util.ts
Labels: 3.x, performance

#29677 test: add compat code for vite v6
  test/basic.test.ts
Labels: 3.x, test

#29678 docs: update lifecycle hooks
  docs/3.api/6.advanced/1.hooks.md
Labels: documentation, 3.x
