Repository nuxt/nuxt, pull requests merged in 2024-05, with the labels that each got.

#27009 fix(nuxt): compile plugin templates last
  packages/nuxt/src/core/app.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#27005 fix: add "-D" for command, Update 4.styling.md
  docs/1.getting-started/4.styling.md
Labels: 3.x, bug

#27021 feat(nuxt,schema): inline ui-templates
  eslint.config.mjs
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/components/error-404.vue
  packages/nuxt/src/app/components/error-500.vue
  packages/nuxt/src/app/components/error-dev.vue
  packages/nuxt/src/app/components/nuxt-error-page.vue
  packages/nuxt/src/app/components/welcome.vue
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/error-500.d.ts
  packages/nuxt/src/core/runtime/nitro/error-500.js
  packages/nuxt/src/core/runtime/nitro/error-dev.d.ts
  packages/nuxt/src/core/runtime/nitro/error-dev.js
  packages/nuxt/src/core/runtime/nitro/error.ts
  packages/nuxt/src/core/templates/spa-loading-icon.d.ts
  packages/nuxt/src/core/templates/spa-loading-icon.js
  packages/nuxt/src/pages/module.ts
  packages/nuxt/test/app.test.ts
  packages/schema/package.json
  packages/schema/src/config/dev.ts
  packages/schema/src/templates/loading.d.ts
  packages/schema/src/templates/loading.js
  packages/ui-templates/lib/dev.ts
  packages/ui-templates/lib/prerender.ts
  packages/ui-templates/lib/render.ts
  packages/ui-templates/package.json
  packages/ui-templates/public
  packages/ui-templates/public/icons/MiniGem.svg
  packages/ui-templates/public/icons/book-open-solid 1.svg
  packages/ui-templates/public/icons/discord-brands 1.svg
  packages/ui-templates/public/icons/documentation-color-light.svg
  packages/ui-templates/public/icons/documentation-color.svg
  packages/ui-templates/public/icons/documentation-light.svg
  packages/ui-templates/public/icons/documentation.svg
  packages/ui-templates/public/icons/examples-color-light.svg
  packages/ui-templates/public/icons/examples-color.svg
  packages/ui-templates/public/icons/examples-light.svg
  packages/ui-templates/public/icons/examples.svg
  packages/ui-templates/public/icons/get-started-light.svg
  packages/ui-templates/public/icons/get-started.svg
  packages/ui-templates/public/icons/github-brands 1.svg
  packages/ui-templates/public/icons/logo.svg
  packages/ui-templates/public/icons/modules-color-light.svg
  packages/ui-templates/public/icons/modules-color.svg
  packages/ui-templates/public/icons/modules-light.svg
  packages/ui-templates/public/icons/modules.svg
  packages/ui-templates/public/icons/twitter-brands 1.svg
  packages/ui-templates/test/snapshots.spec.ts
  packages/ui-templates/uno.config.ts
  packages/ui-templates/vite.config.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, schema

#27020 docs: change `.eslintrc.js` in configuration to `eslint.config.js`
  docs/1.getting-started/3.configuration.md
Labels: documentation, 3.x

#27014 feat(nuxt): support configurable root/teleport element attributes
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/schema/src/config/app.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#27016 fix(nuxt): register redirect middleware before server router push
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug, ❗ p4-important

#27033 chore(ui-templates): misc improvements
  packages/ui-templates/lib/prerender.ts
  packages/ui-templates/lib/render.ts
  packages/ui-templates/test/snapshots.spec.ts
Labels: 3.x, chore

#27029 feat(nuxt,schema): support v4 folder structure
  docs/2.guide/3.going-further/1.features.md
  packages/kit/src/loader/config.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
  packages/schema/test/folder-structure.spec.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have, schema, performance, 4.x

#27043 docs: add vite plugin recipe
  docs/2.guide/4.recipes/1.custom-routing.md
  docs/2.guide/4.recipes/2.vite-plugin.md
  docs/2.guide/4.recipes/_dir.yml
Labels: documentation, 3.x

#27044 feat(nuxt): add `onUpdated` and `onUnmounted` into treeshakeable composables
  packages/schema/src/config/build.ts
Labels: enhancement, 3.x

#26976 fix(nuxt): don't overwrite scope in runWithContext if scope already exists
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  test/basic.test.ts
  test/fixtures/basic/pages/define-nuxt-component/index.vue
  test/fixtures/basic/pages/define-nuxt-component/nested/[foo].vue
Labels: 3.x, bug

#27010 feat(nuxt): prompt to install `nuxt/scripts` on usage
  packages/nuxt/src/app/composables/script-stubs.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/src/imports/transform.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#27050 feat(nuxt): make `<NuxtPage>` exposes default slots
  packages/nuxt/src/pages/runtime/page.ts
Labels: enhancement, 3.x

#27065 docs: update jsdoc for ignore-prefix to clarify ignored files
  packages/schema/src/config/common.ts
Labels: documentation, 3.x

#26989 feat(nuxt): enable `renderSSRHeadOptions` configuration for `unhead`
  docs/2.guide/3.going-further/1.features.md
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/head/module.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x

#27037 feat(nuxt): add `onPrehydrate` lifecycle hook
  docs/3.api/2.composables/on-prehydrate.md
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/prehydrate.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/config/build.ts
  test/basic.test.ts
  test/fixtures/basic/pages/composables/on-prehydrate.vue
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x, 🍰 p2-nice-to-have

#27089 fix(nuxt): deprecate `process.*` flags
  packages/nuxt/src/app/types/augments.d.ts
Labels: 3.x, bug, chore

#27093 fix(nuxt): remove unused prop
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/test/islandTransform.test.ts
Labels: 3.x, bug

#27068 feat(nuxt): allows the support of multiple shared runtime context
  docs/3.api/2.composables/use-nuxt-app.md
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/package.json
  packages/schema/src/config/common.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/namespace-nuxt-app.vue
  vitest.nuxt.config.ts
Labels: enhancement, 3.x

#27097 feat(nuxt): add #fallback to server components types
  packages/nuxt/src/components/templates.ts
  test/fixtures/basic-types/components/ServerComponent.server.vue
  test/fixtures/basic-types/types.ts
Labels: enhancement, 3.x, dx, server components

#27122 chore: update root monorepo node engine
  package.json
Labels: 3.x, refactor

#27022 feat(nuxt): check for compatible builder when installing modules
  docs/3.api/5.kit/3.compatibility.md
  packages/kit/src/compatibility.ts
  packages/schema/src/types/compatibility.ts
Labels: enhancement, 3.x

#27128 docs: add migration/testing guide for nuxt 4
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x, 4.x

#27117 feat(kit): add `useRuntimeConfig` and `updateRuntimeConfig` utils
  docs/3.api/5.kit/10.runtime-config.md
  packages/kit/package.json
  packages/kit/src/index.ts
  packages/kit/src/runtime-config.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/nitro.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, nitro, kit, 🍰 p2-nice-to-have

#27137 test: re-enable testing js payloads
  .github/workflows/ci.yml
  test/fixtures/basic/nuxt.config.ts
  test/utils.ts
Labels: 3.x, test, 🧹 p1-chore

#27138 docs: improve testing component examples
  docs/1.getting-started/11.testing.md
Labels: 3.x

#27164 docs: add `app.config.ts` to nuxt 4 testing/migration
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#27174 docs: add video links for more context
  docs/1.getting-started/11.testing.md
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/3.configuration.md
  docs/1.getting-started/6.data-fetching.md
  docs/1.getting-started/7.state-management.md
  docs/1.getting-started/8.server.md
  docs/1.getting-started/9.layers.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/2.guide/1.concepts/8.typescript.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/10.runtime-config.md
  docs/3.api/2.composables/use-fetch.md
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/2.composables/use-state.md
Labels: documentation, 3.x

#27132 feat(schema): update experimental options for v4
  docs/1.getting-started/12.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
Labels: enhancement, 3.x, 4.x

#27178 docs: update module execution order in guides and modules jsdocs
  docs/2.guide/2.directory-structure/1.modules.md
  packages/schema/src/config/common.ts
Labels: documentation, 3.x

#27212 docs: update stability comparison
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#27189 docs: better explain how environment variables work in production
  docs/2.guide/2.directory-structure/2.env.md
Labels: documentation, 3.x

#27207 chore: try enable regexp eslint rules
  eslint.config.mjs
  package.json
  packages/kit/src/compatibility.ts
  packages/kit/src/internal/template.ts
  packages/kit/src/runtime-config.ts
  packages/kit/src/template.ts
  packages/nuxt/src/components/client-fallback-auto-id.ts
  packages/nuxt/src/components/islandsTransform.ts
  packages/nuxt/src/components/loader.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/src/components/tree-shake.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/import-protection.ts
  packages/nuxt/src/core/runtime/nitro/dev-server-logs.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/core/utils/plugins.ts
  packages/nuxt/src/pages/runtime/plugins/prerender.server.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/ui-templates/lib/dev.ts
  packages/ui-templates/lib/render.ts
  packages/vite/src/plugins/composable-keys.ts
  packages/vite/src/plugins/ssr-styles.ts
  packages/vite/src/utils/index.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/plugins/vue/util.ts
  packages/webpack/src/utils/config.ts
  pnpm-lock.yaml
  scripts/update-changelog.ts
  test/basic.test.ts
  test/utils.ts
Labels: 3.x, chore

#27221 feat(nuxt): auto-register layers in `layers/` directory
  packages/kit/src/loader/config.ts
  packages/nuxt/src/core/nuxt.ts
  test/fixtures/basic/layers/bar/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
Labels: enhancement, 3.x

#27225 docs: add cache option to useFetch params
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#27208 docs: add custom useFetch recipe
  docs/2.guide/0.index.md
  docs/2.guide/4.recipes/3.custom-usefetch.md
Labels: documentation, 3.x

#27229 docs: add nuxt/scripts
  docs/5.community/6.roadmap.md
  docs/5.community/7.changelog.md
Labels: documentation, 3.x

#27214 perf(nuxt): mark payload as shallowReactive
  .github/workflows/ci.yml
  packages/nuxt/src/app/nuxt.ts
Labels: enhancement, 3.x, performance

#27176 feat(nuxt): added loading indicator error
  docs/3.api/1.components/5.nuxt-loading-indicator.md
  docs/3.api/2.composables/use-loading-indicator.md
  packages/nuxt/src/app/components/nuxt-loading-indicator.ts
  packages/nuxt/src/app/composables/loading-indicator.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#27252 fix(nuxt): pass path to `jiti` and not file URL
  packages/nuxt/src/core/schema.ts
Labels: 3.x, bug, windows, 🔨 p3-minor-bug

#27258 feat(nuxt,schema): add new `appId` option and improve chunk determinism
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/common.ts
  test/basic.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/minimal-types/types.ts
  test/nuxt/composables.test.ts
  vitest.nuxt.config.ts
Labels: enhancement, 3.x, bug, 🔨 p3-minor-bug

#27274 fix(schema): handle dev/test `buildId` in schema
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/common.ts
  vitest.nuxt.config.ts
Labels: 3.x, bug

#27271 chore: remove redundant eslint-plugin-regexp
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: 3.x, chore

#27280 fix(nuxt): encode location header
  packages/nuxt/src/app/composables/router.ts
  test/basic.test.ts
  test/fixtures/basic/pages/redirect-with-encode.vue
Labels: 3.x, bug

#27284 docs: add example of passing params to `<NuxtLink>`
  docs/3.api/1.components/4.nuxt-link.md
Labels: 3.x

#27224 feat(nuxt): check key dependencies when loading nuxt
  docs/2.guide/3.going-further/4.kit.md
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/load-nuxt.test.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, dx

#27273 docs: add additional example for setting `baseURL` and `cdnURL`
  packages/schema/src/config/app.ts
Labels: 3.x

#27294 fix(nuxt): use `undefined` rather than `null` for data fetching defaults
  docs/1.getting-started/12.upgrade.md
  packages/nuxt/index.d.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/defaults.js
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/pages/useAsyncData/immediate-remove-unmounted.vue
  test/nuxt/composables.test.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, 4.x

#27304 perf(nuxt): abort vue render when plugins throw error
  packages/nuxt/src/app/components/nuxt-root.vue
Labels: 3.x, bug, 🔨 p3-minor-bug, performance

#27306 fix(vite): ignore query/hash when resolving public assets
  packages/vite/src/plugins/public-dirs.ts
  test/fixtures/basic/pages/assets-custom.vue
Labels: 3.x, bug, vite

#27295 feat(nuxt): reset asyncData to default value when calling clear/clearNuxtData
  docs/1.getting-started/12.upgrade.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug

#27308 fix(nuxt): clear timeout when asyncData request finishes/aborts
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, bug, 🔨 p3-minor-bug

#27314 fix(nuxt): provide default data type values in nuxt/app dir
  packages/nuxt/index.d.ts
  packages/nuxt/src/app/defaults.js
  packages/nuxt/src/app/defaults.ts
Labels: 3.x, bug

#27311 fix(nuxt): add module declarations for virtual files
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#27315 docs: introduce hint and link to environment override feature (#25812)
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#27297 docs: document `partitioned` attribute of `useCookie`
  docs/3.api/2.composables/use-cookie.md
Labels: documentation, 3.x

#26668 fix(nuxt): respect `app.cdnURL` for extracted payloads
  package.json
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: enhancement, 3.x

#27305 feat(nuxt): display banner when running with `compatibilityVersion`
  packages/nuxt/src/core/nuxt.ts
Labels: enhancement, 3.x, dx, 🍰 p2-nice-to-have

#27327 fix(vite): handle runtime paths in inlined styles
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/vite.ts
  test/basic.test.ts
  test/fixtures/basic/assets/global.css
  test/fixtures/basic/public/css-only-public-asset.svg
Labels: 3.x, bug, vite, test, 🔨 p3-minor-bug, inline styles

#27309 feat(nuxt): add dev reviver for VNode and do not deduplicate server/client logs
  packages/nuxt/src/app/plugins/dev-server-logs.ts
  packages/nuxt/src/core/runtime/nitro/dev-server-logs.ts
Labels: enhancement, 3.x, dx, bug, ❗ p4-important

#27328 fix(vite): suppress warning about unresolved public assets
  packages/vite/src/plugins/public-dirs.ts
  packages/vite/src/utils/logger.ts
Labels: 3.x, dx, bug, vite, 🔨 p3-minor-bug

#27329 fix(nuxt): defer shared asyncData promises to next tick
  packages/nuxt/src/app/composables/asyncData.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, bug, 🍰 p2-nice-to-have, 🔨 p3-minor-bug, performance, 4.x

#27332 docs: add windows git clone symlink tip
  docs/5.community/4.contribution.md
Labels: documentation, 3.x

#27338 fix(nuxt): resolve modules from layers directories
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug, 🔨 p3-minor-bug, layers

#27341 fix(schema): pass correct jsx config for esbuild-loader
  packages/schema/src/config/webpack.ts
Labels: 3.x, bug, webpack, 🔨 p3-minor-bug

#27342 fix(nuxt): transpile `app.config` files in nitro build
  packages/nuxt/src/core/nitro.ts
  test/fixtures/basic/app.config.js
Labels: 3.x, bug, nitro, 🔨 p3-minor-bug

#27350 fix(nuxt): use relative paths in `app.config.d.ts`
  packages/nuxt/src/core/templates.ts
Labels: types, 3.x, bug, 🔨 p3-minor-bug

#27355 Docs: fix release badges
  docs/5.community/6.roadmap.md
Labels: 3.x

#27356 fix(vite): disable `optimizeDeps` in ssr
  packages/vite/src/server.ts
Labels: 3.x, bug

#27366 docs: fix list spacing
  packages/schema/src/config/app.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/nitro.ts
Labels: documentation, 3.x

#27372 perf(vite): exclude common ESM deps from pre-bundling
  packages/nuxt/src/pages/module.ts
  packages/vite/src/client.ts
  packages/vite/src/vite.ts
Labels: 3.x, performance

#27348 docs: capitalize text
  docs/2.guide/2.directory-structure/1.components.md
Labels: 3.x, chore

#27326 feat: add ability to set HMR port
  packages/vite/src/client.ts
Labels: 3.x

#27396 perf(kit,nuxt): remove handling for node 14 perf api
  packages/kit/src/module/define.ts
  packages/nuxt/src/core/app.ts
Labels: enhancement, 3.x, kit, performance
