Repository nuxt/nuxt, pull requests merged in 2025-03, with the labels that each got.

#31144 feat(nuxt): add useAsyncData dev warning
  eslint.config.mjs
  packages/nuxt/src/app/composables/asyncData.ts
Labels: enhancement, 3.x

#31081 fix(nuxt): showError on island page error
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/components/runtime/server-component.ts
  test/bundle.test.ts
  test/nuxt/island-pages.test.ts
Labels: 3.x, bug

#31079 feat(kit,nuxt): augment nitro types with `addTypeTemplate`
  packages/kit/src/template.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/types/hooks.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/server/type-context.ts
Labels: enhancement, 3.x

#31174 test: benchmark minimal fixture instead
  packages/nuxt/test/build-plugins.bench.ts
Labels: 3.x, test

#31175 feat(kit,nuxt): resolve template imports from originating module
  packages/kit/src/template.ts
  packages/kit/src/utils.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/nuxt.ts
Labels: enhancement, 3.x

#31176 perf(kit): skip extra module resolution step in `loadNuxt`
  packages/kit/src/loader/nuxt.ts
Labels: 3.x, performance

#31167 fix(nuxt): do not render payloads if disabled, and correct regexp
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
Labels: 3.x, bug

#30066 feat(nuxt): use `oxc-parser` instead of esbuild + acorn
  packages/nuxt/package.json
  packages/nuxt/src/components/plugins/tree-shake.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/component-names.test.ts
  packages/nuxt/test/composable-keys.test.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/plugin-metadata.test.ts
  packages/nuxt/test/route-rules.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x, performance

#31116 docs: clarify lifecycle behavior of `<NuxtPage>` during page changes
  docs/3.api/1.components/2.nuxt-page.md
Labels: documentation, 3.x

#31202 fix(schema): use `RawVueCompilerOptions` for unresolved `tsconfig`
  packages/schema/src/config/typescript.ts
  packages/schema/src/types/hooks.ts
Labels: 3.x, bug

#31169 feat(nuxt): upgrade Unhead v2 major
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/5.seo-meta.md
  docs/3.api/2.composables/use-head-safe.md
  docs/3.api/2.composables/use-route-announcer.md
  docs/3.api/2.composables/use-seo-meta.md
  docs/3.api/5.kit/10.templates.md
  docs/7.migration/4.meta.md
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/composables/head.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/route-announcer.ts
  packages/nuxt/src/app/composables/script-stubs.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/core/runtime/nitro/utils/build-files.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/plugins/unhead-imports.ts
  packages/nuxt/src/head/runtime/components.ts
  packages/nuxt/src/head/runtime/composables/v3.ts
  packages/nuxt/src/head/runtime/composables/v4.ts
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/unhead-imports.test.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/app.ts
  packages/schema/src/index.ts
  packages/schema/src/types/head.ts
  packages/vite/src/server.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/head-script-setup.vue
  test/fixtures/basic/pages/head.vue
  test/nuxt/composables.test.ts
  tsconfig.json
Labels: enhancement, 3.x, 4.x

#31170 feat(nuxt): upgrade to unhead v2
  docs/1.getting-started/12.upgrade.md
  docs/1.getting-started/5.seo-meta.md
  docs/3.api/2.composables/use-head-safe.md
  docs/3.api/2.composables/use-route-announcer.md
  docs/3.api/2.composables/use-seo-meta.md
  docs/3.api/5.kit/10.templates.md
  docs/7.migration/4.meta.md
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/app/components/island-renderer.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/composables/component.ts
  packages/nuxt/src/app/composables/head.ts
  packages/nuxt/src/app/composables/index.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/route-announcer.ts
  packages/nuxt/src/app/composables/script-stubs.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/core/runtime/nitro/utils/build-files.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/plugins/unhead-imports.ts
  packages/nuxt/src/head/runtime/components.ts
  packages/nuxt/src/head/runtime/composables/v3.ts
  packages/nuxt/src/head/runtime/composables/v4.ts
  packages/nuxt/src/head/runtime/plugins/unhead.ts
  packages/nuxt/src/head/runtime/plugins/vueuse-head-polyfill.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/unhead-imports.test.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/app.ts
  packages/schema/src/index.ts
  packages/schema/src/types/head.ts
  packages/vite/src/server.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/bundle.test.ts
  test/fixtures/basic/pages/head-script-setup.vue
  test/fixtures/basic/pages/head.vue
  test/nuxt/composables.test.ts
  tsconfig.json
Labels: enhancement, 3.x

#31205 fix(nuxt): skip deep merge in dev mode for prototype keys
  packages/nuxt/src/app/config.ts
Labels: 3.x

#31208 docs: update getCachedData
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#31209 fix(nuxt): consolidate head component context
  docs/1.getting-started/5.seo-meta.md
  packages/nuxt/src/head/runtime/components.ts
  test/basic.test.ts
Labels: 3.x, bug

#31198 chore(deps): upgrade to unenv v2
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  packages/rspack/package.json
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/vite/src/vite.ts
  packages/webpack/package.json
  packages/webpack/src/configs/client.ts
  pnpm-lock.yaml
Labels: 3.x, chore

#31227 fix(nuxt): resolve shared externals to absolute paths
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/vite/src/server.ts
  test/bundle.test.ts
Labels: 3.x, bug

#31231 fix(nuxt): resolve shared externals to absolute paths (#31227)
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/vite/src/server.ts
  test/bundle.test.ts
Labels: 3.x, bug

#31235 fix(nuxt): ensure externals are resolved first
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/nuxt/src/core/plugins/resolved-externals.ts
  packages/vite/src/server.ts
  test/bundle.test.ts
Labels: 3.x, bug

#31218 chore(deps): upgrade to nitropack v2.11.2
  .github/workflows/ci.yml
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/schema/package.json
  packages/schema/src/config/common.ts
  pnpm-lock.yaml
  test/fixtures/basic-types/nuxt.config.ts
  test/hmr.test.ts
  test/runtime-compiler.test.ts
  test/suspense.test.ts
  test/utils.ts
Labels: 3.x, chore

#31237 test: try to improve dev test stability (#31218)
  .github/workflows/ci.yml
  packages/schema/src/config/common.ts
  test/hmr.test.ts
  test/runtime-compiler.test.ts
  test/suspense.test.ts
  test/utils.ts
Labels: 3.x, test

#31246 fix(nuxt): exempt nitro from import protections
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug

#31248 fix(nuxt): ensure head components are reactive
  packages/nuxt/src/head/runtime/components.ts
Labels: 3.x, bug

#31244 fix(nuxt): navigateToOptions replace not keeping query/hash
  packages/nuxt/src/app/composables/router.ts
Labels: 3.x

#31241 test: migrate hmr test to use playwright runner
  .github/workflows/ci.yml
  .gitignore
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  test/bundle.test.ts
  test/e2e/global.setup.ts
  test/e2e/global.teardown.ts
  test/e2e/hmr.test.ts
  test/e2e/test-utils.ts
  test/hmr.test.ts
  test/setup.ts
  vitest.config.ts
Labels: 3.x, test

#31213 fix: useFetch in middleware that returns undefined gives useAsyncData warning
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, bug

#31233 fix(nuxt): apply ignore rules to nitro `devStorage`
  packages/nuxt/src/core/nitro.ts
Labels: enhancement, 3.x

#31190 fix(nuxt): fall back to wasm if oxc native bindings are missing
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/utils/parse.ts
  pnpm-lock.yaml
  test/setup-env.ts
Labels: 3.x, bug

#31262 docs: mention workaround for `typedPages` in unhoisted pnpm setups
  docs/2.guide/3.going-further/1.experimental-features.md
Labels: documentation, 3.x

#31278 fix(nuxt): restore nuxt aliases to nitro compilerOptions.paths
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug

#31295 fix(nuxt): use new `mocked-exports`
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/rspack/package.json
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/vite/src/vite.ts
  packages/webpack/package.json
  packages/webpack/src/configs/client.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#31301 docs: improve HMR performance note for Windows users
  docs/1.getting-started/2.installation.md
Labels: documentation, 3.x

#31307 fix(nuxt): check resolved options for polyfills
  packages/nuxt/src/imports/module.ts
Labels: 3.x, bug

#31322 docs: correct WSL note phrasing
  docs/1.getting-started/2.installation.md
Labels: documentation, 3.x

#31341 chore: updated typo mistake
  docs/2.guide/2.directory-structure/1.components.md
Labels: 3.x

#31350 docs: adjust `app.head` example
  docs/1.getting-started/5.seo-meta.md
  packages/schema/src/config/app.ts
Labels: documentation, 3.x

#31346 docs(nuxt): include package manager options in update script
  docs/1.getting-started/12.upgrade.md
Labels: documentation, 3.x

#31337 fix(nuxt): style components are not rendered
  packages/nuxt/src/head/runtime/components.ts
Labels: 3.x, bug

#31362 docs: missing comma in code example
  docs/3.api/5.kit/11.nitro.md
Labels: 3.x

#31369 docs: addServerTemplate
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#31371 docs: add `rspack` and remove `test-utils` for monorepo guide
  docs/5.community/5.framework-contribution.md
Labels: documentation, 3.x

#31372 docs: adjust example
  docs/7.migration/6.pages-and-layouts.md
Labels: documentation, 3.x

#31388 docs: update experimental docs
  docs/1.getting-started/12.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/schema/src/config/experimental.ts
Labels: documentation, 3.x

#31379 perf(nuxt): use browser cache for payloads
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/payload.client.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
Labels: 3.x, performance

#31359 fix(nuxt): add missing lazyhydration prop in regex
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
  packages/nuxt/test/component-loader.test.ts
Labels: 3.x, bug

#31273 test: migrate spa preloader tests to playwright
  test/e2e/spa-preloader-body.test.ts
  test/e2e/spa-preloader-within.test.ts
  test/fixtures/spa-loader/app.vue
  test/fixtures/spa-loader/plugins/delay.client.ts
  test/spa-loader/spa-preloader-outside-disabled.test.ts
  test/spa-loader/spa-preloader-outside-enabled.test.ts
Labels: 3.x

#31302 chore: add scorecard badge
  README.md
Labels: 3.x, chore

#31432 test: use `srvx` and random port for remote provider
  package.json
  pnpm-lock.yaml
  test/fixtures/remote-provider/index.ts
  test/fixtures/remote-provider/package.json
  test/nuxt/nuxt-island.test.ts
Labels: 3.x, test

#31436 fix(nuxt): fully resolve nuxt dependencies
  eslint.config.mjs
  packages/nuxt/src/core/plugins/resolved-externals.ts
  packages/nuxt/src/meta.mjs
Labels: 3.x, bug

#31439 fix(vite): don't show interim vite build output files
  packages/vite/src/server.ts
  packages/vite/src/utils/logger.ts
Labels: 3.x, bug

#31427 docs: improve `useHydration` docs
  docs/3.api/2.composables/use-hydration.md
Labels: documentation, 3.x

#31430 docs: update broken docs links
  docs/1.getting-started/12.upgrade.md
  packages/kit/src/runtime-config.ts
  packages/nuxt/src/core/runtime/nitro/handlers/error.ts
  packages/schema/src/config/app.ts
Labels: documentation, 3.x

#31234 docs: mention possibility of prerendering api routes
  docs/1.getting-started/9.prerendering.md
  docs/3.api/3.utils/prerender-routes.md
Labels: documentation, 3.x

#31450 fix(nuxt): use more performant router catchall pattern
  .gitignore
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug

#31454 fix(nuxt): sort route paths before creating route tree
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug, pages

#31459 docs: provide async function for `$fetch`
  docs/3.api/3.utils/$fetch.md
Labels: documentation, 3.x

#31462 docs: mention the possibility to scan pages based on a pattern
  packages/schema/src/config/adhoc.ts
Labels: documentation, 3.x

#31467 chore(docs): add dedupe flag
  docs/3.api/4.commands/upgrade.md
Labels: documentation, 3.x

#31448 docs: improve `refreshNuxtData` docs
  docs/3.api/3.utils/refresh-nuxt-data.md
Labels: documentation, 3.x

#31469 docs: reverted to `npx nuxi init` where `--template` is used
  docs/2.guide/3.going-further/3.modules.md
  docs/2.guide/3.going-further/7.layers.md
Labels: documentation, 3.x

#31487 docs: improve refresh nuxt data example
  docs/3.api/3.utils/refresh-nuxt-data.md
Labels: documentation, 3.x

#31513 fix(nuxt): pass down attrs to <Body> and <Html>
  packages/nuxt/src/head/runtime/components.ts
Labels: 3.x, bug

#31520 feat(nuxt): save selected package manager
  docs/1.getting-started/02.installation.md
  docs/1.getting-started/06.styling.md
  docs/1.getting-started/15.prerendering.md
  docs/1.getting-started/17.testing.md
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/8.typescript.md
  docs/2.guide/2.directory-structure/1.plugins.md
  docs/2.guide/3.going-further/3.modules.md
  docs/2.guide/4.recipes/2.vite-plugin.md
  docs/6.bridge/1.overview.md
  docs/6.bridge/8.nitro.md
Labels: enhancement, 3.x

#31519 docs: replace all 'Nuxt 3' with 'Nuxt' in documentation
  docs/1.getting-started/05.assets.md
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/16.deployment.md
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/2.guide/1.concepts/3.rendering.md
  docs/2.guide/1.concepts/4.server-engine.md
  docs/2.guide/2.directory-structure/3.app.md
  docs/2.guide/3.going-further/3.modules.md
  docs/2.guide/3.going-further/6.nuxt-app.md
  docs/2.guide/3.going-further/7.layers.md
  docs/2.guide/3.going-further/9.debugging.md
  docs/2.guide/4.recipes/1.custom-routing.md
  docs/2.guide/4.recipes/3.custom-usefetch.md
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/3.utils/define-nuxt-component.md
  docs/3.api/5.kit/7.pages.md
  docs/5.community/4.contribution.md
  docs/5.community/5.framework-contribution.md
  docs/5.community/6.roadmap.md
Labels: documentation, 3.x

#31511 docs: mention autoimport resolveComponent only works with literal strings
  docs/2.guide/2.directory-structure/1.components.md
Labels: documentation, 3.x

#31473 docs: fix format
  docs/3.api/5.kit/2.programmatic.md
Labels: documentation, 3.x

#31523 docs: capitalize text
  docs/1.getting-started/06.styling.md
Labels: documentation, 3.x

#31528 fix(nuxt): use greedy catchall when `/index` is the last segment
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/__snapshots__/pages-override-meta-disabled.test.ts.snap
  packages/nuxt/test/__snapshots__/pages-override-meta-enabled.test.ts.snap
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug, pages

#31517 fix(nuxt): write initial cookie value if different from `document.cookie`
  packages/nuxt/src/app/composables/cookie.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31526 fix(nuxt): support template string quotes in `resolveComponent`
  packages/nuxt/src/components/plugins/loader.ts
Labels: 3.x, bug

#31518 fix(nuxt): show fatal errors thrown in middleware
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/bundle.test.ts
Labels: 3.x, bug

#31540 fix(kit,vite): ensure all `modulesDir` paths are added to `fs.allow`
  packages/kit/src/module/install.ts
  packages/schema/src/config/vite.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug

#31545 fix(nuxt): improve default scroll behaviour
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: 3.x

#31543 fix(vite): return 404 for non-existent `_nuxt/` paths in development
  packages/vite/src/client.ts
Labels: 3.x, bug, nitro, vite

#31561 refactor(nuxt): simplify conditional branches of `<NuxtPage>`
  packages/nuxt/src/pages/runtime/page.ts
  test/bundle.test.ts
Labels: 3.x, refactor

#31570 docs: inprove description of `page:start` and `page:finish` hooks
  docs/3.api/6.advanced/1.hooks.md
Labels: documentation, 3.x

#31573 fix(nuxt): pass error data to `error.vue`
  packages/nuxt/src/core/runtime/nitro/handlers/error.ts
Labels: 3.x, bug

#31586 refactor(nuxt): improve tree-shaking of `useRequestEvent` on client
  packages/nuxt/src/app/composables/ssr.ts
Labels: 3.x, refactor

#31585 refactor: replace `useServerHead` in `onPrehydrate` with `useHead`
  packages/nuxt/src/app/composables/ssr.ts
Labels: 3.x, refactor

#31584 fix: use `unhead` v2 compatible API in `ui-templates`
  packages/ui-templates/lib/render.ts
  packages/ui-templates/test/templates.spec.ts
Labels: 3.x, bug

#31507 fix(nuxt): ensure layer array-type config is merged in order
  packages/kit/src/loader/config.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/layers-fixture/custom/module.ts
  packages/nuxt/test/layers-fixture/custom/modules/module.ts
  packages/nuxt/test/layers-fixture/custom/nuxt.config.ts
  packages/nuxt/test/layers-fixture/layers/auto/module.ts
  packages/nuxt/test/layers-fixture/layers/auto/modules/module.ts
  packages/nuxt/test/layers-fixture/layers/auto/nuxt.config.ts
  packages/nuxt/test/layers-fixture/module.ts
  packages/nuxt/test/layers-fixture/modules/module.ts
  packages/nuxt/test/layers-fixture/nuxt.config.ts
  packages/nuxt/test/load-nuxt.test.ts
  packages/nuxt/test/shared-dir-config.test.ts
Labels: 3.x, bug
