Repository nuxt/nuxt, pull requests merged in 2025-10, with the labels that each got.

#33358 fix(nuxt): don't trigger scroll when changing trailing slash
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/pages/runtime/router.options.ts
  test/nuxt/router.options.test.ts
Labels: enhancement, 4.x

#33325 fix(nuxt): prevent duplicate execution on key change in `useAsyncData`
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/use-async-data.test.ts
Labels: bug, 4.x

#33379 fix(nuxt): make middleware `_path` property configurable for HMR
  packages/nuxt/src/core/templates.ts
Labels: bug, 4.x

#33389 chore(kit): remove todo comment as resolved
  packages/kit/src/context.ts
Labels: chore, 4.x

#33394 refactor(nuxt): place `filename` into `componentsIslandsTemplate` definition
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
Labels: refactor, 4.x

#33409 docs: add custom nuxt module addServerPlugin warning
  docs/3.api/5.kit/11.nitro.md
Labels: documentation, 4.x

#33222 fix(nuxt): redirect with hash in routeRules
  packages/nuxt/src/app/middleware/manifest-route-rule.ts
  test/basic.test.ts
  test/fixtures/basic/app/pages/index.vue
  test/fixtures/basic/app/pages/route-rules/redirect.vue
  test/fixtures/basic/nuxt.config.ts
Labels: bug, 4.x

#33420 fix(kit): safe assignment and cleanup of `defineNuxtConfig` for concurrent calls
  packages/kit/src/loader/config.ts
Labels: bug, 4.x

#33328 feat(kit): add `extensions` option for `resolveModule`
  packages/kit/src/internal/esm.ts
Labels: enhancement, 4.x

#33344 fix(nuxt): remove `mergeModels` from auto imports
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/auto-imports.test.ts
Labels: chore, 4.x

#33384 refactor: remove obsolete `shortPath` property
  packages/kit/src/components.ts
  packages/kit/test/components.spec.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/test/component-loader.test.ts
  packages/nuxt/test/components-transform.test.ts
  packages/nuxt/test/components-tree-shake.test.ts
  packages/nuxt/test/island-transform.test.ts
  packages/nuxt/test/lazy-hydration-macro-transform.test.ts
  packages/nuxt/test/scan-components.test.ts
  packages/schema/src/types/components.ts
Labels: refactor, 4.x

#33361 perf(nuxt): use prerelease bundle renderer with precompute support
  packages/nuxt/package.json
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/build-files.ts
  packages/rspack/package.json
  packages/vite/package.json
  packages/vite/src/manifest.ts
  packages/vite/src/vite-node.ts
  packages/vite/src/vite.ts
  packages/webpack/package.json
  packages/webpack/src/plugins/vue/client.ts
  packages/webpack/src/presets/vue.ts
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: performance, 4.x

#32531 feat(nuxt): add abortController option to `useAsyncData`
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/nuxt.ts
  test/nuxt/use-async-data.test.ts
  test/nuxt/use-fetch.test.ts
Labels: enhancement, 4.x
