Repository nuxt/nuxt, pull requests merged in 2025-07, with the labels that each got.

#32510 fix(nuxt): safe-guard `extraPageMetaExtractionKeys`
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
Labels: bug, 4.x

#32527 fix(vite): handle resolving string vite input
  packages/vite/src/utils/config.ts
Labels: bug, 4.x

#32528 fix(kit): ensure legacy tsConfig doesn't exclude too many types
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/8.typescript.md
  docs/2.guide/2.directory-structure/3.tsconfig.md
  docs/7.migration/2.configuration.md
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  packages/schema/src/types/hooks.ts
  packages/schema/src/types/schema.ts
  playground/tsconfig.json
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/tsconfig.json
  test/fixtures/basic/tsconfig.json
  test/fixtures/hmr/tsconfig.json
  test/fixtures/minimal-pages/tsconfig.json
  test/fixtures/minimal-types/tsconfig.json
  test/fixtures/minimal/tsconfig.json
  test/fixtures/runtime-compiler/tsconfig.json
  test/fixtures/spa-loader/tsconfig.json
  test/fixtures/suspense/tsconfig.json
  test/nuxt/tsconfig.json
Labels: bug, 4.x

#32551 fix(kit): ensure types of module entrypoints are in node project
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
Labels: bug, 4.x

#32223 chore: clarify runtimeConfig and process.env usage in nuxt.config
  docs/2.guide/2.directory-structure/2.env.md
Labels: 3.x, chore

#32560 docs: fix key change behavior in `useAsyncData` and `useFetch` migration
  docs/1.getting-started/18.upgrade.md
Labels: documentation, 4.x

#32574 fix(nuxt): ensure `semver.satisfies` returns true for pre-release versions
  packages/nuxt/src/core/nuxt.ts
Labels: bug, 4.x

#32585 test: add more useAsyncData + useFetch tests
  test/nuxt/composables.test.ts
  test/nuxt/use-async-data.test.ts
  test/nuxt/use-fetch.test.ts
Labels: test, 4.x

#32587 docs: provide `async` keyword
  docs/3.api/2.composables/use-runtime-config.md
Labels: documentation, 4.x

#32588 chore(deps): upgrade nuxt eslint config + lint
  debug/plugins/timings-unbuild.ts
  eslint.config.mjs
  package.json
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/runtime/nitro/handlers/island.ts
  packages/nuxt/src/core/runtime/nitro/utils/error.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/vite/src/plugins/public-dirs.ts
  pnpm-lock.yaml
Labels: chore, 4.x

#32595 docs: move augmenting hook types in hooks page
  docs/2.guide/3.going-further/1.events.md
  docs/2.guide/3.going-further/2.hooks.md
Labels: documentation, 4.x

#32600 fix(schema): disable changing compat version
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/2.directory-structure/1.shared.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/1.features.md
  docs/3.api/5.kit/9.plugins.md
  docs/3.api/6.nuxt-config.md
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/schema.ts
Labels: bug, 4.x

#32589 docs: add reference to `useNuxtData` under `useFetch`
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 4.x

#32601 fix(nuxt): allow modules to add to `typescript.hoist`
  packages/nuxt/src/core/nuxt.ts
Labels: bug, 4.x

#32622 fix(nuxt): only use `scrollBehaviorType` for hash scrolling
  packages/nuxt/src/pages/runtime/router.options.ts
Labels: bug, 4.x

#32599 docs: document the --modules flag in the init command
  docs/3.api/4.commands/init.md
Labels: documentation, 4.x

#32617 feat(nuxt): expose page routes to nitro for o11y
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/nitro-ssr-routes.test.ts
  packages/nuxt/test/pages.test.ts
Labels: enhancement, 4.x

#32639 docs: update nuxt.new links to v4
  docs/1.getting-started/02.installation.md
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 4.x

#32567 docs: typos
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/15.prerendering.md
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 4.x

#32613 docs: fix abbreviation
  docs/1.getting-started/17.testing.md
  packages/kit/src/module/install.ts
  packages/nuxt/src/core/utils/names.ts
Labels: documentation, 4.x

#32643 docs: reference `noUncheckedIndexedAccess` rule change in v4 guide
  docs/1.getting-started/18.upgrade.md
Labels: documentation, 4.x

#32648 docs: add missing import in alias config example
  docs/3.api/6.nuxt-config.md
Labels: documentation, 4.x

#32644 fix(nuxt): add `nuxt.schema` files to node tsconfig context
  packages/nuxt/src/core/schema.ts
Labels: bug, 4.x

#32676 fix(nuxt): expose shared aliases within `shared/` dir
  packages/nuxt/src/core/nitro.ts
  test/fixtures/basic-types/shared/other.ts
  test/fixtures/basic-types/shared/shared-types.ts
Labels: bug, 🔨 p3-minor, 4.x

#31609 docs: add best practices section
  docs/2.guide/0.index.md
  docs/2.guide/5.best-practices/.navigation.yml
  docs/2.guide/5.best-practices/performance.md
  docs/2.guide/5.best-practices/plugins.md
Labels: documentation, 3.x

#32691 docs: fix links to Nitro docs
  docs/1.getting-started/15.prerendering.md
  docs/1.getting-started/16.deployment.md
  docs/1.getting-started/18.upgrade.md
  docs/3.api/6.nuxt-config.md
  packages/nuxt/src/core/external-config-files.ts
  packages/schema/src/types/schema.ts
Labels: documentation, 4.x

#32695 ci: trigger website redeploy on main branch
  .github/workflows/notify-nuxt-website.yml
Labels: chore, 4.x

#32707 fix(nuxt): provide typed slots for `<ClientOnly>` and `<DevOnly>`
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/components/dev-only.ts
Labels: 4.x

#32722 chore: update reproduction links for bug-report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: chore, 4.x

#32724 docs: set correct default value for deep option in usefetch
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#32755 fix(kit,nuxt,schema): add trailing slash to some dir aliases
  packages/kit/src/loader/config.ts
  packages/kit/src/template.ts
  packages/kit/test/load-nuxt-config.spec.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/schema/package.json
  packages/schema/src/config/common.ts
  pnpm-lock.yaml
Labels: types, bug, 4.x

#32759 fix(nuxt): update `unbuild` and use absolute path in stubs
  debug/build-config.ts
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/rspack/package.json
  packages/schema/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
Labels: bug, 4.x

#32758 fix(kit): include module types in `app` context
  packages/kit/src/template.ts
Labels: types, bug, 4.x

#32757 docs: add example for module `.with()`
  docs/3.api/5.kit/1.modules.md
Labels: documentation, 4.x

#32767 chore(deps): update vite + vite plugins to v7
  docs/1.getting-started/17.testing.md
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/nuxt/test/treeshake-client.test.ts
  packages/schema/package.json
  packages/ui-templates/package.json
  packages/vite/package.json
  playground/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/basic-types/package.json
  test/fixtures/basic/package.json
  test/fixtures/hmr/package.json
  test/fixtures/minimal-pages/package.json
  test/fixtures/minimal-types/package.json
  test/fixtures/minimal/package.json
  test/fixtures/runtime-compiler/package.json
  test/fixtures/spa-loader/package.json
  test/fixtures/suspense/package.json
Labels: 3.x, chore

#32772 fix(nuxt): use joinURL when remote island is provided
  packages/nuxt/src/app/components/nuxt-island.ts
  test/nuxt/nuxt-island.test.ts
Labels: bug, 4.x

#32791 fix(vite): use vite node server to transform requests
  packages/vite/src/vite-node.ts
Labels: bug, 4.x

#32776 docs: update nightly version
  docs/2.guide/3.going-further/11.nightly-release-channel.md
Labels: documentation, 4.x

#32386 fix(kit): try resolving module subpaths in `resolveNuxtModule` fn
  packages/kit/src/resolve.test.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/nuxt/src/core/nitro.ts
Labels: bug, 4.x

#32744 fix(nuxt): execute all plugins after error rendering error.vue
  packages/nuxt/src/app/nuxt.ts
Labels: bug, 4.x

#32807 fix(nuxt): throwing undefined `error` variable
  packages/nuxt/src/app/nuxt.ts
Labels: bug, 4.x
