Repository nuxt/nuxt, pull requests merged in 2025-01, with the labels that each got.

#30412 fix(schema): support pfx certificate for dev server
  packages/schema/src/config/dev.ts
Labels: 3.x, bug

#30447 fix(nuxt): use node `location` instead of `range` for route meta property extraction
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug

#30454 fix(schema): override `vueCompilerOptions.plugins` type
  packages/schema/src/config/typescript.ts
  packages/schema/src/types/hooks.ts
Labels: 3.x, bug

#30446 fix(nuxt): respect `baseURL` when ignoring prerendered manifest
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, bug

#30455 fix(nuxt): respect `router.options` when hmring routes
  packages/nuxt/src/pages/build.d.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/runtime/plugins/prerender.server.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, bug

#30437 docs: add api functionality docs (#30436)
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#30456 perf(nuxt): drop `pathe` browser dep for deep server components
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
Labels: 3.x, performance

#30457 test: add minimal pages fixture
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/minimal-pages/app.vue
  test/fixtures/minimal-pages/error.vue
  test/fixtures/minimal-pages/layouts/default.vue
  test/fixtures/minimal-pages/middleware/test.global.ts
  test/fixtures/minimal-pages/nuxt.config.ts
  test/fixtures/minimal-pages/package.json
  test/fixtures/minimal-pages/pages/a.client.vue
  test/fixtures/minimal-pages/pages/b.server.vue
  test/fixtures/minimal-pages/pages/index.vue
  test/fixtures/minimal-pages/plugins/test.ts
  test/fixtures/minimal-pages/tsconfig.json
Labels: 3.x, test

#30460 perf(nuxt): remove code duplication in client-only
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/components/utils.ts
Labels: 3.x, performance

#30477 docs: document `--dev` option for the module command
  docs/3.api/4.commands/module.md
Labels: documentation, 3.x

#30476 docs: document the add layer command
  docs/3.api/4.commands/add.md
Labels: documentation, 3.x

#30478 fix(nuxt): collect all identifiers before extracting page metadata
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug

#30490 fix(nuxt): do not hoist identifiers declared locally in `definePageMeta` when extracting page metadata
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/parse.test.ts
Labels: 3.x, bug

#30514 docs: update v4 release date
  docs/5.community/6.roadmap.md
Labels: documentation, 3.x

#30520 fix(kit): reorder `#build` to the end of tsConfig paths
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
Labels: 3.x, bug

#30526 perf(nuxt): use lighter `@nuxt/cli` dependency
  packages/nuxt/bin/nuxt.mjs
  packages/nuxt/build.config.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/features.ts
  pnpm-lock.yaml
Labels: 3.x, performance

#30531 docs: ensure correct type for `url` in `useFetch`
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#30536 docs: add `status` detail and enhance `getCachedData` readability
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
Labels: documentation, 3.x

#30500 fix(nuxt): use `fullPath` instead of empty string in router hmr
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug

#30543 docs: update hash link to correct heading
  docs/2.guide/2.directory-structure/1.composables.md
Labels: documentation, 3.x

#30547 chore: remove stray `nuxi` version again
  package.json
  pnpm-lock.yaml
Labels: 3.x, chore

#30548 ci: don't block release on fixtures + add pkg.pr.new
  .github/workflows/autofix-docs.yml
  .github/workflows/autofix.yml
  .github/workflows/benchmark.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint-monorepo.yml
  .github/workflows/release.yml
  .github/workflows/semantic-pull-requests.yml
  package.json
  pnpm-lock.yaml
Labels: 3.x, chore

#30562 perf(kit): remove iterations when resolving module path
  packages/kit/src/module/install.ts
Labels: 3.x, performance

#30570 docs: adjust example and additional instructions of `useNuxtData`
  docs/3.api/2.composables/use-nuxt-data.md
Labels: documentation, 3.x

#30573 docs: resolve many twoslash errors that occur during `nuxt generate`
  docs/1.getting-started/11.testing.md
Labels: documentation, 3.x

#30581 perf(nuxt): avoid checking fs for existence of scanned files
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, performance

#30567 perf(nuxt): defer version/config checks to after vite build
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/check-dependencies.test.ts
  packages/nuxt/test/load-nuxt.test.ts
Labels: 3.x, performance

#30540 fix(kit): fully resolve plugin paths when normalising them
  packages/kit/package.json
  packages/kit/src/plugin.ts
  packages/nuxt/test/app.test.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#29009 fix(nuxt): call `page:loading:end` only once with nested pages
  packages/nuxt/src/pages/runtime/page.ts
  test/basic.test.ts
  test/fixtures/basic/app.vue
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/page-load-hook.vue
  test/fixtures/basic/pages/page-load-hook/[slug].vue
  test/fixtures/basic/plugins/page-hook-plugin.ts
Labels: 3.x, bug

#30584 fix(nuxt): allow url-specific chars in vfs
  packages/nuxt/src/core/plugins/virtual.ts
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/vite/src/vite-node.ts
  packages/vite/src/vite.ts
  test/hmr.test.ts
Labels: 3.x, bug

#30479 docs: add context for useAsyncData side effects
  docs/1.getting-started/6.data-fetching.md
  docs/3.api/2.composables/use-async-data.md
Labels: documentation, 3.x

#30587 fix(vite): provide fallback alias for `#app-manifest`
  packages/vite/src/client.ts
Labels: 3.x, bug

#30589 refactor(kit,nuxt,webpack): reduce reassignments
  packages/kit/src/build.ts
  packages/kit/src/components.ts
  packages/kit/src/loader/config.ts
  packages/kit/src/loader/nuxt.ts
  packages/kit/src/module/define.ts
  packages/kit/src/module/install.ts
  packages/kit/src/nitro.ts
  packages/kit/src/pages.ts
  packages/kit/src/plugin.ts
  packages/kit/src/template.ts
  packages/kit/src/utils.ts
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/composables/once.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/no-ssr.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/pages/module.ts
  packages/webpack/src/configs/client.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/presets/base.ts
Labels: 3.x, refactor

#30591 fix(nuxt): avoid invoke `shouldPrefetch` on the server side
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: 3.x, bug

#30599 fix(nuxt): decode id before resolving relative imports
  package.json
  packages/nuxt/src/core/plugins/virtual.ts
  packages/nuxt/test/virtual.test.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#30629 docs: add link to custom `useFetch` example
  docs/2.guide/4.recipes/3.custom-usefetch.md
Labels: documentation, 3.x

#30628 docs: fix example command
  docs/2.guide/2.directory-structure/2.env.md
Labels: 3.x

#30618 fix(vite): override previous `#app-manifest` alias
  packages/vite/src/client.ts
Labels: 3.x, bug

#30620 fix(kit,nuxt,schema,vite): improve watching behaviour
  packages/kit/src/ignore.ts
  packages/kit/src/index.ts
  packages/nuxt/src/components/plugins/transform.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/cache.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/imports/module.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/common.ts
  packages/vite/src/vite.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#30614 docs: add description for prefetch and other details of `NuxtLink`
  docs/3.api/1.components/4.nuxt-link.md
Labels: documentation, 3.x

#30648 chore: add debug timing jiti/unbuild plugins
  debug/build-config.ts
  debug/plugins/timings-babel.mjs
  debug/plugins/timings-unbuild.ts
  package.json
  packages/kit/build.config.ts
  packages/nuxt/build.config.ts
  packages/rspack/build.config.ts
  packages/schema/build.config.ts
  packages/vite/build.config.ts
  packages/webpack/build.config.ts
  pnpm-lock.yaml
Labels: 3.x, chore

#30649 fix(nuxt): fall back to `plugin.src` for variable name generation
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#30650 perf(kit,nuxt): don't resolve paths from local layers/modules
  packages/kit/src/module/install.ts
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, performance

#30651 perf(nuxt): reduce number of `mkdirSync` calls
  packages/nuxt/src/core/app.ts
Labels: 3.x, performance

#30634 refactor(vite): drop `externality` and use vite internal config
  packages/vite/package.json
  packages/vite/src/utils/external.ts
  packages/vite/src/vite-node.ts
  pnpm-lock.yaml
Labels: 3.x, refactor

#30664 fix(nuxt): wrap slot with `h()` in ClientOnly
  packages/nuxt/src/app/components/client-only.ts
Labels: 3.x, bug

#30644 chore(deps): update nitro + h3 nightly versions + reenable tracking
  package.json
  packages/kit/package.json
  packages/nuxt/package.json
  packages/rspack/package.json
  packages/schema/package.json
  packages/vite/package.json
  packages/webpack/package.json
  pnpm-lock.yaml
  renovate.json
  test/bundle.test.ts
Labels: 3.x, chore

#30667 fix(schema): allow overriding `dev`/`test` environment value
  packages/schema/src/config/common.ts
Labels: 3.x, bug

#30656 docs: adjust examples, type and description for `addRouteMiddleware`
  docs/3.api/3.utils/add-route-middleware.md
Labels: documentation, 3.x

#30684 perf(nuxt): reduce unnecessary template updating
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/pages/module.ts
  test/bundle.test.ts
Labels: 3.x, performance

#30670 docs: explain how to use ClientOnly with onMounted hook
  docs/3.api/1.components/1.client-only.md
Labels: documentation, 3.x

#30612 docs: add more context about `navigation` mode in `callOnce` composable
  docs/3.api/3.utils/call-once.md
Labels: documentation, 3.x

#30690 fix(vite): inline shared folder in dev mode
  packages/vite/src/vite-node.ts
Labels: 3.x, bug

#30711 ci: reenable nuxt benchmarking
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  package.json
  packages/kit/test/load-nuxt-config.bench.ts
  packages/kit/test/write-types.bench.ts
  packages/nuxt/test/load-nuxt.bench.ts
  pnpm-lock.yaml
  vitest.config.ts
Labels: 3.x, chore

#30717 fix(nuxt): use klona to deep clone extractedMeta
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/pages.test.ts
Labels: 3.x, bug

#30729 docs: add example on how to disable default routes for ssg
  docs/2.guide/1.concepts/3.rendering.md
Labels: documentation, 3.x

#30754 fix(nuxt): improve error logging when parsing with `acorn`
  packages/nuxt/src/core/utils/parse.ts
Labels: enhancement, 3.x

#30767 fix(nuxt): clear island uid before saving into the payload
  packages/nuxt/src/app/components/nuxt-island.ts
Labels: 3.x, bug

#30766 perf(kit): update env expansion regex to match nitro
  packages/kit/src/runtime-config.test.ts
  packages/kit/src/runtime-config.ts
Labels: 3.x, performance

#30774 fix(kit): load `@nuxt/schema` from `nuxt` package dir
  packages/kit/package.json
  packages/kit/src/loader/config.ts
  packages/nuxt/src/core/nuxt.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#30771 fix(nuxt): allow restarting nuxt on paths outside `srcDir`
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
Labels: 3.x, bug, 4.x

#30780 refactor(vite): use new rollup `chunk.names` for asset names
  packages/vite/src/vite.ts
Labels: 3.x, bug

#30757 fix(webpack): disallow cross-site requests in no-cors mode
  packages/webpack/src/webpack.ts
Labels: 3.x, bug

#30802 fix(vite): restore `externality` for dev server externals
  packages/vite/package.json
  packages/vite/src/utils/external.ts
  packages/vite/src/vite-node.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#30799 docs: tiny typo
  docs/2.guide/2.directory-structure/1.middleware.md
Labels: documentation, 3.x

#30817 docs: fix grammatical mistakes
  docs/3.api/1.components/4.nuxt-link.md
Labels: 3.x
