Repository nuxt/nuxt, pull requests merged in 2025-08, with the labels that each got.

#32841 docs: fix publicDir alias
  docs/3.api/6.nuxt-config.md
Labels: documentation, 4.x

#32820 docs: mention `bun.lock` for lockfile
  SECURITY.md
Labels: documentation, 4.x

#32803 chore: update reproduction help text links
  .github/reproduire/needs-reproduction.md
Labels: chore, 4.x

#32835 fix(vite): include tsconfig references during `typeCheck`
  packages/vite/src/vite.ts
Labels: bug, 4.x

#32849 chore: update pnpm ignored build scripts
  pnpm-workspace.yaml
Labels: chore, 4.x

#32843 docs: add a section about augmenting types with TS project references
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/8.typescript.md
Labels: documentation, 4.x

#32848 test: move tests for `defineNuxtComponent` out of e2e test
  test/basic.test.ts
  test/fixtures/basic/app/pages/define-nuxt-component/index.vue
  test/fixtures/basic/app/pages/define-nuxt-component/inject.vue
  test/fixtures/basic/app/pages/define-nuxt-component/inject/index.vue
  test/fixtures/basic/app/pages/define-nuxt-component/nested/[foo].vue
  test/fixtures/basic/app/pages/define-nuxt-component/route-1.vue
  test/fixtures/basic/app/pages/define-nuxt-component/route-2.vue
  test/fixtures/basic/app/pages/legacy/async-data.vue
  test/fixtures/basic/app/pages/legacy/async-data/index.vue
  test/fixtures/basic/app/pages/legacy/async-data/index/index.vue
  test/nuxt/define-nuxt-component.test.ts
Labels: test, 4.x

#32832 fix(nuxt): add warning for lazy-hydration missing prefix
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
Labels: bug, 4.x

#32863 docs: switch example to use vitest projects
  docs/1.getting-started/17.testing.md
Labels: documentation, 4.x

#32868 docs: update testing `setupTimeout` and add `teardownTimeout`
  docs/1.getting-started/17.testing.md
Labels: documentation, 4.x

#32902 fix(nuxt): handle TSSatisfiesExpression in page augmentation
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: bug, 4.x

#32891 fix(nuxt): forward response type to ofetch options
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic-types/app/app-types.ts
Labels: bug, 4.x

#32914 fix(nuxt): add TS parenthesis and as expression for page meta extraction
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: bug, 4.x

#32901 refactor(nuxt): simplify page segment parsing
  packages/nuxt/src/pages/utils.ts
Labels: refactor, 4.x

#32893 fix(nuxt): use correct unit thresholds for relative time
  nuxt.config.ts
  packages/nuxt/src/app/components/nuxt-time.vue
  test/nuxt/nuxt-time.test.ts
Labels: 3.x, bug

#32874 fix(schema,vite): bump `requestTimeout` + allow configuration
  packages/schema/src/types/schema.ts
  packages/vite/src/runtime/vite-node-shared.mjs
  packages/vite/src/vite-node.ts
Labels: bug, 4.x

#32397 feat(kit): add `onInstall` and `onUpgrade` module hooks
  packages/kit/package.json
  packages/kit/src/module/define.ts
  packages/kit/src/module/install.ts
  packages/kit/test/module-fixture/module.ts
  packages/kit/test/module.test.ts
  packages/schema/src/types/module.ts
  pnpm-lock.yaml
Labels: enhancement, 4.x

#33004 docs: add more information about using `useRoute` and accessing route in middleware
  docs/2.guide/2.directory-structure/1.app/1.middleware.md
  docs/3.api/2.composables/use-route.md
  packages/nuxt/src/app/composables/router.ts
Labels: documentation, 4.x

#33023 test: refactor stubbing of `import.meta.dev`
  nuxt.config.ts
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/use-async-data.test.ts
  vitest.config.ts
Labels: test, 4.x

#33016 fix(schema): allow disabling cssnano/autoprefixer postcss plugins
  packages/schema/src/types/schema.ts
Labels: bug, 4.x

#33031 docs: avoid variable shadowing in locale example
  docs/1.getting-started/11.state-management.md
Labels: bug, 4.x

#33030 fix(kit): ensure local layers are prioritised alphabetically
  docs/1.getting-started/14.layers.md
  docs/2.guide/3.going-further/7.layers.md
  packages/kit/src/loader/config.ts
  packages/kit/test/layer-fixture/custom-layers/a/nuxt.config.ts
  packages/kit/test/layer-fixture/custom-layers/b/nuxt.config.ts
  packages/kit/test/layer-fixture/layers/c/assets/foo.js
  packages/kit/test/layer-fixture/layers/c/nuxt.config.ts
  packages/kit/test/layer-fixture/layers/d/nuxt.config.ts
  packages/kit/test/layer-fixture/nuxt.config.ts
  packages/kit/test/load-nuxt-config.spec.ts
Labels: discussion, bug, layers, 4.x

#33026 fix(kit,nuxt): expose global types to vue compiler
  packages/kit/src/template.ts
  packages/kit/test/templates.spec.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/templates.ts
Labels: bug, 4.x

#33072 fix: bump devalue
  package.json
  packages/nuxt/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: bug, 4.x

#32897 feat(nuxt): extract `defineRouteRules` to page `rules` property
  docs/2.guide/2.directory-structure/1.app/1.pages.md
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/nuxt/test/route-rules.test.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 4.x

#33081 fix(nuxt): support config type inference for `defineNuxtModule().with()`
  packages/nuxt/src/core/templates.ts
Labels: bug, 4.x

#33037 feat(nuxt): lazy hydration macros without auto-imports
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/lazy-hydration-macro-transform.ts
  packages/nuxt/test/lazy-hydration-macro-transform.test.ts
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/macro/index.vue
Labels: bug, 4.x
