Repository nuxt/nuxt, pull requests merged in 2025-04, with the labels that each got.

#31640 docs: add note on extending auto-imports
  docs/2.guide/1.concepts/8.typescript.md
Labels: 3.x

#31645 docs: Improve description about app.vue
  docs/2.guide/2.directory-structure/3.app.md
Labels: documentation, 3.x

#31649 fix(nuxt): pass slots through to lazy hydrated components
  packages/nuxt/src/components/runtime/lazy-hydrated-component.ts
Labels: 3.x, bug

#31646 fix(vite): prevent 404 for existent dev server handlers under `_nuxt/` paths in development
  packages/vite/src/client.ts
Labels: 3.x, bug

#31662 perf(nuxt): use `shallowRef` for built-in composables if possible
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/loading-indicator.ts
  packages/nuxt/src/app/composables/route-announcer.ts
Labels: 3.x, performance

#31365 feat(nuxt): warn server components need root element
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/utils.ts
Labels: enhancement, 3.x, dx

#31619 test(nuxt): add customizable test api for pages tests
  packages/nuxt/test/pages.test.ts
Labels: 3.x, test

#31353 feat(docs): publish raw markdown/yaml docs as `@nuxt/docs`
  .github/workflows/semantic-pull-requests.yml
  docs/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement, 3.x

#31668 refactor(kit,rspack,webpack): switch to `tinyglobby`
  packages/kit/package.json
  packages/kit/src/loader/config.ts
  packages/kit/src/resolve.ts
  packages/rspack/package.json
  packages/webpack/package.json
  packages/webpack/src/nitro/plugins/dynamic-require.ts
  pnpm-lock.yaml
Labels: 3.x, refactor

#31676 fix(nuxt): sync error types for `useLazyAsyncData`
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/fixtures/basic-types/types.ts
Labels: 3.x, bug

#31386 refactor(nuxt): move island renderer into its own event handler
  packages/nuxt/src/app/types.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/handlers/island.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/app.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/build-files.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/inline-styles.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/islands.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/payload.ts
  test/bundle.test.ts
Labels: 3.x, refactor

#31680 feat(kit,nuxt): pass dotenv values from `loadNuxtConfig` to nitro
  packages/kit/src/loader/config.ts
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/internal.ts
Labels: enhancement, 3.x

#31583 docs: improve SEO and Meta docs
  docs/1.getting-started/08.seo-meta.md
Labels: documentation, 3.x

#31686 fix(nuxt): render inline styles before `app:rendered` is called
  packages/nuxt/src/core/runtime/nitro/handlers/island.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
Labels: 3.x, bug

#31688 perf(nuxt): replace remaining instance of `globby`
  packages/nuxt/package.json
  packages/nuxt/src/components/scan.ts
  pnpm-lock.yaml
Labels: 3.x, performance

#31691 build(nuxt): use `vue-sfc-transformer` to process sfcs
  packages/nuxt/package.json
  pnpm-lock.yaml
  test/bundle.test.ts
Labels: 3.x

#31694 test(kit): fix tests when running on Windows
  packages/kit/test/load-nuxt-config.spec.ts
Labels: 3.x, test

#31700 docs: refine auto-imports documentation for clarity and structure
  docs/3.api/5.kit/4.autoimports.md
Labels: documentation, 3.x

#31704 docs: fix nuxt logo on website badge
  README.md
Labels: documentation, 3.x

#31712 docs: adjust description of `useHydration`
  docs/3.api/2.composables/use-hydration.md
Labels: documentation, 3.x

#31726 ci: add notify-nuxt-website workflow
  .github/workflows/notify-nuxt-website.yml
Labels: 3.x, chore

#31725 fix(nuxt): do not prompt to update `compatibilityDate`
  package.json
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/schema/package.json
  playground/nuxt.config.ts
  pnpm-lock.yaml
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/hmr/nuxt.config.ts
  test/fixtures/minimal-pages/nuxt.config.ts
  test/fixtures/minimal-types/nuxt.config.ts
  test/fixtures/minimal/nuxt.config.ts
  test/fixtures/runtime-compiler/nuxt.config.ts
  test/fixtures/spa-loader/nuxt.config.ts
  test/fixtures/suspense/nuxt.config.ts
Labels: 3.x, bug

#31738 perf(kit): exclude `.data` directory from type-checking
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
Labels: 3.x, chore

#31750 chore: update view transitions types
  packages/nuxt/src/pages/module.ts
Labels: 3.x, chore

#31751 docs: update page-metadata link
  docs/3.api/3.utils/define-page-meta.md
Labels: documentation, 3.x

#31747 docs: adjust callOnce fn description
  docs/3.api/3.utils/call-once.md
Labels: documentation, 3.x

#31774 feat(nuxt): warn if user uses reserved `runtimeConfig.app` namespace
  docs/1.getting-started/03.configuration.md
  docs/2.guide/3.going-further/10.runtime-config.md
  packages/nuxt/src/core/nuxt.ts
Labels: enhancement, 3.x

#31785 refactor(nuxt): hoist `purgeCachedData` check for tree-shaking
  packages/nuxt/src/app/plugins/payload.client.ts
Labels: 3.x, refactor

#31784 chore(nuxt): show brotli size by default when analyzing bundle
  packages/vite/src/plugins/analyze.ts
Labels: 3.x, chore

#31760 docs: use `vs.` consistently
  docs/1.getting-started/03.configuration.md
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/7.esm.md
Labels: documentation, 3.x

#31769 docs: update nitro addServerHandler example
  docs/3.api/5.kit/11.nitro.md
  docs/3.api/5.kit/13.logging.md
  packages/nuxt/src/core/nitro.ts
Labels: documentation, 3.x

#31761 fix(nuxt): pass statusMessage to error.vue
  packages/nuxt/src/core/runtime/nitro/handlers/error.ts
Labels: 3.x, bug

#31786 refactor(nuxt): use `_replaceAppConfig` for applying hmr
  packages/nuxt/src/app/config.ts
Labels: 3.x, refactor

#31651 docs: add supporting shared folder video
  docs/2.guide/2.directory-structure/1.shared.md
Labels: documentation, 3.x

#31657 feat(kit,schema): new `enforceModuleCompatibility` feature
  packages/kit/src/module/define.ts
  packages/schema/src/config/experimental.ts
Labels: enhancement, 3.x, dx

#31634 fix(nuxt): throw when multiple definePageMeta in a file
  packages/nuxt/src/pages/plugins/page-meta.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, dx, bug

#30708 feat(nuxt): extract `middleware` when scanning page metadata
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/hooks.ts
Labels: enhancement, 3.x

#31571 fix(nuxt): parse `error.data` before rendering `error.vue`
  docs/1.getting-started/18.upgrade.md
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/schema/src/config/experimental.ts
Labels: 3.x, bug

#29971 feat(nuxt): warn if core auto-import presets are overridden
  packages/nuxt/src/imports/module.ts
Labels: enhancement, 3.x

#31373 fix(nuxt): use single synced asyncdata instance per key
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  nuxt.config.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/pages/useAsyncData/immediate-remove-unmounted.vue
  test/fixtures/basic/pages/useAsyncData/override.vue
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#31796 fix(nuxt): use single synced asyncdata instance per key (#31373)
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  nuxt.config.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  test/basic.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/pages/useAsyncData/immediate-remove-unmounted.vue
  test/fixtures/basic/pages/useAsyncData/override.vue
  test/nuxt/composables.test.ts
  vitest.nuxt.config.ts
Labels: 3.x, bug

#31801 fix(nuxt): use `useAsyncData` as default function name
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: 3.x, chore

#31791 fix(nuxt): wait for suspense to resolve before handling `NuxtErrorBoundary` error
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
  test/basic.test.ts
  test/fixtures/basic/pages/error/error-boundary.vue
  test/fixtures/basic/pages/error/index.vue
Labels: 3.x, bug

#27155 feat(nuxt): scan named exports with `addComponentExports`
  packages/kit/package.json
  packages/kit/src/components.ts
  packages/kit/src/index.ts
  packages/kit/test/components-fixture/Named.ts
  packages/kit/test/components.spec.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x

#31839 fix(vite): disable `preserveModules`
  packages/vite/src/server.ts
  test/bundle.test.ts
Labels: 3.x, bug

#25864 fix(nuxt): align `pending` with `status` value for v4
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  test/fixtures/basic/pages/useAsyncData/nuxt-data.vue
  test/nuxt/composables.test.ts
Labels: enhancement, ⚠️ breaking change, 4.x

#31849 fix(nuxt): consider full path when de-duplicating routes
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug

#31847 feat(nuxt): convert `<NuxtErrorBoundary>` to SFC; expose `error` and `clearError`
  docs/3.api/1.components/6.nuxt-error-boundary.md
  packages/nuxt/src/app/components/nuxt-error-boundary.ts
  packages/nuxt/src/app/components/nuxt-error-boundary.vue
  test/nuxt/error-boundary.test.ts
Labels: enhancement, 3.x

#31808 fix(nuxt): update middleware and layouts type declarations
  packages/nuxt/src/pages/module.ts
Labels: 3.x, bug

#31805 docs: fix casing
  docs/1.getting-started/06.styling.md
Labels: documentation, 3.x

#31876 feat(nuxt): add `<NuxtTime>` component for ssr-safe time display
  docs/3.api/1.components/13.nuxt-time.md
  package.json
  packages/nuxt/src/app/components/nuxt-time.vue
  packages/nuxt/src/core/nuxt.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/pages/components/nuxt-time.vue
  test/nuxt/nuxt-time.test.ts
Labels: enhancement, 3.x

#31820 feat(nuxt): add trailingSlash prop to NuxtLink
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: enhancement, 3.x

#31484 perf(nuxt): remove `oxc-parser` manual wasm fallback logic
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/utils/parse.ts
  pnpm-lock.yaml
  test/setup-env.ts
Labels: 3.x, bug

#31868 refactor: opt in to the new unplugin filter option
  packages/nuxt/src/components/plugins/component-names.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
  packages/nuxt/src/core/plugins/async-context.ts
  packages/nuxt/src/core/plugins/composable-keys.ts
  packages/nuxt/src/core/plugins/dev-only.ts
  packages/nuxt/src/core/plugins/layer-aliasing.ts
  packages/nuxt/src/core/plugins/prehydrate.ts
  packages/nuxt/src/core/plugins/tree-shake.ts
  packages/nuxt/src/core/plugins/unctx.ts
  packages/nuxt/src/head/plugins/unhead-imports.ts
  packages/nuxt/src/pages/plugins/route-injection.ts
  packages/nuxt/test/component-names.test.ts
  packages/nuxt/test/composable-keys.test.ts
  packages/nuxt/test/devonly.test.ts
  packages/nuxt/test/island-transform.test.ts
  packages/nuxt/test/prehydrate.test.ts
  packages/nuxt/test/route-injection.test.ts
  packages/nuxt/test/unctx-transform.test.ts
  packages/nuxt/test/unhead-imports.test.ts
  packages/webpack/src/plugins/dynamic-base.ts
Labels: 3.x, refactor

#31893 fix(nuxt): do not purge nuxt data if active `useNuxtData`
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31894 refactor(schema): do not generate types for `ConfigSchema`
  packages/kit/src/module/define.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/config/build.ts
  packages/schema/src/types/config.ts
  packages/schema/src/types/schema.ts
  packages/schema/src/utils/definition.ts
Labels: 3.x, refactor

#31907 fix(nuxt): use first existing modulesDir to store build cache files
  packages/nuxt/src/core/cache.ts
Labels: 3.x, bug

#31898 docs: fix grammar
  docs/1.getting-started/05.assets.md
Labels: documentation, 3.x

#31929 fix(nuxt): check if match exists with new unplugin filter
  packages/nuxt/src/components/plugins/component-names.ts
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
Labels: 3.x, bug

#31940 fix(nuxt): reinitialise stale async data
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31938 fix(nuxt): skip view transition if user agent is providing one
  packages/nuxt/src/app/plugins/view-transitions.client.ts
Labels: enhancement, 3.x

#31941 fix(nuxt): trigger `execute` when non-immediate fetch key changes
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31902 fix(nuxt): don't redirect when route has trailing slash
  packages/nuxt/src/pages/runtime/plugins/router.ts
  test/bundle.test.ts
Labels: 3.x, bug

#31946 fix(nuxt): ensure asyncData is initialised before effects run
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31952 docs: add missing article
  docs/2.guide/1.concepts/1.auto-imports.md
Labels: 3.x

#31945 fix(nuxt): skip view transition if user agent is providing one before defining `transition`
  packages/nuxt/src/app/plugins/view-transitions.client.ts
Labels: 3.x, bug
