Repository nuxt/nuxt, pull requests merged in 2025-09, with the labels that each got.

#33069 fix(nuxt): add validation for nuxt island reviver key
  packages/nuxt/src/app/plugins/revive-payload.server.ts
  packages/nuxt/src/app/plugins/utils.ts
  packages/nuxt/test/plugin-utils.test.ts
  test/bundle.test.ts
Labels: bug, 4.x

#33098 feat(kit,nuxt): add getLayerDirectories util and refactor to use it
  docs/3.api/5.kit/16.layers.md
  packages/kit/src/ignore.test.ts
  packages/kit/src/ignore.ts
  packages/kit/src/index.ts
  packages/kit/src/layers.ts
  packages/kit/src/module/install.ts
  packages/kit/src/template.ts
  packages/kit/test/generate-types.spec.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/types/config.ts
  packages/vite/src/vite.ts
Labels: enhancement, discussion, 4.x

#33130 chore: correct `rou3` github url
  docs/3.api/6.nuxt-config.md
  packages/schema/src/types/schema.ts
Labels: chore, 4.x

#33049 fix(nuxt): ignore #components import mapping inside packages that use it internally
  packages/nuxt/src/components/plugins/transform.ts
  packages/nuxt/test/components-transform.test.ts
  packages/nuxt/test/node_modules/package-fixture/package.json
  pnpm-workspace.yaml
Labels: bug, 4.x

#33133 fix(vite): remove explicit vite-node configuration of `deps.inline`
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
Labels: bug, 4.x

#33137 chore(kit): improve DX by displaying module name when possible
  packages/kit/src/module/define.ts
Labels: chore, 4.x

#33050 fix(nuxt): include core auto-imports from `imports:sources` in override warning
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
Labels: bug, 4.x

#33146 fix(nuxt): render relative importmap entry path if required
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  test/basic.test.ts
Labels: bug, 4.x

#33239 fix(kit): add default values for destructured references in addTypeTemplate hooks
  packages/kit/src/template.ts
Labels: bug, 4.x

#33265 docs: fix more links
  docs/1.getting-started/03.configuration.md
  docs/1.getting-started/05.assets.md
  docs/1.getting-started/08.seo-meta.md
  docs/1.getting-started/09.transitions.md
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/12.error-handling.md
  docs/1.getting-started/17.testing.md
  docs/2.guide/1.concepts/1.auto-imports.md
  docs/2.guide/1.concepts/3.rendering.md
  docs/2.guide/1.concepts/4.server-engine.md
  docs/2.guide/1.concepts/7.esm.md
  docs/2.guide/2.directory-structure/1.app/1.components.md
  docs/2.guide/2.directory-structure/1.app/1.pages.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/2.guide/2.directory-structure/1.shared.md
  docs/2.guide/3.going-further/3.modules.md
  docs/3.api/1.components/4.nuxt-link.md
  docs/3.api/2.composables/use-async-data.md
  docs/3.api/2.composables/use-fetch.md
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/3.utils/define-page-meta.md
  docs/3.api/5.kit/3.compatibility.md
  docs/3.api/5.kit/5.components.md
  docs/3.api/5.kit/8.layout.md
  docs/3.api/6.advanced/1.hooks.md
  docs/5.community/4.contribution.md
  docs/5.community/5.framework-contribution.md
  docs/5.community/6.roadmap.md
  docs/6.bridge/3.bridge-composition-api.md
  docs/6.bridge/5.nuxt3-compatible-api.md
  docs/7.migration/2.configuration.md
  lychee.toml
Labels: 4.x

#33308 fix(vite): duplicate server style imports
  packages/vite/src/plugins/ssr-styles.ts
Labels: bug, 4.x

#33317 docs: missing `useFetch` option reactivity
  docs/1.getting-started/10.data-fetching.md
  docs/3.api/2.composables/use-fetch.md
Labels: 4.x

#33333 fix(nuxt): do not relativise importmap if `cdnURL` is set
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
Labels: bug, 4.x

#33334 fix(nuxt): resolve aliases in `imports.dirs`
  packages/nuxt/src/imports/module.ts
Labels: bug, 4.x

#33336 docs: update `nuxt` command pages
  docs/3.api/4.commands/add.md
  docs/3.api/4.commands/analyze.md
  docs/3.api/4.commands/build.md
  docs/3.api/4.commands/dev.md
  docs/3.api/4.commands/generate.md
  docs/3.api/4.commands/init.md
  docs/3.api/4.commands/module.md
  docs/3.api/4.commands/prepare.md
  docs/3.api/4.commands/preview.md
  docs/3.api/4.commands/test.md
  docs/3.api/4.commands/typecheck.md
  docs/3.api/4.commands/upgrade.md
Labels: documentation, 4.x

#33340 chore(nuxt): align global components indent
  packages/nuxt/src/components/templates.ts
Labels: chore, 4.x

#33345 fix(nuxt): do not generate server placeholder components
  packages/nuxt/src/components/templates.ts
Labels: bug, 4.x

#33302 fix(nuxt): correctly handle island rendering error
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/core/runtime/nitro/handlers/island.ts
  test/basic.test.ts
  test/fixtures/basic/app/pages/index.vue
  test/fixtures/basic/app/pages/server-components/lost-page.server.vue
  test/nuxt/nuxt-island.test.ts
Labels: bug, 4.x
