Repository nuxt/nuxt, pull requests merged in 2025-06, with the labels that each got.

#32254 refactor(schema)!: remove config.schema.json export + defaults
  docs/3.api/6.nuxt-config.md
  lychee.toml
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/adhoc.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/dev.ts
  packages/schema/src/config/esbuild.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/generate.ts
  packages/schema/src/config/index.ts
  packages/schema/src/config/internal.ts
  packages/schema/src/config/nitro.ts
  packages/schema/src/config/postcss.ts
  packages/schema/src/config/router.ts
  packages/schema/src/config/typescript.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/config/webpack.ts
  packages/schema/src/types/builder-env/vite.ts
  packages/schema/src/types/components.ts
  packages/schema/src/types/head.ts
  packages/schema/src/types/hooks.ts
  packages/schema/src/types/imports.ts
  packages/schema/src/types/schema.ts
  packages/schema/src/utils/definition.ts
Labels: 3.x, refactor

#32255 fix(nuxt,schema)!: remove support for `compatibilityVersion: 3`
  packages/kit/src/template.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/head/runtime/composables.ts
  packages/nuxt/src/head/runtime/composables/v3.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/test/shared-dir-config.test.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/experimental.ts
  packages/schema/test/folder-structure.spec.ts
  tsconfig.json
Labels: 3.x, bug

#32232 fix(nuxt): access `asyncData` state from nuxt app instance
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#32257 fix(kit,nuxt,schema,vite)!: remove support for some deprecated options
  packages/kit/src/loader/config.ts
  packages/nuxt/src/core/cache.ts
  packages/nuxt/src/core/runtime/nitro/handlers/island.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/common.ts
  packages/schema/src/types/schema.ts
  packages/vite/src/utils/warmup.ts
  test/basic.test.ts
Labels: 3.x, bug

#32260 fix(nuxt): make patterns relative to `srcDir` in `buildCache`
  packages/nuxt/src/core/cache.ts
Labels: 3.x

#32266 fix(nuxt): return non-existent route component in RouteProvider
  packages/nuxt/src/app/components/route-provider.ts
Labels: 3.x, bug

#32270 docs: fix wrong `alert` with `warning` in `/guide/pages`
  docs/2.guide/2.directory-structure/1.pages.md
Labels: documentation, 3.x

#32119 fix(nuxt)!: remove public and assets alias to fix relative imports from other sources
  packages/kit/test/load-nuxt-config.spec.ts
  packages/schema/src/config/common.ts
  packages/vite/src/vite.ts
  packages/webpack/src/presets/base.ts
Labels: 3.x, bug

#32045 refactor(nuxt,schema): use oxc for `onPrehydrate` transform
  packages/nuxt/package.json
  packages/nuxt/src/core/plugins/prehydrate.ts
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/test/prehydrate.test.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/index.ts
  packages/schema/src/config/oxc.ts
  packages/schema/src/types/schema.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/bundle.test.ts
Labels: 3.x, refactor

#32278 fix(webpack): update dynamic require pattern
  packages/webpack/src/nitro/plugins/dynamic-require.ts
  packages/webpack/src/webpack.ts
Labels: 3.x, bug

#32281 fix(webpack): use plugin for rollup-compatible dynamic imports
  packages/webpack/src/nitro/plugins/dynamic-require.ts
  packages/webpack/src/plugins/rollup-compat-dynamic-import.ts
  packages/webpack/src/presets/base.ts
  packages/webpack/src/webpack.ts
Labels: 3.x, bug

#32297 fix(nuxt): allow camelCase for lazy hydration attributes
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
  packages/nuxt/test/component-loader.test.ts
Labels: 3.x, bug

#32348 docs: update v4 docs with new folder structure
  docs/1.getting-started/10.data-fetching.md
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/3.rendering.md
  docs/2.guide/2.directory-structure/1.app/.navigation.yml
  docs/2.guide/2.directory-structure/1.app/1.assets.md
  docs/2.guide/2.directory-structure/1.app/1.components.md
  docs/2.guide/2.directory-structure/1.app/1.composables.md
  docs/2.guide/2.directory-structure/1.app/1.layouts.md
  docs/2.guide/2.directory-structure/1.app/1.middleware.md
  docs/2.guide/2.directory-structure/1.app/1.pages.md
  docs/2.guide/2.directory-structure/1.app/1.plugins.md
  docs/2.guide/2.directory-structure/1.app/1.utils.md
  docs/2.guide/2.directory-structure/1.app/3.app-config.md
  docs/2.guide/2.directory-structure/1.app/3.app.md
  docs/2.guide/2.directory-structure/1.app/3.error.md
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/4.recipes/1.custom-routing.md
  docs/3.api/3.utils/define-page-meta.md
  docs/3.api/6.nuxt-config.md
  docs/7.migration/7.component-options.md
  packages/schema/src/config/app.ts
  packages/schema/src/types/schema.ts
Labels: documentation, 3.x

#32289 feat(kit): support single import in `addServerImports`
  docs/3.api/5.kit/11.nitro.md
  docs/3.api/5.kit/4.autoimports.md
  packages/kit/src/nitro.ts
Labels: enhancement, 3.x

#32324 fix(nuxt): generate correct types for async data defaults based on `nuxt.config`
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#32355 fix(schema)!: remove top level generate option
  docs/1.getting-started/18.upgrade.md
  docs/3.api/6.nuxt-config.md
  packages/nuxt/src/core/cache.ts
  packages/nuxt/src/core/nitro.ts
  packages/schema/src/config/generate.ts
  packages/schema/src/types/schema.ts
Labels: 3.x, bug

#32239 fix(nuxt): align scroll behavior with page transition completion
  packages/nuxt/src/pages/runtime/page.ts
  test/nuxt/router.option.test.ts
Labels: 3.x, bug

#32388 chore: rename deprecated vitest `workspace` to `projects`
  vitest.config.ts
Labels: chore, 4.x

#32393 fix(nuxt): when `<NuxtLink>` renders native anchor tag, handle click with `navigateTo`
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: bug, 4.x

#32358 fix(nuxt): pass `output.generatedCode.symbols: true` to nitro for rolldown-vite
  packages/nuxt/src/core/nitro.ts
Labels: bug, 4.x

#32396 feat(nuxt): add `onWatcherCleanup` to imports presets
  packages/nuxt/src/imports/presets.ts
Labels: enhancement, 4.x

#32427 chore: mention `bun.lock` for lockfile
  docs/2.guide/3.going-further/1.experimental-features.md
  docs/2.guide/3.going-further/11.nightly-release-channel.md
  packages/nuxt/src/core/cache.ts
Labels: chore, 4.x

#32428 fix(nuxt): lazily access runtimeConfig
  packages/nuxt/src/core/templates.ts
Labels: bug, 4.x

#32415 docs: remove kit playground auto-import note
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#32243 docs: migrate to `h3js`
  docs/1.getting-started/13.server.md
  docs/2.guide/1.concepts/4.server-engine.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/3.api/2.composables/use-cookie.md
  docs/3.api/2.composables/use-nuxt-app.md
  docs/3.api/6.advanced/1.hooks.md
Labels: documentation, 3.x

#32361 docs: mention that NuxtLink encodes query params
  docs/3.api/1.components/4.nuxt-link.md
Labels: documentation, 4.x

#32421 fix(nuxt): use rollup to calculate island component filenames
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
Labels: bug, 4.x

#32417 perf(vite): communicate with vite-node via internal socket
  packages/vite/src/runtime/client.manifest.mjs
  packages/vite/src/runtime/vite-node-shared.mjs
  packages/vite/src/runtime/vite-node.mjs
  packages/vite/src/server.ts
  packages/vite/src/vite-node.ts
Labels: performance, 4.x

#30665 feat(kit,nuxt,schema): separate ts projects for node/app/nitro
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/1.concepts/8.typescript.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/2.guide/2.directory-structure/3.tsconfig.md
  docs/3.api/5.kit/6.context.md
  docs/3.api/6.advanced/1.hooks.md
  docs/3.api/6.nuxt-config.md
  docs/6.bridge/2.typescript.md
  docs/7.migration/2.configuration.md
  package.json
  packages/kit/package.json
  packages/kit/src/template.ts
  packages/nuxt/package.json
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/types/augments.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  packages/schema/package.json
  packages/schema/src/types/hooks.ts
  packages/schema/src/types/schema.ts
  packages/vite/package.json
  playground/server/tsconfig.json
  playground/tsconfig.json
  pnpm-lock.yaml
  test/fixtures/basic-types/app/app-types.ts
  test/fixtures/basic-types/config-types.ts
  test/fixtures/basic-types/nuxt.config.ts
  test/fixtures/basic-types/package.json
  test/fixtures/basic-types/server/tsconfig.json
  test/fixtures/basic-types/tsconfig.json
  test/fixtures/basic/server/tsconfig.json
  test/fixtures/basic/tsconfig.json
  test/fixtures/hmr/tsconfig.json
  test/fixtures/minimal-pages/tsconfig.json
  test/fixtures/minimal-types/app-types.ts
  test/fixtures/minimal-types/app.vue
  test/fixtures/minimal-types/nuxt.config.ts
  test/fixtures/minimal-types/package.json
  test/fixtures/minimal-types/tsconfig.json
  test/fixtures/minimal/tsconfig.json
  test/fixtures/runtime-compiler/tsconfig.json
  test/fixtures/spa-loader/tsconfig.json
  test/fixtures/suspense/tsconfig.json
  test/nuxt/tsconfig.json
  tsconfig.json
Labels: 3.x

#31192 feat(nuxt): support lazy hydration macros
  docs/2.guide/2.directory-structure/1.app/1.components.md
  docs/3.api/3.utils/define-lazy-hydration-component.md
  packages/nuxt/src/app/composables/lazy-hydration.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/lazy-hydration-macro-transform.ts
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
  packages/nuxt/src/components/runtime/lazy-hydrated-component.ts
  packages/nuxt/src/imports/presets.ts
  packages/nuxt/test/lazy-hydration-macro-transform.test.ts
  test/basic.test.ts
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/index.vue
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/macro/index.vue
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/macro/model-event.vue
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/macro/time.vue
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/model-event.vue
  test/fixtures/basic/app/pages/lazy-import-components/delayed-hydration/time.vue
  test/fixtures/basic/app/pages/lazy-import-components/index.vue
Labels: enhancement, 3.x

#32487 fix(kit): do not skip layer with defined `srcDir`
  packages/kit/src/template.ts
Labels: bug, 4.x

#32489 docs: update `.nuxtignore` examples for v4 structure
  docs/2.guide/2.directory-structure/2.nuxtignore.md
Labels: documentation, 4.x

#32499 fix(nuxt): skip external `<NuxtLink>`'s custom on click handler
  packages/nuxt/src/app/components/nuxt-link.ts
Labels: bug, 4.x

#32503 docs: adjust wording to reduce confusion in lifecycle section
  docs/2.guide/1.concepts/10.nuxt-lifecycle.md
Labels: documentation, 4.x

#32513 docs: Update 1.plugins.md
  docs/2.guide/2.directory-structure/1.plugins.md
Labels: documentation, 3.x
