Repository nuxt/nuxt, pull requests merged in 2025-02, with the labels that each got.

#30830 docs: remove backslashes in `spaLoadingTemplate` example
  packages/schema/src/config/app.ts
Labels: 3.x, bug

#30832 fix(nuxt): ensure `<NuxtLayout>` `fallback` prop is typed
  packages/nuxt/src/app/components/nuxt-layout.ts
  test/fixtures/basic-types/types.ts
Labels: 3.x, bug

#30768 fix(nuxt): assign slot to be rendered for client components
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  test/basic.test.ts
Labels: 3.x, bug

#30742 test: add benchmarks for dev server initial build
  packages/kit/test/write-types.bench.ts
  packages/nuxt/test/build.bench.ts
  packages/nuxt/test/load-nuxt.bench.ts
Labels: 3.x, test

#30866 fix(ui-templates): fix examples link and add bluesky
  packages/ui-templates/templates/welcome/index.html
Labels: 3.x, chore

#30868 chore: remove second version of vitest
  pnpm-lock.yaml
  test/fixtures/basic-types/package.json
Labels: 3.x, chore

#30887 fix(nuxt,vite): do not override vite import conditions
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/vite/src/client.ts
Labels: 3.x, bug

#30578 feat(nuxt): granular debug options
  packages/kit/src/module/define.ts
  packages/nuxt/src/app/plugins/debug-hooks.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/module.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/index.ts
  packages/schema/src/types/config.ts
  packages/schema/src/types/debug.ts
  packages/webpack/src/presets/vue.ts
Labels: enhancement, 3.x

#30704 feat(nuxt): add type hints for `NuxtPage`
  packages/nuxt/src/app/index.ts
  packages/nuxt/src/app/types.ts
  packages/nuxt/src/pages/runtime/index.ts
  packages/nuxt/src/pages/runtime/page.ts
Labels: enhancement, 3.x

#30807 fix(nuxt): prevent cache reset on excluded pages and solve transition warning
  nuxt.config.ts
  packages/nuxt/src/app/components/route-provider.ts
  packages/nuxt/src/pages/runtime/page.ts
  test/nuxt/composables.test.ts
  test/nuxt/nuxt-page.test.ts
  test/runtime/app/router.options.ts
  vitest.nuxt.config.ts
Labels: 3.x, bug

#30555 feat(nuxt): support tracking changes to nuxt options by modules
  packages/kit/src/module/install.ts
  packages/nuxt/package.json
  packages/nuxt/src/core/nuxt.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/internal.ts
  packages/schema/src/index.ts
  packages/schema/src/types/debug.ts
  packages/schema/src/types/nuxt.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x

#30425 fix(nuxt): remove `div` wrapper in client-only pages
  packages/nuxt/src/components/runtime/client-component.ts
  test/bundle.test.ts
  test/nuxt/client-only.test.ts
  test/nuxt/client.test.ts
Labels: 3.x, bug

#30726 docs: add nuxt lifecycle
  docs/2.guide/1.concepts/10.nuxt-lifecycle.md
Labels: documentation, 3.x

#30781 docs: add additional information about `NuxtPage`
  docs/3.api/1.components/2.nuxt-page.md
Labels: documentation, 3.x

#30876 docs: improve `navigateTo` docs with clearer structure and examples
  docs/3.api/3.utils/navigate-to.md
Labels: documentation, 3.x

#30858 docs: add auto import info about shared utils
  docs/2.guide/2.directory-structure/1.shared.md
Labels: documentation, 3.x

#30332 feat(nuxt): allow disabling auto-imported polyfills
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/imports/presets.ts
  packages/schema/src/types/imports.ts
  test/nuxt/polyfills.test.ts
  vitest.nuxt.config.ts
Labels: enhancement, 3.x

#30844 feat(schema): add runtime + internal type validation
  packages/nuxt/src/core/templates.ts
  packages/schema/package.json
  packages/schema/src/config/adhoc.ts
  packages/schema/src/config/app.ts
  packages/schema/src/config/build.ts
  packages/schema/src/config/common.ts
  packages/schema/src/config/dev.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/generate.ts
  packages/schema/src/config/index.ts
  packages/schema/src/config/internal.ts
  packages/schema/src/config/nitro.ts
  packages/schema/src/config/postcss.ts
  packages/schema/src/config/router.ts
  packages/schema/src/config/typescript.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/config/webpack.ts
  packages/schema/src/types/module.ts
  packages/schema/src/utils/definition.ts
  pnpm-lock.yaml
Labels: enhancement, 3.x

#30922 fix(vite): use `resolveId` from `vite-node` to resolve deps
  packages/vite/package.json
  packages/vite/src/runtime/vite-node.mjs
  packages/vite/src/utils/external.ts
  packages/vite/src/vite-node.ts
  pnpm-lock.yaml
Labels: 3.x, bug

#30923 fix(vite): use `resolveId` from vite-node to resolve deps
  packages/vite/src/runtime/vite-node.mjs
  packages/vite/src/vite-node.ts
Labels: 3.x, bug

#30918 fix(nuxt): delete existing properties on app config template's HMR
  packages/nuxt/src/app/config.ts
  packages/nuxt/src/core/templates.ts
Labels: 3.x, bug

#27672 feat(kit,nuxt,schema): support experimental decorators syntax
  docs/2.guide/3.going-further/1.experimental-features.md
  packages/kit/src/template.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/plugins/prehydrate.ts
  packages/nuxt/src/core/utils/parse.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/build.config.ts
  packages/schema/package.json
  packages/schema/src/config/esbuild.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/index.ts
  packages/schema/src/config/vite.ts
  packages/schema/src/config/webpack.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/pages/experimental/decorators.vue
  test/fixtures/basic/server/api/experimental/decorators.ts
Labels: enhancement, 3.x, 🔨 p3-minor

#30510 feat(kit,nuxt): allow multiple nuxts to run in one process
  packages/kit/src/context.ts
  packages/kit/src/index.ts
  packages/kit/src/loader/nuxt.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/load-nuxt.test.ts
  packages/schema/src/types/nuxt.ts
Labels: enhancement, 3.x

#30948 feat(kit): add named layer aliases
  docs/1.getting-started/9.layers.md
  docs/2.guide/3.going-further/7.layers.md
  packages/kit/src/loader/config.ts
  packages/kit/test/layer-fixture/layers/test/assets/foo.js
  packages/kit/test/layer-fixture/layers/test/nuxt.config.ts
  packages/kit/test/layer-fixture/nuxt.config.ts
  packages/kit/test/load-nuxt-config.spec.ts
Labels: enhancement, 3.x

#30963 docs: fix typo
  docs/2.guide/1.concepts/10.nuxt-lifecycle.md
Labels: documentation, 3.x

#30959 fix(schema): make `app.head.meta` config undefined-friendly
  packages/schema/src/config/app.ts
Labels: 3.x, bug

#30843 fix(nuxt): make `shared/` directories available within layers
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/test/shared-dir-config.test.ts
Labels: 3.x, bug

#30971 docs: fix typo
  docs/2.guide/3.going-further/2.hooks.md
Labels: documentation, 3.x

#30970 docs: add tips on how to override layers aliases
  docs/1.getting-started/9.layers.md
Labels: documentation, 3.x

#30986 feat(kit,nuxt,vite): `directoryToURL` to normalise paths
  packages/kit/src/index.ts
  packages/kit/src/internal/esm.ts
  packages/kit/src/loader/config.ts
  packages/kit/src/loader/nuxt.ts
  packages/kit/src/module/install.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/utils/types.ts
  packages/nuxt/src/head/module.ts
  packages/nuxt/src/imports/module.ts
  packages/vite/src/server.ts
Labels: enhancement, 3.x

#30992 chore: use logical or assignment
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/components/runtime/client-component.ts
  packages/nuxt/src/core/plugins/composable-keys.ts
Labels: 3.x, refactor

#30989 feat(nuxt): allow forcing `start`/`set` in loading indicator
  docs/3.api/2.composables/use-loading-indicator.md
  packages/nuxt/src/app/composables/loading-indicator.ts
  test/nuxt/composables.test.ts
Labels: enhancement, 3.x

#31004 refactor(nuxt): prefer logical assignment operators
  debug/plugins/timings-babel.mjs
  eslint.config.mjs
  packages/kit/src/loader/config.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/error.ts
  packages/nuxt/src/app/composables/loading-indicator.ts
  packages/nuxt/src/app/composables/once.ts
  packages/nuxt/src/app/composables/payload.ts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/app/composables/route-announcer.ts
  packages/nuxt/src/app/composables/router.ts
  packages/nuxt/src/app/config.ts
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/revive-payload.client.ts
  packages/nuxt/src/app/plugins/router.ts
  packages/nuxt/src/components/runtime/client-component.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/plugin-metadata.ts
  packages/nuxt/src/core/runtime/nitro/app-config.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/imports/module.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/plugins/route-injection.ts
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/vite/src/manifest.ts
  packages/webpack/src/plugins/vue/client.ts
  packages/webpack/src/presets/style.ts
  scripts/_utils.ts
  test/basic.test.ts
Labels: 3.x, refactor

#31014 fix: use tsx loader for jsx as well
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
Labels: 3.x, bug

#31040 fix: remove unimplemented `page:transition:start` type
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, chore

#31035 fix(kit): expose Nuxt module dependency errors
  packages/kit/src/module/install.ts
Labels: 3.x, bug

#31020 fix(nuxt): correct css order for layers
  eslint.config.mjs
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/test/__snapshots__/treeshake-client.test.ts.snap
  packages/nuxt/test/components-fixture/components/HelloWorld.vue
  packages/nuxt/test/components-fixture/components/Nuxt3.client.vue
  packages/nuxt/test/components-fixture/components/Nuxt3.server.vue
  packages/nuxt/test/components-fixture/components/client/ComponentWithProps.vue
  packages/nuxt/test/components-fixture/components/client/WithClientOnlySetup.vue
  packages/nuxt/test/components-fixture/components/global/Glob.vue
  packages/nuxt/test/components-fixture/components/islands/Isle.vue
  packages/nuxt/test/components-fixture/components/parent-folder/index.server.vue
  packages/nuxt/test/components-fixture/components/same-name/same/Same.vue
  packages/nuxt/test/components-fixture/components/some-glob.global.vue
  packages/nuxt/test/components-fixture/components/some.island.vue
  packages/nuxt/test/fixture/scope-tracker.ts
  packages/nuxt/test/layers-fixture/custom/nuxt.config.ts
  packages/nuxt/test/layers-fixture/layers/auto/nuxt.config.ts
  packages/nuxt/test/layers-fixture/nuxt.config.ts
  packages/nuxt/test/load-nuxt.test.ts
  packages/nuxt/test/parse.test.ts
  packages/nuxt/test/scan-components.test.ts
  packages/nuxt/test/treeshake-client.test.ts
  packages/nuxt/test/utils.ts
Labels: 3.x, bug

#31005 docs: update nuxt context section in 6.nuxt-app.md
  docs/2.guide/3.going-further/6.nuxt-app.md
Labels: documentation, 3.x

#30973 fix(nuxt): decode URI components in cache driver methods
  packages/nuxt/src/core/runtime/nitro/cache-driver.js
Labels: 3.x, bug

#30999 docs: add `port` option to preview command
  docs/3.api/4.commands/preview.md
Labels: documentation, 3.x

#31072 fix(nuxt): use `_` for NuxtIsland name on server pages
  packages/nuxt/src/components/runtime/server-component.ts
  packages/nuxt/src/components/templates.ts
  test/basic.test.ts
Labels: 3.x, chore

#31077 docs: Removal of Nuxt 2 mention from the Table of Contents
  README.md
Labels: documentation, 3.x

#31087 fix(nuxt): use `ohash` to calculate legacy async data key without hash
  packages/nuxt/src/app/composables/component.ts
Labels: 3.x, bug

#31088 perf(nuxt): remove duplicated nitro alias resolution
  packages/nuxt/src/core/nitro.ts
Labels: 3.x, performance

#31091 fix(nuxt,schema): resolve `shared` dir from config
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/imports/module.ts
  packages/schema/src/config/common.ts
Labels: 3.x, bug

#31095 docs: ensure the hyperlink points to the releases page
  docs/5.community/7.changelog.md
Labels: documentation, 3.x

#31089 fix(kit,schema): set esbuild target for experimental decorators
  packages/kit/src/template.ts
  packages/schema/src/config/esbuild.ts
Labels: 3.x, bug

#31094 perf(nuxt): return island response earlier
  packages/nuxt/src/core/runtime/nitro/renderer.ts
Labels: 3.x, performance

#31090 feat(nuxt): allow specifying glob patterns for `pages`
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/utils.ts
  packages/schema/src/config/adhoc.ts
Labels: enhancement, 3.x

#31093 docs: add nuxtrc
  docs/2.guide/2.directory-structure/2.nuxtrc.md
  docs/2.guide/2.directory-structure/3.nuxt-config.md
Labels: documentation, 3.x

#31112 docs: fix typo in example command
  docs/2.guide/2.directory-structure/2.env.md
Labels: documentation, 3.x

#31083 refactor(nuxt): update to `noScripts` route rule
  docs/1.getting-started/8.server.md
  docs/2.guide/1.concepts/3.rendering.md
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/runtime/nitro/renderer.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  test/fixtures/basic/nuxt.config.ts
Labels: documentation, refactor, 4.x

#31124 perf(nuxt): migrate to use `exsolve` for module resolution
  packages/kit/package.json
  packages/kit/src/internal/esm.ts
  packages/kit/src/loader/config.ts
  packages/kit/src/module/install.ts
  packages/kit/src/plugin.ts
  packages/kit/src/resolve.ts
  packages/kit/src/template.ts
  packages/nuxt/package.json
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/resolve-deep-imports.ts
  packages/nuxt/src/core/schema.ts
  packages/nuxt/src/core/utils/types.ts
  packages/nuxt/src/head/module.ts
  pnpm-lock.yaml
  test/fixtures/basic/custom-modules/subpath/index.ts
  test/fixtures/basic/custom-modules/subpath/module.ts
  test/fixtures/basic/nuxt.config.ts
Labels: 3.x, performance

#31118 test: add benchmarks for html render + vite client build
  .github/workflows/ci.yml
  packages/nuxt/test/build-plugins.bench.ts
  packages/nuxt/test/build.bench.ts
  packages/nuxt/test/load-nuxt.bench.ts
  packages/nuxt/test/nitro/render-index.ts
  packages/nuxt/test/render.bench.ts
Labels: 3.x, test

#31104 fix(nuxt): ensure `NuxtLink` `default` slot is typed
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/test/nuxt-link.test.ts
Labels: 3.x, bug

#31131 chore: re-organize runtime/nitro directory
  docs/1.getting-started/12.upgrade.md
  docs/3.api/6.advanced/1.hooks.md
  eslint.config.mjs
  packages/nuxt/.gitignore
  packages/nuxt/src/app/types.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/runtime/nitro/handlers/error.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/core/runtime/nitro/middleware/no-ssr.ts
  packages/nuxt/src/core/runtime/nitro/plugins/dev-server-logs.ts
  packages/nuxt/src/core/runtime/nitro/utils/app-config.ts
  packages/nuxt/src/core/runtime/nitro/utils/build-files.ts
  packages/nuxt/src/core/runtime/nitro/utils/cache-driver.js
  packages/nuxt/src/core/runtime/nitro/utils/cache.ts
  packages/nuxt/src/core/runtime/nitro/utils/config.ts
  packages/nuxt/src/core/runtime/nitro/utils/paths.ts
  packages/nuxt/src/core/runtime/nitro/utils/payload.ts
  packages/nuxt/src/core/templates.ts
  packages/ui-templates/lib/render.ts
  test/basic.test.ts
Labels: 3.x, refactor

#31156 fix(nuxt): warn when definePageMeta does not receive an object
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, dx, bug

#26468 feat(nuxt): delayed/lazy hydration support
  docs/2.guide/2.directory-structure/1.components.md
  packages/nuxt/package.json
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/lazy-hydration-transform.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/runtime/lazy-hydrated-component.ts
  packages/nuxt/src/components/templates.ts
  packages/nuxt/test/component-loader.test.ts
  packages/schema/src/config/experimental.ts
  pnpm-lock.yaml
  test/basic.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/components/DelayedComponent.vue
  test/fixtures/basic/components/DelayedModel.vue
  test/fixtures/basic/components/EventView.vue
  test/fixtures/basic/pages/lazy-import-components/index.vue
  test/fixtures/basic/pages/lazy-import-components/model-event.vue
  test/fixtures/basic/pages/lazy-import-components/time.vue
Labels: enhancement, 3.x, 4.x

#31164 feat(vite): add vite's modulepreload polyfill
  packages/vite/src/client.ts
  packages/vite/src/plugins/dev-ssr-css.ts
  packages/vite/src/plugins/module-preload-polyfill.ts
  packages/vite/src/plugins/paths.ts
  packages/vite/src/plugins/type-check.ts
  packages/vite/src/vite-node.ts
  test/bundle.test.ts
Labels: enhancement, 3.x
