Repository nuxt/nuxt, pull requests merged in 2025-05, with the labels that each got.

#31963 fix(nuxt): improve hashing for complex body in `useFetch`
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31964 fix(nuxt): immediately call asyncData within client-only components
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/types/augments.d.ts
  packages/nuxt/src/components/runtime/client-component.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31966 fix(nuxt): don't render errors if event is already handled
  packages/nuxt/src/core/runtime/nitro/handlers/error.ts
Labels: 3.x, bug

#31965 fix(nuxt): track whether need to reinit asyncData separately from deps
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/nuxt.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#31950 fix(nuxt): preserve params/meta/matched when navigating with Route object
  packages/nuxt/src/app/plugins/router.ts
Labels: 3.x, bug

#31914 fix(nuxt): respect the scroll behavior set by `scrollToTop`
  packages/nuxt/src/pages/runtime/page.ts
  packages/nuxt/src/pages/runtime/router.options.ts
  test/basic.test.ts
  test/fixtures/basic/pages/route-scroll-behavior/scroll-to-top.vue
  test/fixtures/basic/pages/route-scroll-behavior/scroll-to-top/[id].vue
  test/nuxt/loading-indicator.test.ts
Labels: 3.x, bug

#31969 fix(nuxt): load live data from `vfs` even if a file exists in `buildDir`
  packages/nuxt/src/core/plugins/virtual.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug

#31971 perf(nuxt): tree-shake router's `handleHotUpdate` in production
  packages/nuxt/src/pages/runtime/plugins/router.ts
Labels: 3.x, performance

#31793 docs: improve `@nuxt/kit` documentation
  docs/3.api/5.kit/1.modules.md
  docs/3.api/5.kit/10.runtime-config.md
  docs/3.api/5.kit/10.templates.md
  docs/3.api/5.kit/11.nitro.md
  docs/3.api/5.kit/12.resolving.md
  docs/3.api/5.kit/13.logging.md
  docs/3.api/5.kit/14.builder.md
  docs/3.api/5.kit/2.programmatic.md
  docs/3.api/5.kit/3.compatibility.md
  docs/3.api/5.kit/4.autoimports.md
  docs/3.api/5.kit/5.components.md
  docs/3.api/5.kit/6.context.md
  docs/3.api/5.kit/7.pages.md
  docs/3.api/5.kit/8.layout.md
  docs/3.api/5.kit/9.plugins.md
Labels: documentation, 3.x

#31967 fix(nuxt): short circuit middleware when validate returns false
  docs/1.getting-started/07.routing.md
  packages/nuxt/src/pages/runtime/plugins/router.ts
  packages/nuxt/src/pages/runtime/validate.ts
  test/fixtures/basic/pages/catchall/[...slug].vue
Labels: 3.x, bug

#31977 feat(docs): add events page
  docs/2.guide/3.going-further/1.events.md
  docs/2.guide/3.going-further/2.hooks.md
Labels: enhancement, 3.x

#31987 fix(nuxt): ensure `useAsyncData` reactive to `key` changes when `immediate: false`
  docs/1.getting-started/18.upgrade.md
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/core/templates.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/types/schema.ts
  test/nuxt/composables.test.ts
  vitest.nuxt.config.ts
Labels: 3.x, bug

#32002 fix(nuxt): preload async layouts
  packages/nuxt/src/app/composables/preload.ts
  packages/nuxt/src/pages/runtime/plugins/prefetch.client.ts
  test/bundle.test.ts
Labels: 3.x, bug

#32013 fix(nuxt): handle File within `FormData`
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#32020 fix(schema): respect user-provided `ignore` patterns
  packages/schema/src/config/common.ts
Labels: 3.x, bug

#32024 docs: fix module initialization command for pnpm
  docs/2.guide/3.going-further/3.modules.md
Labels: documentation, 3.x

#32022 fix(nuxt): allow loading virtual files with query params
  packages/nuxt/src/core/plugins/virtual.ts
Labels: 3.x, bug

#32029 docs: provide nuxt installation guide with deno
  docs/1.getting-started/02.installation.md
Labels: documentation, 3.x

#32019 fix(nuxt): don't use reactive key for `useFetch` with `watch: false`
  packages/nuxt/src/app/composables/fetch.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#32003 fix(nuxt): do not clear data if custom `getCachedData` is provided
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#32038 fix(nuxt): provide nuxtApp for server handler
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#32043 docs: add codeblock closing tag
  docs/1.getting-started/02.installation.md
Labels: documentation, 3.x

#32041 fix(vite): strip queries when skipping vite transform middleware
  packages/vite/src/client.ts
Labels: 3.x, bug

#32048 fix(nuxt): sort hash sources and files
  packages/nuxt/src/core/cache.ts
Labels: 3.x, bug

#32063 docs: tweak nuxt doc
  docs/1.getting-started/01.introduction.md
  docs/1.getting-started/03.configuration.md
  docs/1.getting-started/15.prerendering.md
  docs/1.getting-started/16.deployment.md
  docs/2.guide/1.concepts/3.rendering.md
  docs/2.guide/1.concepts/4.server-engine.md
  docs/2.guide/2.directory-structure/1.server.md
  docs/3.api/2.composables/use-request-url.md
  docs/3.api/3.utils/navigate-to.md
  docs/3.api/5.kit/11.nitro.md
  docs/3.api/5.kit/7.pages.md
  docs/3.api/6.advanced/1.hooks.md
  packages/nuxt/src/core/external-config-files.ts
  packages/schema/src/config/nitro.ts
  packages/schema/src/types/schema.ts
Labels: documentation, 3.x

#32069 docs: improve sentence
  docs/1.getting-started/18.upgrade.md
  docs/2.guide/3.going-further/11.nightly-release-channel.md
Labels: documentation, 3.x

#32052 perf(nuxt): pre-calculate extension glob before app resolution
  packages/nuxt/src/core/app.ts
Labels: 3.x, chore

#32015 perf(nuxt): improve islands client components chunks
  packages/nuxt/src/app/components/nuxt-teleport-island-component.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/islands-transform.ts
Labels: enhancement, 3.x

#32064 fix(nuxt): do not suppress chunk import error
  packages/nuxt/src/app/nuxt.ts
Labels: 3.x, bug

#32078 docs: use emphasis instead of quotes
  docs/1.getting-started/18.upgrade.md
Labels: documentation, 3.x

#32090 chore: remove unneeded JSdoc comments
  packages/nuxt/src/app/composables/asyncData.ts
  packages/nuxt/src/app/composables/fetch.ts
Labels: 3.x, chore

#32054 docs: update `useNuxtData` default return to `undefined`
  docs/3.api/2.composables/use-nuxt-data.md
Labels: documentation, 3.x

#32095 docs: capitalise headings
  docs/1.getting-started/10.data-fetching.md
Labels: documentation, 3.x

#32101 fix(nuxt): do not await lazy asyncData inside `<ClientOnly>`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#32099 fix(nuxt): respect cachedData with multiple asyncData calls
  packages/nuxt/src/app/composables/asyncData.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#32096 fix(nuxt): clear async data after a tick
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#32092 fix(nuxt): support reactive keys in `useLazyAsyncData`
  packages/nuxt/src/app/composables/asyncData.ts
Labels: 3.x, bug

#32121 test: use vitest workspaces
  .github/workflows/autofix.yml
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  vitest.config.ts
  vitest.nuxt.config.ts
Labels: 3.x, test

#32100 fix(nuxt): clear previous head in island-renderer
  packages/nuxt/src/app/components/island-renderer.ts
  test/basic.test.ts
  test/fixtures/basic/plugins/my-plugin.ts
Labels: 3.x, bug

#32110 perf(nuxt): use Set for circular dep plugin to use const time
  packages/nuxt/src/core/app.ts
Labels: 3.x, performance

#31990 fix(schema): remove nitro options from `DeepPartial`
  packages/schema/src/types/config.ts
Labels: 3.x, bug

#32133 perf: refactor Array.includes checks to use Sets
  packages/kit/src/loader/config.ts
  packages/kit/src/resolve.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
  packages/nuxt/src/components/module.ts
  packages/nuxt/src/components/plugins/loader.ts
  packages/nuxt/src/components/plugins/transform.ts
  packages/nuxt/src/components/scan.ts
  packages/nuxt/src/core/app.ts
  packages/nuxt/src/core/builder.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/pages/utils.ts
  packages/nuxt/test/page-metadata.test.ts
  packages/schema/src/config/experimental.ts
  packages/schema/src/config/typescript.ts
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/nitro/plugins/dynamic-require.ts
Labels: 3.x, performance

#32134 fix(nuxt): ensure legacy async data remains reactive
  packages/nuxt/src/app/composables/component.ts
  test/nuxt/composables.test.ts
Labels: 3.x, bug

#32130 fix(vite): do not replace `global` with `globalThis`
  packages/nuxt/src/app/entry.ts
  packages/nuxt/src/core/templates.ts
  packages/vite/src/vite.ts
Labels: 3.x, bug

#32138 test(nuxt): add unit tests for watch strategies
  packages/nuxt/test/builder.test.ts
Labels: 3.x, test

#32137 fix(nuxt): suppress client-side errors by crawlers
  packages/nuxt/src/app/components/nuxt-root.vue
Labels: 3.x, bug

#24673 fix(nuxt): use fresh route when `<NuxtLayout>` first renders
  packages/nuxt/src/app/components/nuxt-layout.ts
  test/bundle.test.ts
  test/nuxt/nuxt-layout.test.ts
  test/runtime/app/router.options.ts
Labels: 3.x, bug

#32142 test: use fake timers instead of `setTimeout` mock
  test/nuxt/composables.test.ts
Labels: 3.x, test

#32148 docs: use node v20 for minimum requirement for nuxt setup
  docs/1.getting-started/02.installation.md
Labels: documentation, 3.x

#32152 perf(nuxt): rewrite all `ref` with primitive values to be `shallowRef`
  .gitignore
  packages/nuxt/src/app/components/client-fallback.client.ts
  packages/nuxt/src/app/components/client-fallback.server.ts
  packages/nuxt/src/app/components/client-only.ts
  packages/nuxt/src/app/components/nuxt-island.ts
  packages/nuxt/src/app/components/nuxt-layout.ts
  packages/nuxt/src/app/components/nuxt-link.ts
  packages/nuxt/src/components/runtime/client-component.ts
  test/basic.test.ts
Labels: 3.x, performance

#32139 fix(nuxt): add watch paths outside `srcDir` to parcel strategy
  .gitignore
  packages/nuxt/src/core/builder.ts
  packages/nuxt/test/builder.test.ts
Labels: 3.x, bug

#32166 perf(nuxt): skip route rules processing for empty child array
  packages/nuxt/src/pages/route-rules.ts
Labels: 3.x, performance

#32167 perf(nuxt): use Intl.Collator instead of localeCompare
  packages/nuxt/src/pages/utils.ts
Labels: 3.x, performance

#32189 chore(kit): remove unnecessary function
  packages/kit/src/template.ts
Labels: 3.x, chore

#32214 docs: fix type issue
  docs/1.getting-started/12.error-handling.md
Labels: documentation, 3.x

#32252 refactor: downgrade to nitro v2
  docs/2.guide/3.going-further/1.events.md
  docs/2.guide/3.going-further/3.modules.md
  docs/3.api/5.kit/11.nitro.md
  package.json
  packages/kit/package.json
  packages/kit/src/nitro.ts
  packages/kit/src/pages.ts
  packages/nuxt/package.json
  packages/nuxt/src/app/composables/fetch.ts
  packages/nuxt/src/app/composables/manifest.ts
  packages/nuxt/src/app/composables/ssr.ts
  packages/nuxt/src/app/nuxt.ts
  packages/nuxt/src/core/nitro.ts
  packages/nuxt/src/core/nuxt.ts
  packages/nuxt/src/core/plugins/resolved-externals.ts
  packages/nuxt/src/core/runtime/nitro/handlers/error.ts
  packages/nuxt/src/core/runtime/nitro/handlers/island.ts
  packages/nuxt/src/core/runtime/nitro/handlers/renderer.ts
  packages/nuxt/src/core/runtime/nitro/plugins/dev-server-logs.ts
  packages/nuxt/src/core/runtime/nitro/utils/cache.ts
  packages/nuxt/src/core/runtime/nitro/utils/paths.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/app.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/build-files.ts
  packages/nuxt/src/core/runtime/nitro/utils/renderer/payload.ts
  packages/nuxt/src/core/templates.ts
  packages/nuxt/src/pages/module.ts
  packages/nuxt/src/pages/route-rules.ts
  packages/nuxt/src/pages/runtime/composables.ts
  packages/nuxt/test/nitro/render-index.ts
  packages/nuxt/types.d.mts
  packages/nuxt/types.d.ts
  packages/schema/package.json
  packages/schema/src/config/nitro.ts
  packages/schema/src/config/typescript.ts
  packages/schema/src/types/config.ts
  packages/schema/src/types/debug.ts
  packages/schema/src/types/hooks.ts
  packages/schema/src/types/schema.ts
  packages/vite/package.json
  packages/vite/src/client.ts
  packages/vite/src/server.ts
  packages/webpack/src/configs/server.ts
  packages/webpack/src/presets/base.ts
  packages/webpack/src/webpack.ts
  pnpm-lock.yaml
  test/bundle.test.ts
  test/fixtures/basic-types/types.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/package.json
  test/fixtures/basic/postcss/plugin.ts
Labels: 3.x, refactor
